# Install Dependecies

In [1]:
%%capture
%pip install -q "transformers>=5,<6"
%pip install matplotlib
%pip install ipynbname
%pip install datasets
%pip install ipywidgets

In [2]:
%%capture
%pip install torch torchvision --index-url https://download.pytorch.org/whl/cu130
%pip install ipykernel

# Imports

In [37]:
import numpy as np
import pandas as pd
import random
import time
import torch
from datasets import load_dataset
from torch import nn
from torch.optim import Adam
from torch.utils.data import DataLoader
from tqdm.std import tqdm
from transformers import AutoTokenizer
from transformers import AutoModel
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import precision_recall_fscore_support

# Import datasets

In [4]:
dataset = load_dataset("coastalcph/tydi_xor_rc")
df_train = dataset["train"].to_pandas()
df_val = dataset["validation"].to_pandas()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

# Preprocessing

In [5]:
LANGUAGES = ["ar", "ko", "te"]

In [6]:
# select languages
df_train = df_train[df_train["lang"].isin(LANGUAGES)].copy()
df_val = df_val[df_val["lang"].isin(LANGUAGES)].copy()

# Tokeniser

In [7]:
tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base")

# 3 Week 37: Structured Span Prediction
* Convert the character-level answer offsets into BIO labels over context tokens. 
* Add automatic checks for at least the following cases: 
  - an answer at character 0, 
  - a multi-token answer, 
  - punctuation adjacent to an answer and an unanswerable example. 
* Document how subword pieces are handled if applicable. 
* Implement one question-conditioned sequence labeller for the group: the representation of the question must influence the predicted label for every context token. 
* Compare it with a simple span baseline. An empty-output baseline is sufficient. If you use lexical overlap, select context tokens using only overlap with the question (optionally after fixed preprocessing or translation), convert the best contiguous run to a span and never use gold answer text or offsets. The correct output for an unanswerable question is an empty span. Evaluate and analyse the models according to Section 1.

### 1. Convert the character-level answer offsets into BIO labels over context tokens

In [8]:
def tokenize_with_offsets(text):
    encoding = tokenizer(text, return_offsets_mapping=True, add_special_tokens=False)
    tokens = tokenizer.convert_ids_to_tokens(encoding["input_ids"])
    offsets = [tuple(offset) for offset in encoding["offset_mapping"]]
    return tokens, offsets

In [9]:
# lab_2.ipynb
def character_span_to_bio(context, answer_start=None, answer_text=""):
    tokens, offsets = tokenize_with_offsets(context)
    labels = ["O"] * len(tokens)

    if answer_start is None or answer_text == "":
        return tokens, offsets, labels

    answer_end = answer_start + len(answer_text)
    if context[answer_start:answer_end] != answer_text:
        raise ValueError("The supplied answer text does not match the character span")

    covered = [
        index
        for index, (start, end) in enumerate(offsets)
        if start < answer_end and end > answer_start
    ]
    if not covered:
        raise ValueError("The answer does not overlap any token")

    labels[covered[0]] = "B-ANS"
    for index in covered[1:]:
        labels[index] = "I-ANS"
    return tokens, offsets, labels

In [10]:
# lab_2.ipynb
def bio_to_character_span(context, offsets, labels):
    if len(offsets) != len(labels):
        raise ValueError("Offsets and labels must have the same length")
    if not set(labels) <= {"O", "B-ANS", "I-ANS"}:
        raise ValueError("Only O, B-ANS and I-ANS labels are supported")

    answer_indices = [
        index for index, label in enumerate(labels) if label != "O"
    ]
    if not answer_indices:
        return None, ""

    start_index = answer_indices[0]
    expected_indices = list(range(start_index, start_index + len(answer_indices)))
    expected_labels = ["B-ANS"] + ["I-ANS"] * (len(answer_indices) - 1)
    if answer_indices != expected_indices:
        raise ValueError("The labels contain multiple or non-contiguous answer spans")
    if [labels[index] for index in answer_indices] != expected_labels:
        raise ValueError("The answer span must begin with B-ANS and continue with I-ANS")

    start = offsets[answer_indices[0]][0]
    end = offsets[answer_indices[-1]][1]
    return start, context[start:end]

### Apply to both splits
Unanswerable rows have `answer_start == -1` (their `answer` column is not empty), so we key on `answerable` and give them all-`O` labels.

In [11]:
def row_to_bio(row):
    if not row["answerable"]:
        return character_span_to_bio(row["context"])
    return character_span_to_bio(row["context"], row["answer_start"], row["answer"])

In [12]:
# train
results = [row_to_bio(row) for _, row in df_train.iterrows()]
df_train["tokens"] = [tokens for tokens, offsets, labels in results]
df_train["offsets"] = [offsets for tokens, offsets, labels in results]
df_train["labels"] = [labels for tokens, offsets, labels in results]
df_train

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (547 > 512). Running this sequence through the model will result in indexing errors

,question,context,lang,answerable,answer_start,answer,answer_inlang,tokens,offsets,labels
4792,30년 전쟁의 승자는 누구인가?,The conflict between France and Spain continue...,ko,True,21,France,None,"[▁The, ▁conflict, ▁between, ▁France, ▁and, ▁Sp...","[(0, 3), (4, 12), (13, 20), (21, 27), (28, 31)...","[O, O, O, B-ANS, O, O, O, O, O, O, O, O, O, O,..."
4793,엑스선은 누가 발견하였는가?,"X-rays make up X-radiation, a form of electrom...",ko,True,503,Wilhelm Röntgen,None,"[▁X, -, ray, s, ▁make, ▁up, ▁X, -, radi, ation...","[(0, 1), (1, 2), (2, 5), (5, 6), (7, 11), (12,...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
4794,아테네에서 언제 가장 최근의 올림픽이 올렸나요?,"In 2022, Beijing will become the first-ever ci...",ko,True,188,2004,None,"[▁In, ▁2022, ,, ▁Beijing, ▁will, ▁become, ▁the...","[(0, 2), (3, 7), (7, 8), (9, 16), (17, 21), (2...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
4795,세상에서 가장 오래된 방송사는 무엇인가?,The British Broadcasting Corporation (BBC) is ...,ko,True,4,British Broadcasting Corporation (BBC),None,"[▁The, ▁British, ▁Broadcast, ing, ▁Corporation...","[(0, 3), (4, 11), (12, 21), (21, 24), (25, 36)...","[O, B-ANS, I-ANS, I-ANS, I-ANS, I-ANS, I-ANS, ..."
4796,팔레스타인 수도는 어딘가요?,"Palestine ( '), officially the State of Palest...",ko,True,205,Jerusalem,None,"[▁Palestin, e, ▁(, ▁', ),, ▁official, ly, ▁the...","[(0, 8), (8, 9), (10, 11), (12, 13), (13, 15),...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
...,...,...,...,...,...,...,...,...,...,...
15338,소말리아는 2차 개헌을 언제 했나요?,"In February 2012, Somali government officials ...",ko,True,923,23 June 2012,None,"[▁In, ▁February, ▁2012,, ▁Somali, ▁government,...","[(0, 2), (3, 11), (12, 17), (18, 24), (25, 35)...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
15339,세상에서 가장 먼저 시작된 교통수단은 무엇인가?,The first earth tracks were created by humans ...,ko,True,160,animals,None,"[▁The, ▁first, ▁earth, ▁track, s, ▁were, ▁crea...","[(0, 3), (4, 9), (10, 15), (16, 21), (21, 22),...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
15340,2019년 이집트의 지도자는 누구인가?,"Abdel Fattah Saeed Hussein Khalil El-Sisi ( """"...",ko,True,0,Abdel Fattah Saeed Hussein Khalil El-Sisi,None,"[▁Ab, del, ▁Fat, tah, ▁Sa, eed, ▁Hussein, ▁Kha...","[(0, 2), (2, 5), (6, 9), (9, 12), (13, 15), (1...","[B-ANS, I-ANS, I-ANS, I-ANS, I-ANS, I-ANS, I-A..."
15341,독일에서 가장 인구밀도가 높은 도시는 무엇인가?,Munich (; ; ) is the capital and most populous...,ko,True,205,Berlin,None,"[▁Munich, ▁(, ;, ▁;, ▁), ▁is, ▁the, ▁capital, ...","[(0, 6), (7, 8), (8, 9), (10, 11), (12, 13), (...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
15342,개혁침례교는 신교와 상관관계가있는가?,"Anabaptism (from Neo-Latin ""anabaptista"", from...",ko,False,-1,no,None,"[▁Ana, baptis, m, ▁(, from, ▁Neo, -, La, tin, ...","[(0, 3), (3, 9), (9, 10), (11, 12), (12, 16), ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."

In [13]:
# val
results = [row_to_bio(row) for _, row in df_val.iterrows()]
df_val["tokens"] = [tokens for tokens, offsets, labels in results]
df_val["offsets"] = [offsets for tokens, offsets, labels in results]
df_val["labels"] = [labels for tokens, offsets, labels in results]
df_val

,question,context,lang,answerable,answer_start,answer,answer_inlang,tokens,offsets,labels
0,ఒరెగాన్ రాష్ట్రంలోని అతిపెద్ద నగరం ఏది ?,Portland is the largest city in the U.S. state...,te,True,0,Portland,None,"[▁Portland, ▁is, ▁the, ▁largest, ▁city, ▁in, ▁...","[(0, 8), (9, 11), (12, 15), (16, 23), (24, 28)...","[B-ANS, O, O, O, O, O, O, O, O, O, O, O, O, O,..."
1,కలరా వ్యాధిని మొదటగా ఏ దేశంలో కనుగొన్నారు ?,"The word cholera is from ""kholera"" from χολή ""...",te,True,99,Indian subcontinent,None,"[▁The, ▁word, ▁cho, lera, ▁is, ▁from, ▁"", kho,...","[(0, 3), (4, 8), (9, 12), (12, 16), (17, 19), ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
2,కలరా వ్యాధిని మొదటగా ఏ దేశంలో కనుగొన్నారు ?,Since it became widespread in the 19th century...,te,True,451,England,None,"[▁Since, ▁it, ▁became, ▁wide, spre, ad, ▁in, ▁...","[(0, 5), (6, 8), (9, 15), (16, 20), (20, 24), ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
3,మొదటి ప్రపంచ యుద్ధం ఎప్పుడు మొదలయింది ?,World War I occurred from 1914 to 1918. In ter...,te,True,26,1914,None,"[▁World, ▁War, ▁I, ▁occur, red, ▁from, ▁1914, ...","[(0, 5), (6, 9), (10, 11), (12, 17), (17, 20),...","[O, O, O, O, O, O, B-ANS, O, O, O, O, O, O, O,..."
4,మొదటి ప్రపంచ యుద్ధం ఎప్పుడు మొదలయింది ?,"World War I (often abbreviated as WWI or WW1),...",te,True,155,28 July 1914,None,"[▁World, ▁War, ▁I, ▁(, o, ften, ▁ab, brev, i, ...","[(0, 5), (6, 9), (10, 11), (12, 13), (13, 14),...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
...,...,...,...,...,...,...,...,...,...,...
3006,2011 జనగణన ప్రకారం రెయ్యలగడ్ద గ్రామములో పురుషు...,Reyyalagadda is a village belonging to Gangara...,te,True,378,37,37,"[▁Rey, ya, lag, adda, ▁is, ▁a, ▁village, ▁belo...","[(0, 3), (3, 5), (5, 8), (8, 12), (13, 15), (1...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
3007,2011 జనాభా లెక్కల ప్రకారం బూతుమిల్లిపాడు గ్రామ...,Boothumillipadu is a village in Gannavaram man...,te,True,308,433,433,"[▁Boot, hu, milli, padu, ▁is, ▁a, ▁village, ▁i...","[(0, 4), (4, 6), (6, 11), (11, 15), (16, 18), ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
3008,2011 జనాభా లెక్కల ప్రకారం మల్లవేముల గ్రామ జనాభ...,Mallavemula is a village belonging to Chagalam...,te,False,-1,1131,1131,"[▁Mall, ave, mula, ▁is, ▁a, ▁village, ▁belo, n...","[(0, 4), (4, 7), (7, 11), (12, 14), (15, 16), ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
3009,2011 నాటికి రష్యా దేశ ప్రధాన మంత్రి ఎవరు?,"Andria Urushadze (; born April 25, 1968) is a ...",te,False,-1,Vladimir Putin,వ్లాదిమిర్ పుతిన్,"[▁Andri, a, ▁Ur, usha, dze, ▁(, ;, ▁born, ▁Apr...","[(0, 5), (5, 6), (7, 9), (9, 13), (13, 16), (1...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
3010,2011 భారత జనగణన గణాంకాల ప్రకారం గుంటూరు పట్టణ ...,"Guntur district is 11,391 sq. km. Spread over ...",te,False,-1,"743,654","743,654","[▁G, untur, ▁district, ▁is, ▁11, ,, 391, ▁s, q...","[(0, 1), (1, 6), (7, 15), (16, 18), (19, 21), ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."

### Round trip: labels back to a character span

In [14]:
def round_trip(row):
    start, text = bio_to_character_span(row["context"], row["offsets"], row["labels"])
    return text

In [15]:
# train
ans = df_train[df_train["answerable"]]
recovered = [round_trip(row) for _, row in ans.iterrows()]
exact = [text == answer for text, answer in zip(recovered, ans["answer"])]
contains = [answer in text for text, answer in zip(recovered, ans["answer"])]
print(f"checked: {len(ans)}; exact: {sum(exact)}; fail: {contains.count(False)}")

checked: 5972; exact: 5598; fail: 0

In [16]:
# val
ans = df_val[df_val["answerable"]]
recovered = [round_trip(row) for _, row in ans.iterrows()]
exact = [text == answer for text, answer in zip(recovered, ans["answer"])]
contains = [answer in text for text, answer in zip(recovered, ans["answer"])]
print(f"checked: {len(ans)}; exact: {sum(exact)}; fail: {contains.count(False)}")

checked: 991; exact: 941; fail: 0

### Label distribution

In [17]:
# from lab_2.ipynb: "Audit the label distribution" (adapted to string labels)
# train
label_counts = pd.Series([label for labels in df_train["labels"] for label in labels]).value_counts()
display(pd.DataFrame({"count": label_counts, "proportion": label_counts / label_counts.sum()}))

        count  proportion
O      890224    0.966669
I-ANS   24723    0.026846
B-ANS    5972    0.006485

In [18]:
# val
label_counts = pd.Series([label for labels in df_val["labels"] for label in labels]).value_counts()
display(pd.DataFrame({"count": label_counts, "proportion": label_counts / label_counts.sum()}))

        count  proportion
O      170678    0.972203
I-ANS    3889    0.022152
B-ANS     991    0.005645

In [19]:
row = df_train[df_train["answerable"]].iloc[0]
start = row["labels"].index("B-ANS")
print(row["question"] + " | " + row["answer"])
display(pd.DataFrame({"token": row["tokens"], "offset": row["offsets"], "label": row["labels"]}).iloc[start - 3:start + 4])

30년 전쟁의 승자는 누구인가? | France

        token    offset  label
0        ▁The    (0, 3)      O
1   ▁conflict   (4, 12)      O
2    ▁between  (13, 20)      O
3     ▁France  (21, 27)  B-ANS
4        ▁and  (28, 31)      O
5      ▁Spain  (32, 37)      O
6  ▁continued  (38, 47)      O

### 2. Automatic checks
1. An answer at character 0
2. A multi-token answer
3. Punctuation adjacent to an answer
4. An unanswerable example.

In [20]:
# check 1: answer at character 0
context = "NLP is the best course at DIKU."
answer = "NLP"
tokens, offsets, labels = character_span_to_bio(context, 0, answer)
print(116 * "-")
print("check 1:  answer at character 0")
print("context: ", context)
print("answer:  ", answer)
print("tokens:  ", tokens)
print("offsets: ", offsets)
print("labels:  ", labels)
print(116 * "-")
assert tokens == ["▁N", "LP", "▁is", "▁the", "▁best", "▁course", "▁at", "▁D", "IKU", "."]
assert labels == ["B-ANS", "I-ANS", "O", "O", "O", "O", "O", "O", "O", "O"]
assert bio_to_character_span(context, offsets, labels) == (0, answer)

# check 2: multi-token answer
context = "Rumour has it that Natural language processing is the only course where the homework talks back."
answer = "Natural language processing"
tokens, offsets, labels = character_span_to_bio(context, context.index(answer), answer)
print("check 2:  multi-token answer")
print("context: ", context)
print("answer:  ", answer)
print("tokens:  ", tokens)
print("offsets: ", offsets)
print("labels:  ", labels)
print(116 * "-")
assert tokens[5:9] == ["▁Natural", "▁language", "▁process", "ing"]
assert labels[5:9] == ["B-ANS", "I-ANS", "I-ANS", "I-ANS"]
assert labels[:5] == ["O"] * 5 and labels[9:] == ["O"] * 12
assert bio_to_character_span(context, offsets, labels) == (context.index(answer), answer)

# check 3: punctuation adjacent to the answer
context = "The tokenizer was last seen in Copenhagen, crying over Telegu tokens."
answer = "Copenhagen"
tokens, offsets, labels = character_span_to_bio(context, context.index(answer), answer)
print("check 3:  punctuation adjacent to the answer")
print("context: ", context)
print("answer:  ", answer)
print("tokens:  ", tokens)
print("offsets: ", offsets)
print("labels:  ", labels)
print(116 * "-")
assert tokens[8:10] == ["▁Copenhagen", ","]
assert labels[8:10] == ["B-ANS", "O"]
assert labels.count("B-ANS") == 1 and labels.count("I-ANS") == 0
assert bio_to_character_span(context, offsets, labels) == (context.index(answer), answer)

# check 4: unanswerable example
tokens, offsets, labels = character_span_to_bio(context)
print("check 4:  unanswerable example")
print("context: ", context)
print("answer:  ", answer)
print("tokens:  ", tokens)
print("offsets: ", offsets)
print("labels:  ", labels)
assert labels == ["O"] * len(tokens)
assert bio_to_character_span(context, offsets, labels) == (None, "")
print(116 * "-")

--------------------------------------------------------------------------------------------------------------------
check 1:  answer at character 0
context:  NLP is the best course at DIKU.
answer:   NLP
tokens:   ['▁N', 'LP', '▁is', '▁the', '▁best', '▁course', '▁at', '▁D', 'IKU', '.']
offsets:  [(0, 1), (1, 3), (4, 6), (7, 10), (11, 15), (16, 22), (23, 25), (26, 27), (27, 30), (30, 31)]
labels:   ['B-ANS', 'I-ANS', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']
--------------------------------------------------------------------------------------------------------------------
check 2:  multi-token answer
context:  Rumour has it that Natural language processing is the only course where the homework talks back.
answer:   Natural language processing
tokens:   ['▁Rum', 'our', '▁has', '▁it', '▁that', '▁Natural', '▁language', '▁process', 'ing', '▁is', '▁the', '▁only', '▁course', '▁where', '▁the', '▁home', 'work', '▁talk', 's', '▁back', '.']
offsets:  [(0, 3), (3, 6), (7, 10), (11, 13), (14, 18), (19, 26), (27, 35), (36, 43), (43, 46), (47, 49), (50, 53), (54, 58), (59, 65), (66, 71), (72, 75), (76, 80), (80, 84), (85, 89), (89, 90), (91, 95), (95, 96)]
labels:   ['O', 'O', 'O', 'O', 'O', 'B-ANS', 'I-ANS', 'I-ANS', 'I-ANS', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']
--------------------------------------------------------------------------------------------------------------------
check 3:  punctuation adjacent to the answer
context:  The tokenizer was last seen in Copenhagen, crying over Telegu tokens.
answer:   Copenhagen
tokens:   ['▁The', '▁to', 'ken', 'izer', '▁was', '▁last', '▁seen', '▁in', '▁Copenhagen', ',', '▁cry', 'ing', '▁over', '▁Tele', 'gu', '▁to', 'kens', '.']
offsets:  [(0, 3), (4, 6), (6, 9), (9, 13), (14, 17), (18, 22), (23, 27), (28, 30), (31, 41), (41, 42), (43, 46), (46, 49), (50, 54), (55, 59), (59, 61), (62, 64), (64, 68), (68, 69)]
labels:   ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-ANS', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']
--------------------------------------------------------------------------------------------------------------------
check 4:  unanswerable example
context:  The tokenizer was last seen in Copenhagen, crying over Telegu tokens.
answer:   Copenhagen
tokens:   ['▁The', '▁to', 'ken', 'izer', '▁was', '▁last', '▁seen', '▁in', '▁Copenhagen', ',', '▁cry', 'ing', '▁over', '▁Tele', 'gu', '▁to', 'kens', '.']
offsets:  [(0, 3), (4, 6), (6, 9), (9, 13), (14, 17), (18, 22), (23, 27), (28, 30), (31, 41), (41, 42), (43, 46), (46, 49), (50, 54), (55, 59), (59, 61), (62, 64), (64, 68), (68, 69)]
labels:   ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']
--------------------------------------------------------------------------------------------------------------------

### 3. Implement one question-conditioned sequence labeller for the group
The representation of the question must influence the predicted label for every context token.

In [21]:
# lab_2.ipynb
BIO_TAGS = ["O", "B-ANS", "I-ANS"]
TAG_TO_ID = {tag: index for index, tag in enumerate(BIO_TAGS)}

In [22]:
# turns the question into a set of its XLM-R pieces so that each context token can be checked if it also occurs in the question
def question_pieces_of(question):
    pieces = tokenizer.tokenize(question)
    res = set(pieces) | {piece.lower() for piece in pieces}
    print(res)
    return res

In [23]:
# ar question word first in a sentence (reading direction: right-to-left)
# summarises the question type as its first and last piece so that the question word can be paired with each context token shape
def question_words_of(question):
    pieces = [piece for piece in tokenizer.tokenize(question) if piece not in {"?", "؟"}]
    return pieces[0] + " | " + pieces[-1]

In [24]:
# lab_2.ipynb
def token_features(tokens, index, question_pieces, question_words):
    word = tokens[index]
    features = {
        "bias": 1.0,
        "word.lower": word.lower(),
        "word.prefix2": word[:2].lower(),
        "word.suffix2": word[-2:].lower(),
        "word.suffix3": word[-3:].lower(),
        "word.istitle": word.istitle(),
        "word.isupper": word.isupper(),
        "word.isdigit": word.isdigit(),
        "contains_hyphen": "-" in word,
        "word.in_question": word in question_pieces,  # added feature
        "word.lower_in_question": word.lower() in question_pieces,  # added feature
        "question_words|word.isdigit": f"{question_words}|{word.isdigit()}",  # added feature
        "question_words|word.istitle": f"{question_words}|{word.istitle()}",  # added feature
    }

    if index == 0:
        features["BOS"] = True
    else:
        previous = tokens[index - 1]
        features.update({
            "previous.lower": previous.lower(),
            "previous.istitle": previous.istitle(),
            "previous.isupper": previous.isupper(),
            "previous.in_question": previous in question_pieces,
        })

    if index == len(tokens) - 1:
        features["EOS"] = True
    else:
        following = tokens[index + 1]
        features.update({
            "next.lower": following.lower(),
            "next.istitle": following.istitle(),
            "next.isupper": following.isupper(),
            "next.in_question": following in question_pieces,
        })

    return features

In [25]:
# lab_2.ipynb
def featurize(df):
    features, labels, lengths = [], [], []
    for tokens, row_labels, question in zip(df["tokens"], df["labels"], df["question"]):
        question_pieces = question_pieces_of(question)
        question_words = question_words_of(question)
        lengths.append(len(tokens))
        features.extend(token_features(tokens, index, question_pieces, question_words) for index in range(len(tokens)))
        labels.extend(TAG_TO_ID[label] for label in row_labels)
    return features, np.asarray(labels), lengths

In [26]:
# lab_2.ipynb
def split_by_lengths(values, lengths):
    sequences = []
    offset = 0
    for length in lengths:
        sequences.append(list(values[offset:offset + length]))
        offset += length
    assert offset == len(values)
    return sequences

In [27]:
# train
train_features, train_labels, train_lengths = featurize(df_train)

{'▁누구', '인가', '자는', '▁승', '?', '▁전쟁', '년', '▁30', '의'}
{'엑스', '▁', '하였', '은', '는', '▁발견', '?', '선', '가', '▁누가'}
{'▁', '▁언제', '에서', '렸', '▁최근', '▁올', '이', '▁가장', '?', '▁아', '올림픽', '네', '테', '의', '나요'}
{'▁오래', '▁가장', '?', '▁무엇인가', '에서', '사는', '된', '▁방송', '▁세상'}
{'인', '딘', '▁어', '스타', '는', '레', '▁수도', '?', '가요', '▁팔'}
{'▁별', '자', '▁', '▁중', '▁무엇인가', '▁이루어', '▁많은', '리는', '별로', '▁가장', '?', '진', '자리'}
{'▁발전', '▁에너지', '▁무엇인가', '에서', '력', '▁세상', '는', '▁가장', '?', '▁풍', '▁큰', '소'}
{'▁본', '▁무엇인가', '▁15', '명', '이', '▁루', '은', '?', '세', '의'}
{'▁', '▁어디', '텔', '▁처음', '비', '▁출시', '▁기업', '▁컬러', '인가', '이', '은', '레', '?', '된', '전'}
{'▁황', '▁누구', '인가', '국', '는', '아', '우리', '?', '제', '▁제', '▁마', '▁초대', '의'}
{'▁', '였', '▁관계', '틀', '는', '?', '▁힘', '러', '히', '▁무슨', '가', '와'}
{'로', '▁구성', '▁실', '율', '에', '▁있는', '표', '되어', '▁', '리', '들', '콘', '주기', '은', '?', '▁어떤', '▁원', '가', '소'}
{'▁언제', '▁끝', '기는', '강', '점', '▁일', '는', '났', '?', '제', '가'}
{'▁무엇인가', '에서', '▁많은', '즈', '식', '▁세상', '▁프', '▁외', '이', '는', '▁가장', '?', '차', '랜'}
{'켈', '로', '▁언제', '▁총', '리', '▁취', '르', '했', '리는', '▁독일', '임', '?', '▁메', '의', '나요'}
{'인가', '는', '▁수도', '▁어디', '?', '▁영국', '의'}
{'▁발전', '자', '▁어디', '▁국가', '▁먼저', '력', '동', '인가', '는', '▁가장', '?', '▁가', '▁원', '한', '소', '를'}
{'은', '광', '▁달', '하는', '?', '발', '▁자체', '가'}
{'인가', '은', '▁달', '▁지구', '▁배', '?', '▁몇', '의'}
{'행', '▁2019', '흥', '드', '▁영화', '치', '▁알', '콕', '까지', '한', '▁', '▁중', '년', '▁무엇인가', '▁대중', '는', '▁가장', '?', '프레', '히', '적으로', '의'}
{'▁일본', '▁국', '로', '▁번째', '년', '에서', '▁많은', '▁2018', '했', '은', '는', '?', '방', '▁세계', '▁몇', '비를', '가', '▁투자'}
{'▁기', '인', '▁어디', '판', '▁대하여', '?', '에', '원', '▁종', '사는', '▁출', '가요', '의'}
{'대', '인', '군', '▁어디', '단체', '동', '는', '▁적', '민', '?', '▁인', '원', '가요', '의'}
{'▁성경', '은', '▁책', '?', '▁무엇인가', '▁마지막', '의'}
{'▁처음', '디아', '▁무엇인가', '▁등록', '피', '키', '는', '▁페이지', '▁위', '?', '에', '된'}
{'▁어디', '▁인구', '에서', '인가', '▁호주', '도가', '는', '▁가장', '▁도시', '?', '▁높은', '밀'}
{'▁온라인', '▁무엇인가', '에서', '▁게임', '▁세상', '은', '▁오래', '▁가장', '?', '된'}
{'▁2019', '▁인구', '▁포', '클', '월', '▁삼', '인가', '▁기준', '▁몇', '▁5', '를', '년', ',', '거', '랜드', '명', '지로', '은', '는', '?', '▁주'}
{'▁시청', '▁2019', '▁기록', '▁역사', '▁미국', '까지', '한', '▁', '년', '▁무엇인가', '▁abc', '을', '▁ABC', '은', '▁가장', '?', '상', '▁높은', '방송', '률', '▁프로그램'}
{'▁', '되었', '▁처음', '닥', '▁방', '는', '터', '?', '에', '영', '▁몇', '년도', '가', '▁후'}
{'▁되', '리아', '에서', '▁거리', '▁이탈리아', '는', '▁오', '?', '▁얼마나', '까지', '스트', '나요'}
{'▁어디', '▁인구', '▁지역', '에서', '▁중국', '인가', '은', '도가', '▁가장', '?', '▁높은', '밀'}
{'▁어디', '▁처음', '텔', '유', '▁국가', '스', '기를', '인가', '는', '?', '▁보', '한', '▁스'}
{'▁성경', '은', '▁책', '▁가장', '?', '▁무엇인가', '▁첫번째', '의'}
{'▁작', '▁', '▁많은', '을', '▁누구', '인가', '니', '는', '▁가장', '?', '상', '▁역사', '피아', '곡', '한', '스트'}
{'▁기', '액', '▁', '▁중', ',', '▁고', '▁무엇인가', '체', '▁빠른', '▁상태', '▁열', '▁전', '도가', '는', '▁가장', '?'}
{'에서', '▁포', '▁로', '했', '▁승리', '마', '니', '?', '에', '▁전쟁', '가', '나요'}
{'▁제일', '▁무엇인가', '에서', '클', '요', '라', '마', '는', '▁오', '▁도시', '?', '주', '▁큰', '호'}
{'▁', '▁인구', '니아', '인가', '는', '주의', '웨', '지', '?', '버', '스트', '▁얼마'}
{'인가', '라는', '▁현재', '▁어디', '?', '나', '▁청', '의'}
{'▁중', '골', '▁강', '었', '▁왜', '점', '을', '몽', '하고', '▁외', '은', '국', '는', '민', '?', '있', '화', '가'}
{'▁언제', '▁최초', '는', '▁한국', '?', '에', '졌', '▁자동차', '▁만들어', '나요'}
{'▁되었', '▁', '▁언제', '닥', '는', '터', '?', '방송', '▁첫', '▁후', '나요'}
{'▁서', '▁언제', '철', '도는', '객', '했', '립', '?', '▁창', '▁여', '일본', '나요'}
{'시', '▁', '멕', '되었', '▁언제', '▁승인', '은', '▁독립', '?', '코', '의', '나요'}
{'대', '인', '▁누구', '은', '▁대통령', '?', '▁미국', '▁5', '가요', '▁제'}
{'왕', '▁국', '▁언제', '위', '▁16', '▁즉', '했', '이', '▁루', '는', '?', '세', '으로', '나요'}
{'은', '▁달', '▁지구', '?', '에서', '▁얼마나', '▁있는', '▁멀리', '가'}
{'▁인도', '▁화', '인가', '는', '?', '시아', '네', '폐', '▁얼마', '의'}
{'▁', '해', '▁주는', '▁무엇인가', '▁속', '요', '스코', '있는', '샌', '?', '란', '프', '가', '시'}
{'토', '▁지역', '▁어느', '을', '▁뜻', '은', '▁현재', '▁지방', '하는', '?', '▁간', '가'}
{'▁기', '인', '교', '▁국', '독', '인가', '는', '국', '?', '개', '▁몇', '▁나라', '가'}
{'▁누구', '인가', '▁독일', '자는', '?', '▁2019', '년', '▁지도', '의'}
{'은', '▁대통령', '▁현대', '?', '▁중국', '요', '▁누군가'}
{'▁일본', '부터', '되었', '야구', '▁언제', '▁시작', '는', '▁프로', '?', '▁역사', '가', '의'}
{'▁사용', '는', '?', '▁무엇인가', '에서', '되는', '▁프랑스', '폐', '▁화'}
{'▁처음', '에서', '▁어느', '▁최초', '▁생', '장은', '겨', '났', '?', '▁세계', '▁극', '▁나라', '의', '나요'}
{'는', '국어', '▁', '?', '▁무엇인가', '이란', '의'}
{'▁', '▁무엇인가', '솅', '▁가입', '함으로써', '겐', '?', '▁조', '에', '▁이', '약', '점은'}
{'인', '▁독일', '는', '▁도시', '▁어디', '?', '▁최대', '가요', '의'}
{'인', '▁연', '▁', '▁제일', '▁하는', '▁어디', '을', '는', '바이오', '?', '료', '▁나라', '가요', '▁생산', '▁많이'}
{'연합', '▁', '드는', '▁언제', '했', '▁가입', '?', '란', '에', '▁유럽', '폴', '나요'}
{'집', '라는', '▁별', '파', '했', '레', '?', '에', '▁클', '세', '▁이', '▁몇', '오', '트', '의', '나요'}
{'인가', '는', '디', '?', '▁명', '▁몇', '▁간', '▁자녀', '의'}
{'▁개', '국어', '▁', '로', '▁중국', '어', '▁사용하는', '인가', '는', '국', '?', '▁몇', '▁나라', '를'}
{'▁되었', '▁언제', '키', '과', '백', '는', '▁위', '?', '▁설립', '나요'}
{'인가', '는', '▁가장', '▁도시', '▁어디', '?', '▁큰', '에서', '▁영국'}
{'년', '석', '▁중국', '▁2018', '▁누구', '인가', '은', '?', '▁주', '의'}
{'는', '▁맥', '▁발견', '주', '▁언제', '되었', '?', '▁처음으로', '가'}
{'▁처음', '▁와이', '▁누구', '인가', '▁사람은', '?', '파이', '한', '▁개발', '를'}
{'라는', '너', '▁언제', '▁무', '나', '는', '?', '▁명', '졌', '가'}
{'교', '▁', '되었', '▁시작', '▁몰', '는', '몬', '?', '에', '▁몇', '년도', '가'}
{'▁누구', '인', '은', '▁대통령', '?', '년', '▁중국', '▁2002', '가요'}
{'은', '▁가장', '▁중', '▁강한', '?', '▁무엇인가', '▁행', '성', '력이'}
{'단', '▁nba', '▁', '▁총', '▁NBA', '에서', '인가', '은', '하는', '?', '개', '구', '▁몇', '농구', '▁활동'}
{'집', '▁군', '▁언제', '했', '헌', '는', '국', '▁독립', '?', '주', '▁이', '으로', '트', '▁입', '나요'}
{'인', '▁', '▁제일', '▁어디', '에서', 'gdp', '▁2018', '는', '?', '▁아시아', '▁높은', 'GDP', '▁나라', '가요', '가'}
{'▁남', '에는', '개의', '▁있나요', '?', '▁미국', '▁주', '▁몇', '가', '부'}
{'자는', '경영', '▁2019', '년', '▁누구', '인가', '?', '▁최고', '▁애플', '의'}
{'인가', '는', '▁가장', '▁도시', '▁어디', '?', '▁큰', '에서', '▁러시아'}
{'▁독일', '▁가장', '?', '▁주는', '▁무엇인가', '▁큰', '에서'}
{'▁호', '▁어느', '▁전', '인가', '스는', '?', '설', '▁문화', '▁나라', '적', '루', '의'}
{'▁무엇인가', '에서', '▁기업', '은', '▁가장', '▁한국', '?', '▁큰', '▁규모', '가'}
{'▁광', '▁사이', '인', '배', '▁배', '성', '에서', '▁10', '▁수', '은', '도가', '?', '▁거', '천', '가요'}
{'싱', '▁', '워', '▁된', '▁누구', '인가', '은', '지', '?', '▁조', '턴', '▁대통령이', '▁다음', '으로', '▁인물'}
{'인', '▁발전', '자', '력', '는', '▁한국', '?', '에', '개', '▁원', '▁몇', '가요', '소'}
{'▁', '되었', '▁첫번째', '명', '▁어디서', '는', '시계', '?', '▁발', '가'}
{'▁', '딘', '드', '▁어', '는', '▁수도', '?', '란', '폴', '가요'}
{'동안', '해', '년', '▁무엇인가', '에서', '▁판매', '요', '▁도', '▁2018', '는', '▁가장', '?', '▁한', '된', '타', '▁자동차', '▁많이'}
{'▁2017', '해', '▁선수', '▁많은', '▁기록', '인가', '메이', '한', '동안', '▁', '리그', '년', '을', '▁누구', '는', '▁가장', '?', '저', '▁한', '홈런'}
{'▁', '딘', '랜드', '▁어', '스코', '틀', '는', '▁수도', '?', '가요'}
{'븐', '▁무엇인가', '▁종교', '틴', '요', '▁영화', '는', '▁감독', '?', '버', '필', '그', '의', '▁스'}
{'▁공연', '로', '▁최초', '▁누구', '인가', '▁사람은', '?', '▁노', '한', '를'}
{'▁', '에는', '개의', '▁2019', '년', ',', '월', '▁대학', '▁독일', '이', '?', '▁기준', '▁있는', '▁몇', '▁5', '가'}
{'▁우주', '켓', '로', '▁로', '▁최초', '명', '을', '했', '는', '?', '▁발', '가', '▁누가'}
{'존', '▁중', '▁어디', '▁브랜드', '▁현', '▁기타', '는', '인가', '▁오래', '▁가장', '하는', '?', '된'}
{'대', '▁복', '▁기간', '▁군', '▁', '▁2019', '년', ',', '월', '인가', '은', '며', '?', '칠', '▁5', '▁기준', '▁대한민국', '무'}
{'은', '황', '하는', '▁생활', '?', '가', '▁어디서', '▁교'}
{'인', '액', '해', '년', '리', '피', '▁필', '핀', '인가', '은', '▁재산', '풍', '▁2011', '?', '으로', '▁얼마', '▁태'}
{'▁되었', '은', '▁냉', '는', '?', '▁언제', '▁시작', '전', '가'}
{'망', '▁어느', '르', '는', '디', '?', '에', '▁노', '▁있는', '▁나라', '가'}
{'는', '국', '▁수도', '?', '가요', '딘', '▁어', '▁태', '의'}
{'▁', '해', '▁속', '지는', '▁어느', '니', '륙', '있는', '?', '에', '튀', '▁대', '가'}
{'▁후기', '년', '전을', '▁얘기', '하는', '?', '란', '▁정확', '악', '▁몇', '▁백', '가', '기'}
{'▁되었', '▁에', '▁언제', '▁처음', '리', '▁영화', '는', '언', '?', '일', '▁개봉', '나요'}
{'▁왕', '▁통', '▁오랜', '에서', '▁중국', '기간', '▁누구', '인가', '은', '치', '▁가장', '?', '상', '▁역사', '한'}
{'▁개', '▁동', '▁구성', '은', '국', '있는', '?', '으로', '▁몇', '유럽', '가', '되어'}
{'급', '▁2019', '년', '▁무엇인가', '▁계', '도는', '▁영국', '▁현재', '?', '의'}
{'▁일본', '인', '▁어디', '지는', '▁녹', '?', '차', '▁최대', '▁생산', '가요', '의'}
{'▁둘', '에서', '과', '▁물', '어', '▁땅', '▁살', '▁수', '는', '?', '▁있을까', '▁악', '▁다'}
{'싱', '▁', '▁무엇인가', '▁새', '▁이름', '은', '?', '원의', '▁공', '폴', '가'}
{'평', '투', '로', '해', '▁울', '▁결과', '▁전', '?', '진', '▁이', '▁어떤', '겼', '▁나라', '가', '-', '나요'}
{'까', '▁남아', '▁인구', '리', '▁될', '카', '메', '는', '?', '▁얼마나', '의'}
{'▁이유는', '슬', '▁무엇인가', '▁유', '어', '라', '▁일', '이', '고', '?', '전', '▁내', '비아', '난'}
{'자', '▁중', '?', '란', '▁무엇인가', '성'}
{'▁', '▁치료', '▁수', '할', '이', '?', '곰', '▁상처', '▁있을까', '팡', '가', '를'}
{'▁미국의', '▁사건', '▁선', '게', '이', '받', '▁있', '한', '▁후', '나요', '▁되었', '▁완전', '▁계', '▁인정', '을', '기로', '은', '▁독립', '언', '?', '▁어떤'}
{'▁누구', '인가', '자는', '▁초대', '?', '▁소', '▁지도', '련', '의'}
{'▁', '▁최초', '목', '▁있었', '나', '은', '이', '?', '올림픽', '▁종', '▁몇', '의'}
{'인', '옥', '▁', '드', '스', '▁대학', '▁누구', '립', '주는', '?', '▁창', '퍼', '가요', '의'}
{'▁우주', '키스', '▁', '탄', 'gdp', '베', '인가', '는', '?', 'GDP', '▁얼마', '의'}
{'투', '▁무엇인가', '▁전', '는', '▁가장', '?', '상', '▁역사', '▁큰', '▁규모', '가'}
{'▁사', '▁위치한', '▁무엇인가', '에서', '은', '▁가장', '▁한국', '?', '▁높은', '▁곳에', '찰'}
{'은', '▁제일', '?', '▁무엇인가', '▁강', '▁큰', '에서', '요', '▁영국'}
{'자는', '▁받은', '▁', '상을', '로', '▁최초', '물', '▁생', '▁누구', '인가', '?', '학', '▁노', '벨'}
{'▁', '▁무엇인가', '에서', '기는', '▁오래', '▁가장', '▁한국', '?', '옹', '된'}
{'▁호', '▁무', '▁문', '했', '는', '지에', '?', '란', '구', '▁처음으로', '▁말', '의', '가', '소', '▁누가'}
{'교', '되었', '▁시작', '에서', '▁어느', '▁청', '도는', '는', '?', '▁나라', '가'}
{'로', '파', '▁무엇인가', '리', '▁최초', '▁전', '주의', '▁사람은', '?', '▁공', '한', '를'}
{'▁', '▁최초', '목', '▁있었', '나', '은', '이', '?', '올림픽', '▁종', '▁몇', '의'}
{'▁', '▁무엇인가', '에서', '드', '는', '▁가장', '▁도시', '?', '란', '▁큰', '폴'}
{'▁언제', '당', '을', '했', '은', '▁독일', '?', '▁창', '▁국민', '민주', '나요'}
{'▁개', '▁한국의', '조', '▁양', '공', '장은', '?', '▁있는', '▁몇', '가'}
{'라는', '▁', '하였', '▁언제', '망', '▁청', '나', '는', '?', '멸', '가'}
{'인', '▁', '▁언제', '닉', '▁사망', '은', '?', '슨', '가요', '의', '일'}
{'인', '▁연', '▁', '로', '야구', '▁언제', '한', '▁첫', '▁스포츠', '도는', '현', '?', '에', '올림픽', '▁출', '가요', '가'}
{'▁', '에는', '▁살고', '▁2019', '년', '명의', '이', '?', '▁대한민국', '▁조선', '▁있는', '▁몇', '가', '족'}
{'▁', '▁베이', '야구', '징', '▁국가', '▁어느', '했', '는', '▁우승', '?', '올림픽', '가'}
{'▁무엇인가', '에서', '체', '통', '▁우', '은', '▁가장', '▁한국', '?', '▁큰'}
{'▁개', '법인', '마', '는', '국', '인가', '?', '▁합', '▁나라', '▁몇', '▁대', '초', '가'}
{'▁가장', '?', '▁무엇인가', '▁미국', '에서', '씨는', '▁많은', '▁성'}
{'해', '▁어느', '▁위치', '은', '있는', '?', '에', '▁주', '관', '악', '▁백', '가'}
{'▁에너지', '열', '▁먼저', '▁누구', '▁태양', '인가', '▁가장', '▁사람은', '?', '한', '▁개발', '를'}
{'적인', '▁민', '들이', '▁무엇인가', '▁내용', '요', '▁기록', '▁이스라엘', '?', '▁역사', '서는', '▁있는', '되어', '족', '의'}
{'부터', '되었', '▁언제', '▁시작', '▁북한', '권', '은', '?', '▁김정', '▁정', '의', '나요'}
{'신', '에서', '▁많은', '▁문', '▁세상', '▁누구', '인가', '이', '▁가장', '▁사람은', '?'}
{'▁최', '되었', '▁시작', '에서', '▁어느', '▁최초', '금', '▁제도', '는', '임', '?', '저', '▁나라', '의', '나요'}
{'인', '집', '▁언제', '▁시기', '한', '에서', '는', '?', '물이', '▁마', '▁이', '▁발달', '가요', '트', '직'}
{'딘', '바', '▁어', '니아', '국', '는', '▁알', '▁수도', '?', '▁공', '화', '가요'}
{'황', '▁천', '▁오랜', '기간', '▁있던', '▁누구', '인가', '▁자리', '은', '▁가장', '?', '상', '▁역사', '에', '▁인물', '의'}
{'▁누구', '인', '▁인도', '은', '▁대통령', '?', '▁첫번째', '가요', '의'}
{'▁사용', '▁2019', '년', ',', '▁소셜', '▁미디어', '▁무엇인가', '월', '는', '되고', '▁가장', '있는', '?', '▁기준', '▁5', '▁많이'}
{'인', '연합', '▁어디', '한', '▁최근', '▁가입', '는', '▁가장', '?', '에', '▁나라', '가요', '▁유럽'}
{'▁', '▁어디', '▁처음', '닥', '▁방', '인가', '는', '터', '?', '영', '된', '년도', '가', '▁후'}
{'▁베이', '다', '▁캐', '▁프로', '▁미국', '메이', '볼', '를', '하나', '▁', '야구', '리그', '에서', '과', '요', '스', '나', '▁수준', '은', '?', '저', '▁말', '▁최고', '의'}
{'▁누구', '은', '▁대통령', '▁현재', '낙', '?', '요', '▁러시아'}
{'은', '▁긴', '▁가장', '▁해', '?', '변', '에서', '▁중국'}
{'인', '생', '▁', '▁언제', '닉', '은', '?', '슨', '▁출', '가요', '의', '일'}
{'▁개', '▁', '▁하는', '을', '인가', '는', '국', '?', '▁주식', '으로', '▁몇', '▁나라', '쌀'}
{'인', '틱', '▁만든', '▁누구', '▁휴', '▁사람은', '▁발견', '?', '리스', '법을', '가요'}
{'▁', '년', '▁무엇인가', '에서', '기는', '▁세상', '▁2018', '▁현', '항공', '▁오래', '▁가장', '?', '된', '직'}
{'▁에', '▁시청', '드는', '피', '▁기록', '했던', '터', '▁시리즈', '▁후', '▁', '▁무엇인가', '닥', '을', '▁중에서', '▁가장', '?', '▁높은', '률', '소', '의'}
{'하였', '성', '명', '는', '?', '▁장치', '▁발', '▁관', '▁측정', '가', '▁누가'}
{'자는', '징', '▁선', '인가', '고', '받', '범죄', '▁역사', '▁미국', '연', '▁최', '▁', '▁무', '을', '▁누구', '은', '?', '상', '역', '기', '소'}
{'은', '▁가장', '?', '▁무엇인가', '▁강', '▁큰', '에서', '▁중국'}
{'향', '▁', '▁어디', '▁고', '틴', '푸', '인가', '은', '?', '의'}
{'황', '▁곳', '▁어디', '▁지', '이', '은', '인가', '?', '내는', '▁교'}
{'대', '▁', '예', '▁언제', '브라', '인가', '이', '는', '수', '?', '상', '질', '진', '▁거', '년도', '▁만들어', '의'}
{'▁이탈리아', '은', '▁가장', '?', '▁무엇인가', '▁큰', '당', '에서', '▁성'}
{'은', '체인', '?', '▁언제', '나요', '▁기술', '졌', '▁만들어', '▁블록'}
{'▁서', '▁어디', '어', '식', '▁러시아', '인가', '은', '디', '?', '지역', '늑', '숲', '대의'}
{'▁', '로', '▁인구', '에서', '는', '?', '많', '▁세계', '불교', '번째', '▁발생', '▁몇', '▁나라', '한', '가', '의', '나요'}
{'는', '▁가장', '?', '▁무엇인가', '▁큰', '에서', '▁나라', '▁세상'}
{'▁언제', '어', '▁일', '은', '는', '났', '?', '차', '▁산업혁명', '▁1', '가'}
{'▁인구', '르', '▁수', '메', '는', '인가', '?', '에', '▁있는', '▁얼마'}
{'▁누구', '인', '립', '주는', '?', '▁인', '텔', '▁창', '가요'}
{'는', '▁오래', '▁가장', '?', '상', '▁역사', '▁무엇인가', '▁종교', '된'}
{'인', '체인', '을', '▁만든', '▁블록', '▁누구', '▁사람은', '?', '▁기술', '가요'}
{'대', '▁국', '년', '▁서울', '▁무엇인가', '과', '형', '▁2018', '은', '?', '악', '전', '▁입', '시'}
{'▁어디', '운', '에서', '인가', '▁호주', '는', '▁가장', '▁도시', '?', '▁더'}
{'▁언제', '당', '했', '은', '▁독일', '?', '▁창', '▁사회', '민주', '나요'}
{'▁누구', '인가', '자는', '▁미국의', '?', '▁2019', '년', '▁지도'}
{'향', '델', '스티', '▁에', '▁', '븐', '▁어디', '▁고', '인가', '은', '?', '스턴', '의'}
{'▁복', '▁어디', '석', '에서', '룡', '▁화', '▁세상', '은', '▁가장', '?', '에', '원', '▁큰', '▁공', '▁있는', '본', '가'}
{'결', '▁어디', '성', '▁동', '▁많은', '혼', '인가', '이', '는', '▁가장', '?', '▁나라'}
{'는', '▁', '▁알', '낳', '류', '?', '유', '▁포', '을'}
{'▁기', '단', '교', '▁무엇인가', '갑', '과', '요', '도', '는', '?', '▁병', '사'}
{'▁', '해', '▁있나요', '▁속', '스코', '는', '?', '샌', '란', '▁주', '에', '▁어떤', '프', '시'}
{'▁한국의', '▁시간', '▁2019', '년', ',', '월', '인가', '은', '?', '▁기준', '제', '▁몇', '▁5', '한', '▁노동'}
{'▁되었', '▁', '▁언제', '▁처음', '텐', '도는', '▁출시', '닌', '는', '?', '가'}
{'인', '집', '▁어디', '는', '▁도시', '?', '▁최대', '▁이', '가요', '트', '의'}
{'▁해', '하였', '▁언제', '체', '은', '는', '?', '▁소', '가', '련'}
{'▁', '▁어디', '야구', '▁시작', '▁먼저', '인가', '는', '▁가장', '?', '▁나라', '한', '를'}
{'▁', '명', '을', '했', '는', '?', '음악', '▁발', '락', '가', '▁누가'}
{'▁', '▁어디', '석', '트리', '박물관', '라', '▁화', '인가', '스의', '이', '케', '은', '있는', '?', '▁전시', '되어', '톱'}
{'리아', '▁무엇인가', '에서', '은', '▁오', '▁가장', '?', '▁산', '▁높은', '스트'}
{'로', '브라', '랍', '어', '▁어떻게', '함', '은', '?', '▁쓰', '▁아', '나요'}
{'▁어디', '▁주는', '▁인구', '에서', '▁중국', '인가', '도가', '▁가장', '?', '▁높은', '밀'}
{'▁누구', '인가', '주는', '?', '▁마이크로', '▁창업', '소프트', '의'}
{'▁인천', '전', '▁언제', '▁펼쳐', '나', '은', '륙', '?', '작', '졌', '▁상'}
{'d', '▁언제', 'ec', 'EC', '▁프랑스', '▁O', '했', '▁가입', '▁o', '는', '?', '에', 'D', '나요'}
{'인', '▁어디', '하이', '지는', '▁중국', '▁청', '▁상', '재', '?', '가요', '사', '소', '의'}
{'▁뭐', '대', '▁', '▁고', '리', '었', '▁불', '리는', '헝', '라고', '?', '에', '가', '나요'}
{'▁어디', '▁판매', '▁많은', '▁게임', '을', '인가', '▁가장', '?', '사는', '한'}
{'▁되었', '▁언제', '▁서울', '은', '는', '▁수도', '?', '▁대한민국', '가', '의'}
{'대', '▁왕', '인', '만', '스', '▁누구', '국', '▁오', '은', '?', '▁제', '▁1', '가요', '의'}
{'▁무엇인가', '▁생명', '▁많은', '을', '▁치료', '▁구', '는', '▁가장', '?', '상', '▁역사', '제', '한'}
{'▁에', '▁시청', '피', '드', '▁기록', '터', '▁시리즈', '한', '▁후', '▁', '▁중', '▁무엇인가', '닥', '을', '▁가장', '?', '▁높은', '률', '소'}
{'▁스페인', '은', '▁가장', '?', '▁무엇인가', '▁산', '에서', '▁높은'}
{'▁누구', '인가', '은', '▁대통령', '▁미국의', '?', '▁초대'}
{'▁', '▁어디', '에서', '▁세상', '인가', '은', '▁가장', '?', '미술', '▁큰', '관'}
{'자는', '투', '망', '▁사망', '명', '르', '▁전', '는', '디', '▁당시', '이었', '?', '▁노', '▁몇', '가'}
{'▁일본', '수는', '년', '▁무엇인가', '에서', '▁판매', '▁2018', '▁가장', '?', '료', '된', '▁음', '▁많이'}
{'자는', '▁2019', '년', '리', '▁필', '▁누구', '핀', '인가', '?', '▁지도', '의'}
{'▁브', '▁언제', '▁첫번째', '브리', '을', '라이', '했', '은', '▁피', '언', '터', '?', '▁가', '▁음', '▁발표', '엘', '반', '나요'}
{'▁국', '채', '유', '▁중국', '하고', '은', '▁현재', '?', '▁얼마', '▁미국', '▁있는', '▁보', '가', '를'}
{'▁', '백화점', '▁2019', '년', '▁무엇인가', '에서', '▁세상', '은', '▁가장', '?', '▁큰'}
{'▁', '되었', '▁첫번째', '에서', '건설', '도는', '▁어디서', '▁철', '?', '▁세계', '나요'}
{'▁2019', '년', '자가', '▁많은', '▁된', '▁누구', '인가', '▁가장', '▁나이', '▁사람은', '?', '상', '▁역사', '에', '▁지도', '까지', '▁나라', '의'}
{'▁작', '보드', '가는', '위를', '▁누구', '인가', '▁오래', '▁가장', '?', '▁1', '한', '곡', '▁빌'}
{'인', '▁', '▁어디', '브라', '라', '나', '는', '▁주의', '▁도시', '?', '질', '▁최대', '가요', '▁파'}
{'연', '황', '▁최', '▁', '로', '▁2019', '년', '▁된', '▁누구', '인가', '이', '▁사람은', '?', '상', '▁역사', '까지', '▁교', '소'}
{'자는', '얀', '▁2019', '년', '▁누구', '마', '인가', '?', '▁지도', '▁미', '의'}
{'▁', '로', '위', '▁무엇인가', '성', '궤', '▁최초', '공', '도', '른', '은', '▁오', '?', '▁인', '상', '▁역사', '에'}
{'인', '대학교', '▁', '▁어디', '럴', '한', '드', '웰', '스', '▁졸업', '▁헤', '이', '는', '▁라', '?', '가요'}
{'은', '▁냉', '는', '났', '?', '▁언제', '▁끝', '전', '가'}
{'▁호', '▁', '에는', '?', '개의', '▁있나요', '▁몇', '수가', '▁영국'}
{'▁', '연구소', '▁무엇인가', '에서', '는', '▁오래', '▁가장', '▁한국', '?', '된'}
{'▁일본', '▁', '▁어디', '야구', '팀', '에서', '인가', '은', '▁오래', '▁가장', '?', '된'}
{'▁기', '하나', '급', '생', '▁어디', '▁속', '에서', '요', '은', '▁한국', '?', '상', '에', '▁사회', '계'}
{'▁', '연구소', '▁무엇인가', '에서', '는', '▁오래', '▁가장', '▁한국', '?', '된'}
{'▁국가', '▁무엇인가', '▁프랑스', '공', '요', '국', '는', '?', '화', '▁제', '▁1', '의'}
{'▁동안', '▁통', '▁프랑스', '▁식', '했', '는', '치', '이나', '지', '민', '?', '▁얼마', '친', '차', '▁코', '를', '나요'}
{'위', '▁무엇인가', '에서', '스', '은', '▁가장', '?', '▁산', '▁높은', '▁스'}
{'큰', '▁발전', '부터', '▁미국의', '로', '▁언제', '▁로', '르', '▁대중', '했', '은', '?', '음악', '▁장', '롤', '나요'}
{'라는', '▁', '하였', '▁언제', '▁당', '망', '나', '는', '?', '멸', '가'}
{',', '▁2019', '년', '▁무엇인가', '에서', '▁분', '▁많은', '점이', '▁기업', '은', '▁가장', '?', '시아', '▁말', '▁기준', '레이'}
{'라는', '▁', '▁언제', '▁당', '망', '나', '했', '는', '?', '멸', '가'}
{'공항', '은', '▁가장', '?', '▁국제', '▁무엇인가', '▁큰', '에서', '▁아시아'}
{'로', '▁번째', '▁국가', '에서', '▁러시아', '인가', '는', '?', '▁큰', '▁세계', '▁몇'}
{'니', '는', '▁', '지', '국어', '?', '▁무엇인가', '튀', '의'}
{'법원', '▁연', '▁건물', '▁어디', '▁있나요', '은', '?', '에', '▁미국', '방', '▁대'}
{'▁', '▁처음', '위', '성', '▁무엇인가', '공', '▁인류', '쏘', '은', '아', '올', '?', '▁인', '가', '린'}
{'▁추', '▁어디', '운', '에서', '▁러시아', '인가', '는', '▁가장', '▁도시', '?'}
{'마', '는', '▁루', '인가', '?', '▁크기', '▁얼마', '니아', '의'}
{'▁', '▁무엇인가', '드', '요', '어', '핀', '는', '용', '?', '란', '▁공', '의'}
{'인가', '▁페이지', '?', '▁총', '중', '▁몇', '기는', '▁난', '일'}
{'인', '▁돈', '당', '▁금', '▁imf', '▁모', '인가', '은', '▁IMF', '?', '모', '에', '▁운동', '으', '▁몇', '기', '시'}
{'인', '마크', '▁', '▁무엇인가', '요', '니', '▁루', '웨', '는', '?', '의', '번호', '▁등'}
{'자', '▁', '젠', '▁중국', '▁사망', '▁철학', '이', '은', '언', '?', '▁정', '가요', '일'}
{'해', '얀', '▁속', '▁어느', '마', '는', '륙', '있는', '?', '에', '▁미', '▁대', '가'}
{'▁승', '로', '였', '▁15', '원은', '명이', '?', '폴', '호', '▁몇', '무', '▁아', '나요'}
{'되었', '▁언제', '▁시작', '텍', '명', '즈', '▁문', '은', '는', '?', '▁아', '가'}
{'는', '▁교회', '▁세', '?', '웠', '▁초대', '▁누가', '나요'}
{'▁기', '인', '▁', '▁세', '어', '탑', '▁누구', '듀', '▁프로', '?', '서는', '번째', '가요'}
{'인', '▁국가', '▁북', '딕', '르', '는', '?', '개', '▁노', '▁몇', '유럽', '가요', '의'}
{'▁어디', '년', '▁반도체', '▁많은', '▁2018', '인가', '는', '▁가장', '?', '▁수입', '▁나라', '한', '를'}
{'▁되', '▁', '▁기간', '위', '리', '헨', '▁재', '▁8', '은', '?', '세', '▁얼마나', '의', '나요'}
{'로', '하였', '▁언제', '▁브루', '▁사망', '실', '는', '?', '프', '가'}
{'▁사', '자', '블', '▁', '▁무엇인가', '리', '에서', '드', '▁게임', '▁먼저', '▁출시', '은', '▁가장', '?', '한'}
{'▁노트북', '▁어디', '요', '▁만든', '을', '이', '낙', '?', '▁처음으로', '▁회사는'}
{'▁한국의', '▁시간', '시간', '인가', '은', '?', '▁최대', '▁법적', '▁몇', '▁근무'}
{'인', '▁', '텐', '▁첫', '금', '도', '닌', '은', '▁설립', '▁회사', '?', '가요', '▁얼마', '▁자본', '의'}
{'▁끝나', '은', '?', '▁언제', '혁명', '▁프랑스', '▁대', '나요'}
{'▁', '에서', '▁어느', '었', '틀', '는', '?', '▁죽', '러', '히', '▁나라', '가'}
{'은', '▁석', '▁가장', '▁한국', '?', '▁무엇인가', '성', '▁큰', '에서'}
{'▁작', '▁', '슬', '▁2019', '년', '▁몇', '스', '을', '비', '했', '리는', '는', '?', '프레', '까지', '곡', '엘', '가'}
{'하였', '▁언제', '▁사망', '르', '는', '크', '스는', '?', '▁마', '가'}
{'▁우주', '범', '▁', '▁포함', '뱅', '빅', '이', '은', '?', '주', '에', '되는', '가', '의', '론'}
{'▁', '폰', '▁스', '밥', '▁누구', '인가', '케', '지', '터', '▁사람은', '?', '한', '릭', '▁디자인', '를'}
{'▁기', '교', '되었', '▁시작', '에서', '▁어느', '독', '는', '?', '▁나라', '가'}
{'▁', '되었', '▁시작', '▁비', '는', '?', '에', '트', '▁몇', '년도', '가', '인은', '코'}
{'왕', '▁왕', '▁프', '▁누구', '인가', '국', '은', '크', '?', '랑', '▁초대', '의'}

In [28]:
# val
validation_features, validation_labels, validation_lengths = featurize(df_val)

{'▁రాష్ట్రంలో', '▁ఒ', 'న్', 'ద్ద', '▁అతి', 'రె', '▁నగర', '▁?', 'గా', 'పె', 'ం', 'ని', '▁ఏది'}
{'ను', 'ొ', 'న్నారు', '▁కల', 'గ', '▁ఏ', 'రా', '▁దేశంలో', '▁?', '▁మొదట', 'గా', '▁వ్యాధి', 'ని', '▁క'}
{'ను', 'ొ', 'న్నారు', '▁కల', 'గ', '▁ఏ', 'రా', '▁దేశంలో', '▁?', '▁మొదట', 'గా', '▁వ్యాధి', 'ని', '▁క'}
{'ల', '▁?', '▁మొదటి', '▁ప్రపంచ', '▁యుద్ధం', '▁ఎప్పుడు', 'యింది', '▁మొద'}
{'ల', '▁?', '▁మొదటి', '▁ప్రపంచ', '▁యుద్ధం', '▁ఎప్పుడు', 'యింది', '▁మొద'}
{'ద', '▁ఆ', 'మో', '▁ఏ', '-2005', '▁చట్టం', 'ించింది', '?', '▁సమాచార', '▁ను', '▁ప్రభుత్వం'}
{'▁', 'లు', '▁ఎన్ని', 'లో', '▁భారత', '▁ఉండే', 'న', '▁ప్రా', 'క', '?', '▁భాష', 'చీ', 'వాడు', 'దేశం', 'వి'}
{'గ', '▁స', 'న', 'టు', '▁రక్త', '▁ఉండ', '?', 'ాల్సిన', 'ం', '▁మనిషి', 'ని', '▁ఎంత'}
{'తం', 'మి', '▁', '▁రాష్ట్రంలో', 'స్', 'ద్ద', '▁అతి', '▁?', 'స', '▁నిర్', 'పె', '▁మానవ', 'ని', '▁ఏది', 'టెక్'}
{'▁వ', 'లో', '▁హక్కు', '▁భారత', 'నీ', 'డానికి', 'టు', '▁ఉండ', 'స', '?', 'య', 'వలసిన', 'స్సు', '▁ఎంత', 'దేశం', '▁క', '▁ఓ', '▁పొంద'}
{'ను', 'ొ', 'న్నారు', 'లో', '▁సంవత్సరం', 'జన్', 'గ', '▁ఏ', 'లి', '?', '▁ను', '▁క', 'వి', '▁టె'}
{'▁', 'వరి', '▁ఎక్కువగా', 'లో', '▁భారత', '?', '▁ప', '▁రాష్ట్రం', '▁ఏది', 'దేశం', 'ండే'}
{'▁మాట్లాడ', 'తారు', 'లు', '▁ఎన్ని', 'లో', '▁భారత', 'గ', '▁స', 'టు', '?', 'గా', '▁భాష', 'దేశం'}
{'▁సి', '▁లో', 'న్', 'టి', '్', '▁చర్చ', 'క', '▁పేరు', 'ిన', 'గా', '?', '▁ఏది', 'ంచ', '▁వాటి'}
{'▁ఈ', '▁ఏంటి', 'డ్', 'ొ', '▁డ', 'ప్', '▁ఇంటర్నెట్', '▁కో', 'మైన', '్', '▁దేశ', 'టు', '?', 'జి', 'పు'}
{'▁కా', '▁రాష్ట్రంలో', 'లో', 'ణం', '▁అతి', '▁పర', 'లి', '▁ఏది', 'యా', '▁పెద్ద', 'ీర్', 'ంగా', 'ఫో', 'స్త', 'ర్', '▁వి', '▁నగర', '?', 'ం', 'ని'}
{'కి', '▁', 'లో', '▁భారత', '▁ఎక్కువ', '▁ఉండే', 'వులు', 'నాటి', 'స్త', 'రై', '?', 'ం', '▁ఏది', 'దేశం', '▁2010', '▁క్', '▁ప్రాంత'}
{'▁ఖ', '▁ఉంది', 'గా', '?', '▁ఉ', 'ండా', 'ం', 'డంలో', '▁ఏ'}
{'▁ఎవరు', 'లో', 'న్', '▁అర', '▁ఏ', 'ారు', 'రా', '▁ఖ', 'ు', '?', '▁భాష', 'బ్బ', 'ీ', '▁రాస'}
{'▁అంటారు', '?', 'ం', 'ంలో', '▁ని', 'ని', '▁జల', '▁ఏమ', '▁ఆంగ్ల'}
{'లో', 'స్థా', '▁భారత', 'ష', 'దేశం', '▁క్', 'బడింది', '▁', 'స్త', 'న', 'రై', 'పించ', '▁?', '▁మొదట', 'రీ', 'గా', 'వ', '▁ఎక్కడ', '▁మి'}
{'ాలలో', 'న్న', 'తార', 'వు', '▁కృష్ణ', '▁', '▁అవ', '▁పు', 'ుడి', 'ది', 'రా', '▁ప్రకారం', 'ాల', '▁ఎ', 'విష్ణు', '?', 'ం', 'ణ', 'వ'}
{'▁త', 'ష్', '▁మనిషి', 'గ్ర', 'ో', '▁ఒక', 'గ', '▁స', 'గల', 'కో', 'టు', 'త', 'గా', 'డు', '▁ఉ', '?', 'ట్టు', 'ని', '▁ఎంత', 'ణ'}
{'న్నది', '▁క్యాన్సర్', '▁ఎవరు', 'ను', 'ొ', '?', '▁ని', 'గ', '▁క'}
{'▁', '▁నడి', '▁నుండి', '▁ఏ', 'న', '▁ప్రా', '▁వరకు', 'గ్', 'రీ', '?', 'చీ', 'కు', 'ింది', 'చ', '▁కాలం'}
{'లు', '▁రాష్ట్రంలో', 'లో', '▁భారత', 'మైంది', '▁ఏ', 'రై', '▁మొదట', '▁ప్రారంభ', 'గా', '▁మె', '?', 'ట్రో', 'దేశం'}
{'▁సమయం', '▁అవ', '▁ఎక్కువ', '▁ఏ', '▁పని', 'చే', 'వం', 'క', '?', 'య', '▁మనిషి', '▁చనిపో', 'యా', 'స్తుంది'}
{'క్', '▁ఎవరు', 'ధా', 'జన్', 'నాయక', 'ుడు', '▁ఆ', '?', 'సి', '▁చిత్ర', '▁క'}
{'క్', '▁ఎవరు', 'ధా', 'జన్', 'నాయక', 'ుడు', '▁ఆ', '?', 'సి', '▁చిత్ర', '▁క'}
{'బి', 'లు', 'ద', '▁ఎన్ని', 'లలో', '▁బై', '▁అను', '▁2018', '▁వరకు', 'ించారు', '?', '▁భాష', '▁ను', 'వ'}
{'ంటారు', '?', 'తిని', 'ంలో', '▁నీ', '▁ఏమ', '▁ఆంగ్ల'}
{'▁ప్ర', 'లు', 'హి', '▁ఎన్ని', '▁అమెరికాలో', '▁న', '?', 'స్తున్నాయి', 'వ', 'దు'}
{'దేశ', '?', 'చీ', '▁రాజధాని', '▁భారత', '▁ఏది', 'న', '▁ప్రా', 'ానికి'}
{'కి', '▁?', '▁మానవ', '▁ఎన్ని', '▁అవసరం', '▁సాధారణ', '▁గంటల', 'ుని', '▁నిద్ర'}
{'కి', '▁?', '▁మానవ', '▁ఎన్ని', '▁అవసరం', '▁సాధారణ', '▁గంటల', 'ుని', '▁నిద్ర'}
{'▁రష్యా', 'కి', '▁ఎవరు', '▁', 'నాటి', '▁దేశ', '▁ప్రధాన', '▁2011', '▁మంత్రి', '?'}
{'గ', '▁స', 'ారు', 'మంది', 'టు', '?', 'ద్ధ', 'గా', '▁ప్రపంచ', 'య', 'ంలో', '▁చనిపో', '▁రెండవ', '▁ఎంత', 'యు'}
{'మి', '▁వ్యక్తి', '▁పే', 'రే', 'టి', 'ిన', '?', 'జీ', '▁చంప', 'ని', '▁గాంధీ'}
{'మి', '▁వ్యక్తి', '▁పే', 'రే', 'టి', 'ిన', '?', 'జీ', '▁చంప', 'ని', '▁గాంధీ'}
{'▁మరణించ', 'లో', 'గ', '▁స', 'ష్', 'ారు', 'మంది', 'టి', 'ి', '▁బ్ర', 'న', 'టు', '?', '▁ఎంత', 'ులు', '▁పాలన', '▁భారతీయ'}
{'▁', 'లు', '▁మొత్తం', '▁ఎన్ని', 'లో', '▁భారత', 'రు', '▁రకాల', '?', 'దొ', 'కు', 'తాయి', 'దేశం', '▁పూ'}
{'▁ఎక్కువగా', '▁ఉండే', '్యా', '▁పర', '▁?', 'వు', '▁వా', 'రణ', 'ంలో', '▁ఏది', 'వ', 'యు'}
{'కా', 'ళం', '▁రక్షణ', '▁ఏ', '▁శక్తి', '▁దేశ', '▁ఉంది', '?', '▁అత్యంత', 'వంతమైన', '▁ద', '▁నా', 'వి', 'ానికి'}
{'కా', 'ళం', '▁రక్షణ', '▁ఏ', '▁శక్తి', '▁దేశ', '▁ఉంది', '?', '▁అత్యంత', 'వంతమైన', '▁ద', '▁నా', 'వి', 'ానికి'}
{'▁మధ్య', '▁ఏ', 'ఏ', '▁మొదటి', '▁మొదట', '?', 'గా', '▁ప్రపంచ', '▁మొదలు', '▁అయ్యింది', '▁దేశాల', '▁యుద్ధం'}
{'▁మధ్య', '▁ఏ', 'ఏ', '▁మొదటి', '▁మొదట', '?', 'గా', '▁ప్రపంచ', '▁మొదలు', '▁అయ్యింది', '▁దేశాల', '▁యుద్ధం'}
{'ను', 'లు', '▁2019', 'ద', '▁ఎన్ని', 'లలో', '▁బై', '▁అను', 'బు', '▁వరకు', 'ించారు', '?', '▁భాష', 'వ'}
{'ాం', '▁జ', '▁గుంటూరు', 'కాల', '▁పట్టణ', '▁భారత', 'గ', 'భా', '▁జన', 'న', '▁ప్రకారం', '▁?', '▁2011', 'నా', '▁గణ', '▁ఎంత', 'ణ'}
{'రి', '▁నీరు', 'ో', '▁కావాలి', '▁ఆ', 'ష్', 'డానికి', 'త', 'గా', '?', '▁ఉ', '▁మార', '▁ఎంత', 'ణ', 'వి', 'గ్ర'}
{'▁ఎవరు', 'ను', 'ొ', 'న్నారు', 'జన్', 'గ', 'లి', '?', '▁ను', '▁క', 'వి', '▁టె'}
{'▁నవల', '▁అండ్', '▁', 'ను', '▁ఎప్పుడు', 'స్', 'ారు', '▁పీ', '?', '▁ప్రచురించ', 'వార్'}
{'▁నవల', '▁అండ్', '▁', 'ను', '▁ఎప్పుడు', 'స్', 'ారు', '▁పీ', '?', '▁ప్రచురించ', 'వార్'}
{'▁దేశ', '?', 'డా', '▁రాజధాని', '▁ఏది', '▁కె', 'న'}
{'▁విద్యుత్', 'ర', '▁ఏ', '▁ప్రవేశపెట్ట', 'ారు', '▁దేశంలో', '▁మొదట', '?', '▁ను', '▁సౌ', 'శక్తి'}
{'▁విద్యుత్', 'ర', '▁ఏ', '▁ప్రవేశపెట్ట', 'ారు', '▁దేశంలో', '▁మొదట', '?', '▁ను', '▁సౌ', 'శక్తి'}
{'▁త', 'ో', 'ుడు', 'గల', 'కో', 'ష్', '▁?', 'త', 'డు', '▁ఉ', '▁మానవ', 'ట్టు', 'ని', '▁ఎంత', '▁తక్కువ', 'ణ', 'గ్ర'}
{'▁దేశ', '▁ఏంటి', 'కా', '?', '▁రాజధాని', 'ండ్', 'ట్', '▁స్', '▁లే'}
{'త్', '▁అధికార', 'ిక', '▁కొ', '▁దేశ', '?', '▁భాష', 'రియా', '▁సౌ', '▁ఏది'}
{'క్', '▁', 'గి', '▁ఏ', 'టా', '▁టై', '▁న', 'ౌ', 'క', '?', '▁ము', 'ంలో', 'ని', '▁సముద్ర', 'పోయింది'}
{'ంబ', 'ణ', '▁ఎవరు', 'ను', 'ొ', 'న్నారు', 'గ', '▁బా', 'ు', '?', '▁క', 'ుని', '▁అ'}
{'▁ఏంటి', '▁పై', '▁చంద్ర', '▁సంస్థ', 'ుడు', '▁మొదటి', '▁పేరు', '?', 'గా', '▁పరిశోధన', '▁చేసిన'}
{'▁ఏంటి', '▁పై', '▁చంద్ర', '▁సంస్థ', 'ుడు', '▁మొదటి', '▁పేరు', '?', 'గా', '▁పరిశోధన', '▁చేసిన'}
{'క్', 'మి', '▁పట్ట', 'స్ట్', '▁ఎవరు', '▁ఆర్', '▁లో', 'ుడు', '▁కె', '▁మొదటి', 'రీ', 'ిన', 'గా', '?', 'ని', 'ా', '▁భారతీయ', '▁పొంద'}
{'టూ', '▁పరిచయం', '▁డిస్', '▁కార్', 'నీ', 'న్', '▁మొదటి', '?', '▁చేసిన', '▁ఏది'}
{'▁ఏంటి', 'లా', '▁మ', '?', '▁భాష', '▁లో', '▁అధికార', 'ిక', 'నీ'}
{'ంబ', '▁', 'ము', 'గ్రహ', '▁అతి', 'న్న', 'ర', 'టు', '▁?', 'చి', 'కు', '▁సౌ', 'ంలో', '▁ఏది'}
{'ంబ', '▁', 'ము', 'గ్రహ', '▁అతి', 'న్న', 'ర', 'టు', '▁?', 'చి', 'కు', '▁సౌ', 'ంలో', '▁ఏది'}
{'▁ఈ', 'స్ట్', '▁ఇండియా', 'లోకి', '▁భారత', '▁ఎప్పుడు', '▁కంపెనీ', '▁వచ్చింది', '?', 'దేశం'}
{'?', 'ఫ్', '▁లీ', '▁ఎన్ని', 'లో', '▁సంవత్సరం', '▁ఉంటాయి', '▁రోజులు', '▁ఒక్క'}
{'▁ప్ర', '▁స్థానంలో', '▁', '▁2017', '▁లో', 'వ్', 'లో', 'థ', '▁ఆ', '▁ఉన్న', 'లి', '?', '▁ఉత్పత్తి', 'మ', 'దేశం', '▁ఏది', '▁నూనె'}
{'▁ప్ర', '▁స్థానంలో', '▁', '▁2017', '▁లో', 'వ్', 'లో', 'థ', '▁ఆ', '▁ఉన్న', 'లి', '?', '▁ఉత్పత్తి', 'మ', 'దేశం', '▁ఏది', '▁నూనె'}
{'▁మధ్య', '▁జరుగుతుంది', '▁కా', 'శ్', '▁ఏ', 'ర్', 'మీ', '▁పోరాటం', '▁విషయంలో', '?', '▁దేశాల'}
{'▁వాడ', '▁నిత్య', 'లో', 'ుడు', 'రా', '▁ప్రపంచంలో', 'లకు', 'స', '▁శాతం', '?', '▁మానవ', '▁నీటి', 'ే', '▁ఎంత', '▁70%', 'వ'}
{'క్త', '▁సం', '▁ఎన్ని', 'లో', '▁ఉన్నాయి', '▁దేశ', '▁రాష్ట్రాల', '?', 'ాలు', '▁అమెరికా', 'యు'}
{'ము', '▁', 'ీర్', 'ంగా', 'ద్ద', '▁అతి', 'స్త', '▁వి', '▁పర', '▁?', '▁ప్రపంచంలో', 'పె', '▁ఏది', 'దేశం', 'ణ'}
{'▁వ', 'లో', '▁చేయడానికి', '▁భారత', 'నీ', '▁కావ', '▁రాష్ట్ర', '▁పోటీ', 'స', 'గా', 'ాల్సిన', 'య', '?', 'పతి', 'స్సు', '▁ఎంత', 'దేశం', '▁క'}
{'▁2017', '▁లో', '▁ఎక్కువగా', '▁చేస్తున్న', 'లో', '▁భారత', '?', '▁ప', '▁ఉత్పత్తి', '▁రాష్ట్రం', 'ని', 'త్తి', '▁ఏది', 'దేశం'}
{'లాండ్', '▁', 'ంగ్', '▁ఏ', '▁ఖ', '▁ఇ', '▁ఉంది', '?', 'ం', 'డంలో', 'దేశం'}
{'తం', 'మి', '▁మ', 'హే', '▁ఏ', '▁పుట్ట', '▁దేశంలో', '▁మొదట', '?', 'ింది', 'యన్', '▁బో'}
{'▁', 'పాల్', '▁నే', '▁పు', '▁హిందూ', '▁దేవాలయ', '▁ఉన్న', 'తన', 'రా', '▁ఉంది', '?', 'ం', '▁అత్యంత', 'దేశం', '▁ఎక్కడ'}
{'▁దగ్గర', '▁ఏ', '▁ఉంది', 'గా', '?', 'రాష్ట్ర', '▁రాష్ట్రం', '▁సముద్ర', '▁మహా', 'ానికి'}
{'రి', '▁నీరు', 'ో', '▁ఆ', 'ష్', 'ుతుంది', 'త', 'గా', '▁వద్ద', '▁ఉ', '▁మార', '?', '▁ఎంత', 'ణ', 'వి', 'గ్ర'}
{'▁న్యూ', 'ను', 'ాన్ని', 'ా', 'ొ', 'లో', '▁సంవత్సరం', 'గ', '▁ఏ', '▁సిద్ధ', '▁మొదటి', 'న్నాడు', '?', 'టన్', '▁క', 'ంత'}
{'▁న్యూ', 'ను', 'ాన్ని', 'ా', 'ొ', 'లో', '▁సంవత్సరం', 'గ', '▁ఏ', '▁సిద్ధ', '▁మొదటి', 'న్నాడు', '?', 'టన్', '▁క', 'ంత'}
{'▁ఈ', 'లోకి', '▁ప్రవేశ', '▁ఎప్పుడు', '▁భారత', '▁కంపెనీ', '▁?', 'ించింది', 'స్టి', 'ండి', 'దేశం', 'యా'}
{'▁సి', 'ాన్ని', '▁ఆంధ్రప్రదేశ్', 'లో', '▁ఏ', 'జ', 'రింగ్', 'ల్', '▁ఇం', 'వి', '▁లో', 'నీ', '▁ప్రారంభించ', '▁వి', 'ారు', 'భాగ', '▁మొదట', '?', 'గా', '▁కళాశాల'}
{'▁', 'నీ', 'ద్ద', '▁అతి', 'ి', 'జర్', '▁దేశంలో', '▁చర్చ', '▁ఉంది', '?', 'పె', 'మ', '▁ఎక్కడ'}
{'▁', 'నీ', 'ద్ద', '▁అతి', 'ి', 'జర్', '▁దేశంలో', '▁చర్చ', '▁ఉంది', '?', 'పె', 'మ', '▁ఎక్కడ'}
{'▁లో', '▁ఎక్కువగా', 'ణం', '▁ఉండే', '్యా', '▁పర', 'వర', '▁?', 'వు', '▁వా', '▁ఏది', 'యు'}
{'మి', 'ొ', 'మైన', 'న', '▁ప్రా', 'ది', 'టే', '▁?', 'స', 'పొ', '▁మె', 'చీ', '▁ఎంత', 'యా'}
{'▁భారత', '▁ఆ', '▁అతి', '▁ఉన్న', 'ధ', '▁?', '▁వద్ద', 'ం', 'వంతమైన', '▁ఏది', 'దేశం', 'శక్తి', 'యు'}
{'▁జె', 'వో', '?', 'డా', 'ంగ్', '▁మరణించ', '▁మా', '▁ఎప్పుడు', 'ాడు'}
{'▁ఈ', 'లో', '▁సంవత్సరం', '▁భారత', '▁కంపెనీ', '▁ఏ', 'దేశ', '▁?', '▁వచ్చింది', 'స్టి', 'ండి', 'యా', 'ానికి'}
{'▁నెల', 'ంగ్', 'ాంగ', 'లో', '▁సంవత్సరం', '▁ఏ', 'ష్', '▁నూతన', '▁తెలుగు', 'లీ', 'ుతుంది', '▁ప్రకారం', '▁పంచ', '▁ఇ', '▁ప్రారంభ', '?', 'ం', 'మ', 'వ'}
{'కి', '▁', '▁2017', 'లో', '▁సంవత్సరం', '▁ఎక్కువ', 'నాటి', '▁వల్ల', '?', 'దో', 'యిన', 'ం', '▁చనిపో', '▁ఏది', 'మ', '▁జన'}
{'తం', '▁మ', 'లోకి', '▁ప్రవేశ', 'లో', '▁సంవత్సరం', '▁భారత', 'స్త', '▁ఏ', 'రై', '▁?', 'ించింది', 'దేశం', 'వ', '▁క్'}
{'ను', '▁లో', 'కో', 'మో', '▁ఏ', '▁ప్రవేశపెట్ట', 'ారు', 'రు', 'ాయి', 'టివ్', 'ల', '▁దేశంలో', '▁మొదట', '▁బ', '?'}
{'లోకి', '▁పన్ను', 'ప్పటి', '▁ఆ', '▁నుండి', '▁భారతీయ', '▁చట్టం', '▁ఎ', '▁అమలు', '▁వచ్చింది', '?', 'య', 'దా'}
{'కి', 'ీర్', 'స్థా', 'న్', 'స్త', '▁వి', '▁దేశ', 'త', 'జ', '?', '▁ఎంత', '▁క', 'ణ'}
{'కి', '▁ఎప్పుడు', 'న్', '▁నుండి', '▁విడి', '?', 'స్తా', '▁పా', 'పోయింది', '▁భారత్'}
{'కి', '▁ఎప్పుడు', 'న్', '▁నుండి', '▁విడి', '?', 'స్తా', '▁పా', 'పోయింది', '▁భారత్'}
{'బెల్', '▁ఎవరు', 'లో', '▁భారత', 'త్త', '▁నుండి', 'మతి', '▁మొదటి', '▁బహు', 'ౌ', 'ిన', '▁నో', 'దేశం', 'శాస్త్ర', '▁శాస్త్రం', '▁భారతీయ', '▁పొంద', '▁', 'వే', '▁భ', 'తిక', '?'}
{'▁యూ', '▁', 'ప్', 'లో', 'ద్ద', '▁అతి', 'ర', '?', 'పె', '▁ఏది', 'దేశం', '▁తూర్పు'}
{'డం', 'ంగా', 'లో', '▁కట్ట', '▁భారత', 'న', 'ిన', '?', 'కు', '▁ప్రేమ', '▁చి', '▁నిర్మించ', '▁ఏది', 'దేశం', 'హ్'}
{'▁గుర్తు', 'డం', 'లో', '▁కట్ట', '▁భారత', '▁ఉన్న', '?', 'గా', 'కు', '▁ప్రేమ', '▁ఏది', 'దేశం'}
{'▁సి', 'వర్', 'ద్ర', '▁ఏ', 'ష్', 'రూపం', '▁మార', 'ల్', 'గ్ర', '▁', 'లోకి', 'ో', 'ుతుంది', 'త', '?', '▁వద్ద', '▁ఉ', 'ణ', 'వ'}
{'▁ప్ర', 'ము', 'ించే', 'లు', 'లో', '▁భారత', '▁రాష్ట్ర', '▁న', '?', '▁ఏది', 'దేశం', 'హ', '▁అయి', 'వ', 'దు'}
{'▁ప్ర', 'ము', 'ించే', 'లు', 'లో', '▁భారత', '▁రాష్ట్ర', '▁న', '?', '▁ఏది', 'దేశం', 'హ', '▁అయి', 'వ', 'దు'}
{'▁ఎవరు', '▁అధ్యక్ష', '▁2011', '?', '▁పనిచేస', '▁అమెరికా', 'లో', 'ుడిగా', 'ారు'}
{'▁ఎవరు', '▁అధ్యక్ష', '▁2011', '?', '▁పనిచేస', '▁అమెరికా', 'లో', 'ుడిగా', 'ారు'}
{'ను', '▁రైలు', 'ొ', 'తో', '▁ఎప్పుడు', '▁ప్రారంభించ', '▁నడి', 'ారు', 'చే', '▁బ', '?', 'గ్గు'}
{'ను', '▁రైలు', 'ొ', 'తో', '▁ఎప్పుడు', '▁ప్రారంభించ', '▁నడి', 'ారు', 'చే', '▁బ', '?', 'గ్గు'}
{'▁', '▁రాష్ట్రంలో', '▁ఏ', '▁ప్రవేశపెట్ట', 'ారు', '▁పాల', 'ధన', '▁మొదట', '?', '▁ను', 'జీవ', 'సీ', '▁జాతీయ', '▁ఇం'}
{'ప', '▁ఎవరు', '▁', 'ాన్ని', 'స్థా', 'ించింది', 'ౌ', '▁బ', '?', 'ద్ధ', 'మత'}
{'ప', '▁ఎవరు', '▁', 'ాన్ని', 'స్థా', 'ించింది', 'ౌ', '▁బ', '?', 'ద్ధ', 'మత'}
{'▁లో', '▁హక్కు', '▁భారత', '▁ఎప్పుడు', '▁ప్రవేశపెట్ట', 'ారు', '▁చట్టం', 'ల', '?', '▁మానవ', 'దేశం'}
{'కి', '▁', 'లు', '▁ఎన్ని', 'లో', '▁భారత', 'గల', 'నాటి', '▁1950', 'క', '?', '▁భాష', 'వాడు', 'దేశం'}
{'ాన్ని', 'లు', 'లో', 'స్థా', '▁భారత', '▁ఏ', 'పరచ', 'ే', 'దేశం', 'యు', '▁', 'ర్', '▁?', '▁మొదట', 'గా', 'ుకున్నారు', '▁ఎక్కడ', '▁ఆంగ్ల', 'వర'}
{'▁', 'లో', 'నీ', '▁భారత', '▁వయసు', 'పురుష', 'స', '?', '▁వివాహ', '▁ఎంత', 'దేశం', '▁క', 'ుని'}
{'▁', 'లో', 'నీ', '▁భారత', '▁వయసు', 'పురుష', 'స', '?', '▁వివాహ', '▁ఎంత', 'దేశం', '▁క', 'ుని'}
{'▁జీ', '▁?', '▁సృష్టించ', 'ు', 'ిన', '▁తొలి', '▁మనుషుల', '▁ఏది', 'వి'}
{'▁జీ', '▁?', '▁సృష్టించ', 'ు', 'ిన', '▁తొలి', '▁మనుషుల', '▁ఏది', 'వి'}
{'▁కొట్ట', '▁', '▁ఎన్ని', '▁వ్యక్తి', '▁ఒక', 'గ', '▁స', 'టు', '▁?', '▁గుండె', 'సార్లు', '▁గంట', 'గా', 'కు', 'ుకుంటుంది'}
{'క్', 'లో', 'ష', '▁ఏ', '▁దేశ', '▁వా', 'టన్', '▁రాజధాని', 'జార్', 'జి', '▁కాలం', 'యా', '▁న్యూ', '▁ఉండేది', 'ింగ్', '▁', 'ర్', '?', 'గా', 'ానికి'}
{'▁మన', 'ము', '▁లో', '▁ఎన్ని', '▁సుమారు', '▁ఉన్నాయి', '▁న', '?', 'గా', '▁విశ్వ', 'ాలు', 'త్ర', 'క్ష'}
{'?', 'డా', '▁రాజధాని', '▁ఏది', '▁కె', 'న'}
{'▁ఫ', '▁క్రీ', 'ైంది', '▁బాల్', 'డ', '▁ఏ', '▁దేశంలో', 'ల', '▁అనే', 'ు', '▁మొదట', '?', 'గా', 'ట్', '▁మొద'}
{'▁దేశ', '?', '▁రాజధాని', '▁కె', '్యా', '▁ఏమిటి', 'న'}
{'▁ఎవరు', '▁', 'ను', 'ొ', 'కృత', 'న్నారు', 'గ', '్రి', '▁మొదటి', '▁ప్రపంచంలో', '▁గుండె', '?', 'ని', 'మ', '▁క'}
{'▁ఎవరు', '▁', 'ను', 'ొ', 'కృత', 'న్నారు', 'గ', '్రి', '▁మొదటి', '▁ప్రపంచంలో', '▁గుండె', '?', 'ని', 'మ', '▁క'}
{'▁వారు', 'లోకి', '▁ప్రవేశ', '▁భారత', '▁ఎప్పుడు', 'ష్', 'ి', 'ించారు', 'టీ', '?', 'దేశం', '▁బ్ర'}
{'క్', 'యూ', '▁ఇన్', 'లో', '▁భారత', '▁ఏ', '▁మొదటి', '▁ఇండియన్', 'స్టి', '▁ఉంది', 'జీ', 'నా', 'దేశం', 'ట్', '▁', '▁స్థానంలో', '▁ఆఫ్', '▁2018', '▁ట', 'ల', '?'}
{'క్', 'యూ', '▁ఇన్', 'లో', '▁భారత', '▁ఏ', '▁మొదటి', '▁ఇండియన్', 'స్టి', '▁ఉంది', 'జీ', 'నా', 'దేశం', 'ట్', '▁', '▁స్థానంలో', '▁ఆఫ్', '▁2018', '▁ట', 'ల', '?'}
{'▁ఎవరు', 'ను', '▁రా', 'ొ', 'గ', 'న్నది', '▁?', '▁జరిగే', 'ళ్ల', 'ని', '▁క'}
{'బి', 'భ్య', '▁డె', 'ల', 'త', '▁భాష', '?', '▁సంఖ్య', 'యన్', '▁ల', '▁ఎంత'}
{'▁పు', 'లో', '▁భారత', '▁అతి', 'మైన', 'తన', 'రా', '?', '▁భాష', '▁ఏది', 'దేశం'}
{'▁పు', 'లో', '▁భారత', '▁అతి', 'మైన', 'తన', 'రా', '?', '▁భాష', '▁ఏది', 'దేశం'}
{'▁యూ', '▁లో', '▁ఎన్ని', '▁ఉన్నాయి', '▁సో', '▁దేశ', '?', 'య', 'ాలు', 'యన్', 'ని', 'ట్', 'వి'}
{'▁దేశంలో', 'ళ్లు', '?', '▁ఎక్కువగా', '▁కనిపిస్త', '▁కో', '▁ఏ', 'ాయి'}
{'▁గుర్తు', 'డం', 'లో', '▁కట్ట', '▁భారత', '▁ఉన్న', '?', 'గా', 'కు', '▁ప్రేమ', '▁ఏది', 'దేశం'}
{'క్', '▁అధికార', 'ిక', 'కో', '▁దేశ', '?', '▁భాష', '▁మె', 'సి', '▁ఏది'}
{'▁స్వీ', '▁ఖ', '▁ఉంది', '?', 'ం', 'డంలో', 'న్', 'డ', '▁ఏ'}
{'▁స్వీ', '▁ఖ', '▁ఉంది', '?', 'ం', 'డంలో', 'న్', 'డ', '▁ఏ'}
{'కా', '▁జ', 'లో', '▁పే', 'భా', 'టికీ', 'నా', 'ల్', '▁నా', '▁2015', 'మి', 'రి', '▁', 'గ', '▁అత్యధిక', '▁ఆఫ్', 'గల', 'రే', 'టి', '▁నగర', '?', 'ం', 'వ'}
{'▁ఉంది', '?', '▁రాష్ట్రంలో', '▁పట్టణ', 'ం', 'స్', '▁పారి', '▁ఏ'}
{'▁', 'ను', 'ొ', 'ట్', 'స్', 'గ', 'న్న', 'దర్', 'రై', '▁ప్రయాణ', '▁సాధన', '?', 'ం', '▁క', '▁బ్ర', '▁ఏమిటి'}
{'▁మొదట', 'ను', 'ారు', '?', 'గా', '▁క్రికెట్', '▁ఎప్పుడు', '▁ఆడ', '▁ఆట'}
{'▁మొదట', 'ను', 'ారు', '?', 'గా', '▁క్రికెట్', '▁ఎప్పుడు', '▁ఆడ', '▁ఆట'}
{'▁ఎవరు', '▁', 'ాన్ని', 'సు', '▁పాల', 'ించిన', '▁దేశ', 'గ్', 'రీ', '?', 'గా', '▁రాజు', '▁చివర'}
{'▁నల్ల', 'ము', 'ించే', 'లను', '▁ఎక్కువగా', 'ండ', 'లో', '▁భారత', '▁రాష్ట్ర', '▁?', '▁ప', 'రియా', '▁ఏది', 'దేశం', '▁మి'}
{'▁పడ', '▁తిరిగి', '▁', 'ుని', '▁రావ', '▁ఎన్ని', 'గ్రహ', '▁సూర్య', '▁చుట్టూ', 'డానికి', 'ుతుంది', '?', '▁శ', 'ం', 'ని', '▁రోజులు'}
{'▁', '▁స్థానంలో', 'లో', 'ండ్', '▁ఆ', '▁ఏ', 'మతి', 'ల', '▁ఎ', '▁మొదటి', '▁ఉంది', '▁ప', '?', 'పి', 'గు', 'దేశం', 'ల్'}
{'▁', '▁స్థానంలో', 'లో', 'ండ్', '▁ఆ', '▁ఏ', 'మతి', 'ల', '▁ఎ', '▁మొదటి', '▁ఉంది', '▁ప', '?', 'పి', 'గు', 'దేశం', 'ల్'}
{'▁పి', '▁ఎవరు', '?', 'ంక్', '▁చిత్ర', '▁దర్శకుడు'}
{'▁?', '▁మొదట', 'గా', '▁ఉ', '▁ఎప్పుడు', '▁అయింది', 'బు', '▁విడుదల', 'ంటు'}
{'▁ఎవరు', '▁', '▁పై', 'టై', '▁కొ', 'మ్మ', 'త్త', 'ఫో', 'ి', 'వే', 'రా', '▁వై', '▁మొదటి', '?', '▁పరిశోధన', '▁చేసిన', 'శాస్త్ర', '▁భారతీయ'}
{'కా', 'రి', '▁', 'లో', '▁ఆఫ్', 'ద్ద', '▁అతి', '▁ఉత్తర', '?', 'పె', '▁ఏది', 'దేశం'}
{'కా', 'రి', '▁', 'లో', '▁ఆఫ్', 'ద్ద', '▁అతి', '▁ఉత్తర', '?', 'పె', '▁ఏది', 'దేశం'}
{'ాన్ని', '▁చట్ట', 'లో', '▁హక్కు', '▁భారత', '▁ఎప్పుడు', '▁ప్రవేశపెట్ట', 'ారు', 'ల', '▁?', '▁సమాచార', 'దేశం'}
{'కి', 'కా', '▁', 'రి', '▁జ', 'లో', 'నాటి', 'భా', 'ద్ద', '▁అతి', '▁ఆఫ్', '▁1990', '▁కలిగిన', '?', 'పె', '▁ఏది', 'నా', 'దేశం'}
{'▁రోజు', '▁తీస', 'కి', 'లు', '▁ఎన్ని', '▁సాధారణ', 'ుడు', '▁గుడ్', '▁?', 'ుకోవాలి', '▁మానవ'}
{'ుకున్న', '▁', '▁రా', 'స్తు', 'లు', 'గ', '▁దు', '?', 'తి', '▁మానవ', 'ంలో', 'ులు', '▁ఏమిటి', '▁వేస', 'యు'}
{'▁ఈ', '▁మాట్లాడ', '▁లో', 'ప్', '▁ప్రధాన', '?', '▁భాష', 'జి', 'ే', '▁ఏది', 'ట్'}
{'తం', 'కి', '▁స్వ', '▁ఎప్పుడు', 'న్', '▁కు', 'త్రం', '▁వచ్చింది', '?', 'స్తా', '▁పా'}
{'తం', 'కి', '▁స్వ', '▁ఎప్పుడు', 'న్', '▁కు', 'త్రం', '▁వచ్చింది', '?', 'స్తా', '▁పా'}
{'దల', '▁జీ', '▁వలన', '▁జరుగుతుంది', '?', '▁విటమిన్', '▁ఏ', 'వి', '▁పెరుగు'}
{'దల', '▁జీ', '▁వలన', '▁జరుగుతుంది', '?', '▁విటమిన్', '▁ఏ', 'వి', '▁పెరుగు'}
{'ేంద్ర', 'ము', '▁', 'లు', '▁ఎన్ని', 'లో', 'జ్ఞాన', '▁ఉన్నాయి', 'ి', '▁శరీర', '?', '▁మానవ', 'యా'}
{'▁పి', '▁గతంలో', 'బడింది', 'లోని', 'లు', 'ంగా', '▁ఒక', 'జింగ్', '▁బీ', 'మైన', '▁ఏ', '▁నగర', '▁చైనా', '?', '▁ను', 'వ'}
{'ప్', 'లో', '▁సంవత్సరం', '▁భారత', '▁టాప్', '్యా', '▁ప్రారంభించ', '▁డె', '▁కంపెనీ', '▁ఏ', '▁మొదటి', '?', '▁ను', 'ింది', '▁ల', 'దేశం', 'ల్'}
{'ింగ్', '▁ఎవరు', '▁ప్రో', 'ను', 'గ్రా', 'ారు', 'పెట్ట', '?', '▁భాష', 'ని', 'మ', '▁క'}
{'▁వాడ', 'ుతారు', 'ను', '▁ఎక్కువగా', 'లలో', '▁వంట', '▁ఏ', '▁రాష్ట్ర', '▁ప్రజలు', '?', '▁కేరళ', '▁నూనె'}
{'▁', 'ము', 'ించే', 'వరి', '▁ఎక్కువగా', 'ండ', 'లో', '▁పంట', '▁భారత', '▁రాష్ట్ర', '?', '▁ప', '▁ఏది', 'దేశం'}
{'▁దేశ', '▁మొదటి', '▁ఎవరు', '?', 'డా', '▁ముఖ్యమంత్రి', '▁కె', 'న'}
{'తో', 'గ', '▁స', '▁పుట్ట', '▁ఒక్క', 'టు', 'ు', 'వు', 'క', '?', 'గా', '▁బరువు', '▁శి', 'శు', '▁ఎంత', '▁ఉంటుంది'}
{'తో', 'గ', '▁స', '▁పుట్ట', '▁ఒక్క', 'టు', 'ు', 'వు', 'క', '?', 'గా', '▁బరువు', '▁శి', 'శు', '▁ఎంత', '▁ఉంటుంది'}
{'▁ఎవరు', '▁అధ్యక్ష', '▁2017', '?', '▁పనిచేస', '▁అమెరికా', 'ుడి', '▁గా', 'ారు'}
{'ను', '▁', '▁ప్ర', 'పై', '▁ఏ', 'బు', 'బా', 'ించారు', 'ు', '▁మొదట', '?', 'గా', 'యోగ', 'ం', 'దేశం', 'ణ', '▁అ'}
{'ను', '▁', '▁ప్ర', 'పై', '▁ఏ', 'బు', 'బా', 'ించారు', 'ు', '▁మొదట', '?', 'గా', 'యోగ', 'ం', 'దేశం', 'ణ', '▁అ'}
{'▁ఎవరు', 'ను', 'ాన్ని', 'ొ', '?', 'న్నారు', 'గ', '▁క', '▁విమాన'}
{'మల', '▁', '▁అధికార', 'ిక', '▁ఏ', '▁రాష్ట్ర', '?', '▁భాష', 'యా', 'ళ', 'ానికి'}
{'▁ఎవరు', 'మొ', 'ాన్ని', 'ద', 'టి', 'ించారు', '▁మొ', '?', 'గా', 'భారత', 'చ', '▁ర', '▁మహా', 'ట్ట'}
{'వర్గ', '▁ఎవరు', '▁', 'ను', '▁వ్యక్తి', 'పాద', 'ీకరణ', 'ించిన', '▁జీ', '▁మొదట', '▁ప్రతి', 'గా', '?', 'వుల'}
{'వర్గ', '▁ఎవరు', '▁', 'ను', '▁వ్యక్తి', 'పాద', 'ీకరణ', 'ించిన', '▁జీ', '▁మొదట', '▁ప్రతి', 'గా', '?', 'వుల'}
{'లాండ్', '▁', '▁అధికార', 'ిక', 'థ', 'ాయి', '▁దేశ', '?', '▁భాష', '▁ఏది'}
{'నీ', '▁స', 'ద్ద', '▁అతి', 'ర', 'టి', '▁?', '▁ప్రపంచంలో', '▁మంచి', 'పె', 'స్సు', '▁ఏది'}
{'▁నే', 'ము', '▁కలిగి', 'లో', '▁భారత', '▁ఎక్కువ', 'న్న', '▁రాష్ట్ర', 'రాల', 'వు', '?', '▁శాతం', '▁ఏది', 'దేశం'}
{'▁నే', 'ము', '▁కలిగి', 'లో', '▁భారత', '▁ఎక్కువ', 'న్న', '▁రాష్ట్ర', 'రాల', 'వు', '?', '▁శాతం', '▁ఏది', 'దేశం'}
{'మి', '▁కార్', '▁చట్టం', '▁మొదటి', 'క', '?', 'గా', '▁కేంద్ర', '▁చేసిన', '▁ప్రభుత్వం', '▁ఏది', '▁విడుదల'}
{'▁హిందూ', '▁దేవాలయ', 'లో', '▁భారత', '▁అతి', 'మైన', 'తన', 'రా', '▁పేరు', '?', 'ం', 'దేశం', '▁ఏమిటి', 'పు'}
{'▁ఎవరు', '▁', 'థ', 'స్', 'మో', 'టా', 'ర్', 'పెట్ట', '▁?', 'ింది', '▁ని', 'ని', '▁క', 'ట్'}
{'▁ఎవరు', '▁', 'థ', 'స్', 'మో', 'టా', 'ర్', 'పెట్ట', '▁?', 'ింది', '▁ని', 'ని', '▁క', 'ట్'}
{'రి', '?', 'డా', '▁రాజధాని', '▁ఫ్ల', 'ో', '▁ఏది'}
{'క్', 'డ్', 'బ', 'వులు', '▁ఆ', 'సై', 'సి', 'నా', '▁లో', '▁కార్', '▁ఎన్ని', 'జన్', 'న్', '▁ఉన్నాయి', '▁మొ', 'ు', '?', 'ణ', '▁అ'}
{'▁ఎవరు', 'కాలం', 'లో', '▁వ్యక్తి', '▁ఎక్కువ', 'ించిన', '▁సాగ', '▁చైనా', '?', '▁జీవిత'}
{'▁', '▁స్థానంలో', '▁వ్యవసాయ', 'టికీ', '▁రంగంలో', '▁చైనా', '▁ఉంది', '?', '▁ఎన్నో', 'దేశం', '▁2010', '▁నా'}
{'▁కథా', '▁ఎవరు', 'బో', '?', '▁రో', 'ుడు', 'నాయక', '▁చిత్ర'}
{'రి', '▁నీరు', 'ో', '▁గా', '▁ఆ', 'ష్', 'ుతుంది', 'త', '?', '▁వద్ద', '▁ఉ', '▁మార', '▁ఎంత', 'ణ', 'వి', 'గ్ర'}
{'▁ఎవరు', 'లో', '▁హక్కు', '▁భారత', 'ల', '▁మొదటి', '▁బాలిక', 'ిన', '?', '▁మహిళ', '▁పోరాడ', 'దేశం', '▁కోసం'}
{'క్', 'మి', '▁ప్ర', '▁కా', '▁లో', 'జన్', 'మైన', 'ర', 'సా', '▁చిత్రం', 'లి', '▁మొదటి', '?', '▁ఏమిటి', 'వి', '▁టె'}
{'▁భూమి', '▁ఏంటి', '▁', 'ో', 'గ్రహ', '▁తరువాత', '▁పేరు', '?', '▁నాలుగ', 'ం'}
{'▁దేశ', '▁ఏంటి', '?', 'డా', '▁రాజధాని', '▁కె', 'న'}
{'భ', 'లో', '▁భారత', '▁శా', 'న', '▁అధిక', '▁సభ్యులు', '▁కలిగిన', 'స', '?', '▁రాష్ట్రం', '▁ఏది', 'దేశం'}
{'▁', 'ధ్వ', 'గం', '▁?', '▁శ', 'ూ', '▁వే', 'ంలో', 'ని', 'న్య', '▁ఎంత'}

In [29]:
# lab_2.ipynb
vectorizer = DictVectorizer(sparse=True)
X_train = vectorizer.fit_transform(train_features)
X_validation = vectorizer.transform(validation_features)

for X in (X_train, X_validation):
    X.indices = X.indices.astype(np.int32)
    X.indptr = X.indptr.astype(np.int32)

token_classifier = SGDClassifier(
    loss="log_loss",
    alpha=1e-5,
    class_weight="balanced",
    max_iter=30,
    random_state=42,
)
start = time.time()
token_classifier.fit(X_train, train_labels)
print(f"training time: {time.time() - start:.1f}s | contexts: {len(train_lengths)} | tokens: {len(train_labels)}")

training time: 19.1s | contexts: 6335 | tokens: 920919

In [30]:
# lab_2.ipynb
def valid_bio_transition(previous_id, current_id):
    current = BIO_TAGS[int(current_id)]
    if not current.startswith("I-"):
        return True
    if previous_id is None:
        return False
    entity_type = current[2:]
    return BIO_TAGS[int(previous_id)] in {f"B-{entity_type}", f"I-{entity_type}"}

In [31]:
# lab_2.ipynb
def constrained_beam_decode(token_log_probs, class_ids, beam_size=4):
    beam = [([], 0.0)]

    for scores in token_log_probs:
        candidates = []
        for sequence, sequence_score in beam:
            previous = sequence[-1] if sequence else None
            for column, label_id in enumerate(class_ids):
                if valid_bio_transition(previous, label_id):
                    candidates.append((
                        sequence + [int(label_id)],
                        sequence_score + float(scores[column]),
                    ))
        candidates.sort(key=lambda item: item[1], reverse=True)
        beam = candidates[:beam_size]

    return beam[0][0]

In [32]:
# keeps only the first predicted span and sets all other labels to O
def first_span(labels):
    kept = ["O"] * len(labels)
    if "B-ANS" not in labels:
        return kept
    index = labels.index("B-ANS")
    kept[index] = "B-ANS"
    index += 1
    while index < len(labels) and labels[index] == "I-ANS":
        kept[index] = "I-ANS"
        index += 1
    return kept

In [33]:
# the prediction steps from the val cell below, as a function so they can be reused for train and for other seeds
def predict_labels(classifier, X, lengths):
    log_prob_sequences = split_by_lengths(classifier.predict_log_proba(X), lengths)
    beam_predictions = [
        constrained_beam_decode(scores, classifier.classes_, beam_size=4)
        for scores in log_prob_sequences
    ]
    return [first_span([BIO_TAGS[label] for label in sequence]) for sequence in beam_predictions]

In [34]:
# claude
# train
# predict
df_train["pred_labels"] = predict_labels(token_classifier, X_train, train_lengths)

In [35]:
# val
# predict
df_val["pred_labels"] = predict_labels(token_classifier, X_validation, validation_lengths)
df_val["pred_answer"] = [bio_to_character_span(context, offsets, labels)[1] for context, offsets, labels in zip(df_val["context"], df_val["offsets"], df_val["pred_labels"])]

print("predicted empty:", round((df_val["pred_answer"] == "").mean(), 3))
display(df_val[df_val["answerable"]][["lang", "question", "answer", "pred_answer"]].head(15))

predicted empty: 0.137

,lang,question,answer,pred_answer
0,te,ఒరెగాన్ రాష్ట్రంలోని అతిపెద్ద నగరం ఏది ?,Portland,
1,te,కలరా వ్యాధిని మొదటగా ఏ దేశంలో కనుగొన్నారు ?,Indian subcontinent,1817
2,te,కలరా వ్యాధిని మొదటగా ఏ దేశంలో కనుగొన్నారు ?,England,1847
3,te,మొదటి ప్రపంచ యుద్ధం ఎప్పుడు మొదలయింది ?,1914,1914
4,te,మొదటి ప్రపంచ యుద్ధం ఎప్పుడు మొదలయింది ?,28 July 1914,28
5,te,సమాచార చట్టం-2005 ను ఏ ప్రభుత్వం ఆమోదించింది?,India,11
6,te,ప్రాచీన భారతదేశంలో ఎన్ని భాషలు వాడుకలో ఉండేవి?,122,122
7,te,మనిషిని సగటున ఉండాల్సిన రక్తం ఎంత?,approximately 5 liters,A
8,te,టెక్సస్ రాష్ట్రంలోని అతిపెద్ద మానవ నిర్మితం ఏది ?,JPMorgan Chase Tower,1960
9,te,భారతదేశంలో ఓటు హక్కు పొందడానికి ఉండవలసిన కనీస ...,18,Six
10,te,టెలివిజన్ ను ఏ సంవత్సరంలో కనుగొన్నారు?,1926,John Logi
11,te,భారతదేశంలో వరి ఎక్కువగా పండే రాష్ట్రం ఏది?,West Bengal,India
12,te,భారతదేశంలో సగటుగా ఎన్ని భాషలు మాట్లాడతారు?,"122 which were spoken by more than 10,000 people",122
13,te,వాటికన్ సిటి లో పేరుగాంచిన చర్చ్ ఏది?,St. Peter's Basilica,Vatican
14,te,ఈజిప్టు దేశపు ఇంటర్నెట్ డొమైన్ కోడ్ ఏంటి?,.eg,.

### 4. Compare with a simple span baseline and evaluate according to Section 1
* **Token F1**: `B-ANS` and `I-ANS` are positive, `O` negative, pooled over all context tokens. Unanswerable items are all `O`, so they can only add false positives.
* **Exact match**: the predicted label sequence equals the gold label sequence, i.e. the same start and end token. For an unanswerable item only the empty span matches. Reported over all items and separately for answerable and unanswerable items.
* Overall and per language, always with the number of evaluated examples.

In [50]:
def evaluate_spans(df, pred_column):
    rows = []
    for lang in ["all"] + LANGUAGES:
        part = df if lang == "all" else df[df["lang"] == lang]
        gold_tokens = [label != "O" for labels in part["labels"] for label in labels]
        pred_tokens = [label != "O" for labels in part[pred_column] for label in labels]
        precision, recall, f1, _ = precision_recall_fscore_support(gold_tokens, pred_tokens, average="binary", zero_division=0)
        exact = pd.Series([gold == pred for gold, pred in zip(part["labels"], part[pred_column])], index=part.index)
        rows.append({
            "lang": lang,
            "n": len(part),
            "n_unans": (~part["answerable"]).sum(),
            "token_p": precision,
            "token_r": recall,
            "token_f1": f1,
            "exact": exact.mean(),
            "exact_ans": exact[part["answerable"]].mean(),
            "exact_unans": exact[~part["answerable"]].mean(),
        })
    return pd.DataFrame(rows).round(3)

### Empty-output baseline
Predicts the empty span (all `O`) for every item.

In [49]:
# train
df_train["pred_empty"] = [["O"] * len(labels) for labels in df_train["labels"]]
evaluate_spans(df_train, "pred_empty")

,lang,n,n_unans,token_p,token_r,token_f1,exact,exact_ans,exact_unans
0,all,6335,363,0.0,0.0,0.0,0.057,0.0,1.0
1,ar,2558,255,0.0,0.0,0.0,0.100,0.0,1.0
2,ko,2422,63,0.0,0.0,0.0,0.026,0.0,1.0
3,te,1355,45,0.0,0.0,0.0,0.033,0.0,1.0

In [48]:
# val
df_val["pred_empty"] = [["O"] * len(labels) for labels in df_val["labels"]]
evaluate_spans(df_val, "pred_empty")

,lang,n,n_unans,token_p,token_r,token_f1,exact,exact_ans,exact_unans
0,all,1155,164,0.0,0.0,0.0,0.142,0.0,1.0
1,ar,415,52,0.0,0.0,0.0,0.125,0.0,1.0
2,ko,356,19,0.0,0.0,0.0,0.053,0.0,1.0
3,te,384,93,0.0,0.0,0.0,0.242,0.0,1.0

### Question-conditioned labeller

In [47]:
# train
evaluate_spans(df_train, "pred_labels")

,lang,n,n_unans,token_p,token_r,token_f1,exact,exact_ans,exact_unans
0,all,6335,363,0.442,0.132,0.203,0.175,0.153,0.543
1,ar,2558,255,0.439,0.118,0.185,0.211,0.170,0.580
2,ko,2422,63,0.441,0.139,0.212,0.150,0.141,0.476
3,te,1355,45,0.451,0.154,0.229,0.153,0.144,0.422

In [46]:
# val
evaluate_spans(df_val, "pred_labels")

,lang,n,n_unans,token_p,token_r,token_f1,exact,exact_ans,exact_unans
0,all,1155,164,0.289,0.077,0.121,0.135,0.098,0.360
1,ar,415,52,0.291,0.074,0.117,0.142,0.107,0.385
2,ko,356,19,0.310,0.074,0.119,0.098,0.086,0.316
3,te,384,93,0.265,0.086,0.130,0.161,0.100,0.355

### Seeds
`seed = [42, 43, 44]`

In [43]:
# claude
seed_scores = []
for seed in [42, 43, 44]:
    classifier = SGDClassifier(
        loss="log_loss",
        alpha=1e-5,
        class_weight="balanced",
        max_iter=30,
        random_state=seed,
    )
    classifier.fit(X_train, train_labels)
    df_val["pred_seed"] = predict_labels(classifier, X_validation, validation_lengths)
    seed_scores.append(evaluate_spans(df_val, "pred_seed"))

pd.concat(seed_scores).groupby("lang", sort=False)[["token_f1", "exact", "exact_ans", "exact_unans"]].agg(["mean", "std"]).round(3)

     token_f1         exact        exact_ans        exact_unans
         mean    std   mean    std      mean    std        mean    std
lang
all     0.111  0.011  0.130  0.007     0.093  0.007       0.356  0.007
ar      0.108  0.009  0.141  0.005     0.102  0.006       0.410  0.029
ko      0.108  0.011  0.096  0.003     0.084  0.003       0.316  0.000
te      0.120  0.014  0.151  0.014     0.093  0.015       0.334  0.018

### Error analysis
How the predicted span relates to the gold span (val).

In [44]:
# claude
def span_outcome(gold, pred):
    gold_tokens = {index for index, label in enumerate(gold) if label != "O"}
    pred_tokens = {index for index, label in enumerate(pred) if label != "O"}
    if not gold_tokens:
        return "unans: empty" if not pred_tokens else "unans: false span"
    if not pred_tokens:
        return "ans: empty"
    if pred_tokens == gold_tokens:
        return "ans: exact"
    if pred_tokens & gold_tokens:
        return "ans: overlap"
    return "ans: wrong span"

df_val["outcome"] = [span_outcome(gold, pred) for gold, pred in zip(df_val["labels"], df_val["pred_labels"])]
pd.crosstab(df_val["outcome"], df_val["lang"], margins=True)

lang                ar   ko   te   All
outcome
ans: empty          34   35   30    99
ans: exact          39   29   29    97
ans: overlap        52   61   47   160
ans: wrong span    238  212  185   635
unans: empty        20    6   33    59
unans: false span   32   13   60   105
All                415  356  384  1155

In [45]:
# claude
# examples of wrong spans
display(df_val[df_val["outcome"] == "ans: wrong span"][["lang", "question", "answer", "pred_answer"]].head(10))

,lang,question,answer,pred_answer
1,te,కలరా వ్యాధిని మొదటగా ఏ దేశంలో కనుగొన్నారు ?,Indian subcontinent,1817
2,te,కలరా వ్యాధిని మొదటగా ఏ దేశంలో కనుగొన్నారు ?,England,1847
5,te,సమాచార చట్టం-2005 ను ఏ ప్రభుత్వం ఆమోదించింది?,India,11
7,te,మనిషిని సగటున ఉండాల్సిన రక్తం ఎంత?,approximately 5 liters,A
8,te,టెక్సస్ రాష్ట్రంలోని అతిపెద్ద మానవ నిర్మితం ఏది ?,JPMorgan Chase Tower,1960
9,te,భారతదేశంలో ఓటు హక్కు పొందడానికి ఉండవలసిన కనీస ...,18,Six
10,te,టెలివిజన్ ను ఏ సంవత్సరంలో కనుగొన్నారు?,1926,John Logi
11,te,భారతదేశంలో వరి ఎక్కువగా పండే రాష్ట్రం ఏది?,West Bengal,India
12,te,భారతదేశంలో సగటుగా ఎన్ని భాషలు మాట్లాడతారు?,"122 which were spoken by more than 10,000 people",122
13,te,వాటికన్ సిటి లో పేరుగాంచిన చర్చ్ ఏది?,St. Peter's Basilica,Vatican