# Install Dependecies

In [1]:
%%capture
%pip install -q "transformers>=5,<6"
%pip install matplotlib
%pip install ipynbname
%pip install datasets
%pip install ipywidgets

In [2]:
%%capture
%pip install torch torchvision --index-url https://download.pytorch.org/whl/cu130
%pip install ipykernel

# Imports

In [42]:
import numpy as np
import pandas as pd
import random
import torch
from datasets import load_dataset
from torch import nn
from torch.optim import Adam
from torch.utils.data import DataLoader
from tqdm.std import tqdm
from transformers import AutoTokenizer
from transformers import AutoModel
from sklearn.feature_extraction import DictVectorizer
from sklearn.linear_model import SGDClassifier

# Import datasets

In [4]:
dataset = load_dataset("coastalcph/tydi_xor_rc")
df_train = dataset["train"].to_pandas()
df_val = dataset["validation"].to_pandas()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

# Preprocessing

In [5]:
LANGUAGES = ["ar", "ko", "te"]

In [6]:
# select languages
df_train = df_train[df_train["lang"].isin(LANGUAGES)].copy()
df_val = df_val[df_val["lang"].isin(LANGUAGES)].copy()

# Tokeniser

In [7]:
tokenizer = AutoTokenizer.from_pretrained("xlm-roberta-base")

# 3 Week 37: Structured Span Prediction
* Convert the character-level answer offsets into BIO labels over context tokens. 
* Add automatic checks for at least the following cases: 
  - an answer at character 0, 
  - a multi-token answer, 
  - punctuation adjacent to an answer and an unanswerable example. 
* Document how subword pieces are handled if applicable. 
* Implement one question-conditioned sequence labeller for the group: the representation of the question must influence the predicted label for every context token. 
* Compare it with a simple span baseline. An empty-output baseline is sufficient. If you use lexical overlap, select context tokens using only overlap with the question (optionally after fixed preprocessing or translation), convert the best contiguous run to a span and never use gold answer text or offsets. The correct output for an unanswerable question is an empty span. Evaluate and analyse the models according to Section 1.

### 1. Convert the character-level answer offsets into BIO labels over context tokens

In [8]:
def tokenize_with_offsets(text):
    encoding = tokenizer(text, return_offsets_mapping=True, add_special_tokens=False)
    tokens = tokenizer.convert_ids_to_tokens(encoding["input_ids"])
    offsets = [tuple(offset) for offset in encoding["offset_mapping"]]
    return tokens, offsets

In [9]:
# lab_2.ipynb
def character_span_to_bio(context, answer_start=None, answer_text=""):
    tokens, offsets = tokenize_with_offsets(context)
    labels = ["O"] * len(tokens)

    if answer_start is None or answer_text == "":
        return tokens, offsets, labels

    answer_end = answer_start + len(answer_text)
    if context[answer_start:answer_end] != answer_text:
        raise ValueError("The supplied answer text does not match the character span")

    covered = [
        index
        for index, (start, end) in enumerate(offsets)
        if start < answer_end and end > answer_start
    ]
    if not covered:
        raise ValueError("The answer does not overlap any token")

    labels[covered[0]] = "B-ANS"
    for index in covered[1:]:
        labels[index] = "I-ANS"
    return tokens, offsets, labels

In [10]:
# lab_2.ipynb
def bio_to_character_span(context, offsets, labels):
    if len(offsets) != len(labels):
        raise ValueError("Offsets and labels must have the same length")
    if not set(labels) <= {"O", "B-ANS", "I-ANS"}:
        raise ValueError("Only O, B-ANS and I-ANS labels are supported")

    answer_indices = [
        index for index, label in enumerate(labels) if label != "O"
    ]
    if not answer_indices:
        return None, ""

    start_index = answer_indices[0]
    expected_indices = list(range(start_index, start_index + len(answer_indices)))
    expected_labels = ["B-ANS"] + ["I-ANS"] * (len(answer_indices) - 1)
    if answer_indices != expected_indices:
        raise ValueError("The labels contain multiple or non-contiguous answer spans")
    if [labels[index] for index in answer_indices] != expected_labels:
        raise ValueError("The answer span must begin with B-ANS and continue with I-ANS")

    start = offsets[answer_indices[0]][0]
    end = offsets[answer_indices[-1]][1]
    return start, context[start:end]

### Apply to both splits
Unanswerable rows have `answer_start == -1` (their `answer` column is not empty), so we key on `answerable` and give them all-`O` labels.

In [11]:
def row_to_bio(row):
    if not row["answerable"]:
        return character_span_to_bio(row["context"])
    return character_span_to_bio(row["context"], row["answer_start"], row["answer"])

In [12]:
# train
results = [row_to_bio(row) for _, row in df_train.iterrows()]
df_train["tokens"] = [tokens for tokens, offsets, labels in results]
df_train["offsets"] = [offsets for tokens, offsets, labels in results]
df_train["labels"] = [labels for tokens, offsets, labels in results]
df_train

[transformers] Token indices sequence length is longer than the specified maximum sequence length for this model (547 > 512). Running this sequence through the model will result in indexing errors

,question,context,lang,answerable,answer_start,answer,answer_inlang,tokens,offsets,labels
4792,30년 전쟁의 승자는 누구인가?,The conflict between France and Spain continue...,ko,True,21,France,None,"[▁The, ▁conflict, ▁between, ▁France, ▁and, ▁Sp...","[(0, 3), (4, 12), (13, 20), (21, 27), (28, 31)...","[O, O, O, B-ANS, O, O, O, O, O, O, O, O, O, O,..."
4793,엑스선은 누가 발견하였는가?,"X-rays make up X-radiation, a form of electrom...",ko,True,503,Wilhelm Röntgen,None,"[▁X, -, ray, s, ▁make, ▁up, ▁X, -, radi, ation...","[(0, 1), (1, 2), (2, 5), (5, 6), (7, 11), (12,...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
4794,아테네에서 언제 가장 최근의 올림픽이 올렸나요?,"In 2022, Beijing will become the first-ever ci...",ko,True,188,2004,None,"[▁In, ▁2022, ,, ▁Beijing, ▁will, ▁become, ▁the...","[(0, 2), (3, 7), (7, 8), (9, 16), (17, 21), (2...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
4795,세상에서 가장 오래된 방송사는 무엇인가?,The British Broadcasting Corporation (BBC) is ...,ko,True,4,British Broadcasting Corporation (BBC),None,"[▁The, ▁British, ▁Broadcast, ing, ▁Corporation...","[(0, 3), (4, 11), (12, 21), (21, 24), (25, 36)...","[O, B-ANS, I-ANS, I-ANS, I-ANS, I-ANS, I-ANS, ..."
4796,팔레스타인 수도는 어딘가요?,"Palestine ( '), officially the State of Palest...",ko,True,205,Jerusalem,None,"[▁Palestin, e, ▁(, ▁', ),, ▁official, ly, ▁the...","[(0, 8), (8, 9), (10, 11), (12, 13), (13, 15),...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
...,...,...,...,...,...,...,...,...,...,...
15338,소말리아는 2차 개헌을 언제 했나요?,"In February 2012, Somali government officials ...",ko,True,923,23 June 2012,None,"[▁In, ▁February, ▁2012,, ▁Somali, ▁government,...","[(0, 2), (3, 11), (12, 17), (18, 24), (25, 35)...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
15339,세상에서 가장 먼저 시작된 교통수단은 무엇인가?,The first earth tracks were created by humans ...,ko,True,160,animals,None,"[▁The, ▁first, ▁earth, ▁track, s, ▁were, ▁crea...","[(0, 3), (4, 9), (10, 15), (16, 21), (21, 22),...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
15340,2019년 이집트의 지도자는 누구인가?,"Abdel Fattah Saeed Hussein Khalil El-Sisi ( """"...",ko,True,0,Abdel Fattah Saeed Hussein Khalil El-Sisi,None,"[▁Ab, del, ▁Fat, tah, ▁Sa, eed, ▁Hussein, ▁Kha...","[(0, 2), (2, 5), (6, 9), (9, 12), (13, 15), (1...","[B-ANS, I-ANS, I-ANS, I-ANS, I-ANS, I-ANS, I-A..."
15341,독일에서 가장 인구밀도가 높은 도시는 무엇인가?,Munich (; ; ) is the capital and most populous...,ko,True,205,Berlin,None,"[▁Munich, ▁(, ;, ▁;, ▁), ▁is, ▁the, ▁capital, ...","[(0, 6), (7, 8), (8, 9), (10, 11), (12, 13), (...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
15342,개혁침례교는 신교와 상관관계가있는가?,"Anabaptism (from Neo-Latin ""anabaptista"", from...",ko,False,-1,no,None,"[▁Ana, baptis, m, ▁(, from, ▁Neo, -, La, tin, ...","[(0, 3), (3, 9), (9, 10), (11, 12), (12, 16), ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."

In [13]:
# val
results = [row_to_bio(row) for _, row in df_val.iterrows()]
df_val["tokens"] = [tokens for tokens, offsets, labels in results]
df_val["offsets"] = [offsets for tokens, offsets, labels in results]
df_val["labels"] = [labels for tokens, offsets, labels in results]
df_val

,question,context,lang,answerable,answer_start,answer,answer_inlang,tokens,offsets,labels
0,ఒరెగాన్ రాష్ట్రంలోని అతిపెద్ద నగరం ఏది ?,Portland is the largest city in the U.S. state...,te,True,0,Portland,None,"[▁Portland, ▁is, ▁the, ▁largest, ▁city, ▁in, ▁...","[(0, 8), (9, 11), (12, 15), (16, 23), (24, 28)...","[B-ANS, O, O, O, O, O, O, O, O, O, O, O, O, O,..."
1,కలరా వ్యాధిని మొదటగా ఏ దేశంలో కనుగొన్నారు ?,"The word cholera is from ""kholera"" from χολή ""...",te,True,99,Indian subcontinent,None,"[▁The, ▁word, ▁cho, lera, ▁is, ▁from, ▁"", kho,...","[(0, 3), (4, 8), (9, 12), (12, 16), (17, 19), ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
2,కలరా వ్యాధిని మొదటగా ఏ దేశంలో కనుగొన్నారు ?,Since it became widespread in the 19th century...,te,True,451,England,None,"[▁Since, ▁it, ▁became, ▁wide, spre, ad, ▁in, ▁...","[(0, 5), (6, 8), (9, 15), (16, 20), (20, 24), ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
3,మొదటి ప్రపంచ యుద్ధం ఎప్పుడు మొదలయింది ?,World War I occurred from 1914 to 1918. In ter...,te,True,26,1914,None,"[▁World, ▁War, ▁I, ▁occur, red, ▁from, ▁1914, ...","[(0, 5), (6, 9), (10, 11), (12, 17), (17, 20),...","[O, O, O, O, O, O, B-ANS, O, O, O, O, O, O, O,..."
4,మొదటి ప్రపంచ యుద్ధం ఎప్పుడు మొదలయింది ?,"World War I (often abbreviated as WWI or WW1),...",te,True,155,28 July 1914,None,"[▁World, ▁War, ▁I, ▁(, o, ften, ▁ab, brev, i, ...","[(0, 5), (6, 9), (10, 11), (12, 13), (13, 14),...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
...,...,...,...,...,...,...,...,...,...,...
3006,2011 జనగణన ప్రకారం రెయ్యలగడ్ద గ్రామములో పురుషు...,Reyyalagadda is a village belonging to Gangara...,te,True,378,37,37,"[▁Rey, ya, lag, adda, ▁is, ▁a, ▁village, ▁belo...","[(0, 3), (3, 5), (5, 8), (8, 12), (13, 15), (1...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
3007,2011 జనాభా లెక్కల ప్రకారం బూతుమిల్లిపాడు గ్రామ...,Boothumillipadu is a village in Gannavaram man...,te,True,308,433,433,"[▁Boot, hu, milli, padu, ▁is, ▁a, ▁village, ▁i...","[(0, 4), (4, 6), (6, 11), (11, 15), (16, 18), ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
3008,2011 జనాభా లెక్కల ప్రకారం మల్లవేముల గ్రామ జనాభ...,Mallavemula is a village belonging to Chagalam...,te,False,-1,1131,1131,"[▁Mall, ave, mula, ▁is, ▁a, ▁village, ▁belo, n...","[(0, 4), (4, 7), (7, 11), (12, 14), (15, 16), ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
3009,2011 నాటికి రష్యా దేశ ప్రధాన మంత్రి ఎవరు?,"Andria Urushadze (; born April 25, 1968) is a ...",te,False,-1,Vladimir Putin,వ్లాదిమిర్ పుతిన్,"[▁Andri, a, ▁Ur, usha, dze, ▁(, ;, ▁born, ▁Apr...","[(0, 5), (5, 6), (7, 9), (9, 13), (13, 16), (1...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."
3010,2011 భారత జనగణన గణాంకాల ప్రకారం గుంటూరు పట్టణ ...,"Guntur district is 11,391 sq. km. Spread over ...",te,False,-1,"743,654","743,654","[▁G, untur, ▁district, ▁is, ▁11, ,, 391, ▁s, q...","[(0, 1), (1, 6), (7, 15), (16, 18), (19, 21), ...","[O, O, O, O, O, O, O, O, O, O, O, O, O, O, O, ..."

### Round trip: labels back to a character span

In [14]:
def round_trip(row):
    start, text = bio_to_character_span(row["context"], row["offsets"], row["labels"])
    return text

In [15]:
# train
ans = df_train[df_train["answerable"]]
recovered = [round_trip(row) for _, row in ans.iterrows()]
exact = [text == answer for text, answer in zip(recovered, ans["answer"])]
contains = [answer in text for text, answer in zip(recovered, ans["answer"])]
print(f"checked: {len(ans)}; exact: {sum(exact)}; fail: {contains.count(False)}")

checked: 5972; exact: 5598; fail: 0

In [16]:
# val
ans = df_val[df_val["answerable"]]
recovered = [round_trip(row) for _, row in ans.iterrows()]
exact = [text == answer for text, answer in zip(recovered, ans["answer"])]
contains = [answer in text for text, answer in zip(recovered, ans["answer"])]
print(f"checked: {len(ans)}; exact: {sum(exact)}; fail: {contains.count(False)}")

checked: 991; exact: 941; fail: 0

### Label distribution

In [17]:
# from lab_2.ipynb: "Audit the label distribution" (adapted to string labels)
# train
label_counts = pd.Series([label for labels in df_train["labels"] for label in labels]).value_counts()
display(pd.DataFrame({"count": label_counts, "proportion": label_counts / label_counts.sum()}))

        count  proportion
O      890224    0.966669
I-ANS   24723    0.026846
B-ANS    5972    0.006485

In [18]:
# val
label_counts = pd.Series([label for labels in df_val["labels"] for label in labels]).value_counts()
display(pd.DataFrame({"count": label_counts, "proportion": label_counts / label_counts.sum()}))

        count  proportion
O      170678    0.972203
I-ANS    3889    0.022152
B-ANS     991    0.005645

In [19]:
row = df_train[df_train["answerable"]].iloc[0]
start = row["labels"].index("B-ANS")
print(row["question"] + " | " + row["answer"])
display(pd.DataFrame({"token": row["tokens"], "offset": row["offsets"], "label": row["labels"]}).iloc[start - 3:start + 4])

30년 전쟁의 승자는 누구인가? | France

        token    offset  label
0        ▁The    (0, 3)      O
1   ▁conflict   (4, 12)      O
2    ▁between  (13, 20)      O
3     ▁France  (21, 27)  B-ANS
4        ▁and  (28, 31)      O
5      ▁Spain  (32, 37)      O
6  ▁continued  (38, 47)      O

### 2. Automatic checks
1. An answer at character 0
2. A multi-token answer
3. Punctuation adjacent to an answer
4. An unanswerable example.

In [63]:
# check 1: answer at character 0
context = "NLP is the best course at DIKU."
answer = "NLP"
tokens, offsets, labels = character_span_to_bio(context, 0, answer)
print(116 * "-")
print("check 1:  answer at character 0")
print("context: ", context)
print("answer:  ", answer)
print("tokens:  ", tokens)
print("offsets: ", offsets)
print("labels:  ", labels)
print(116 * "-")
assert tokens == ["▁N", "LP", "▁is", "▁the", "▁best", "▁course", "▁at", "▁D", "IKU", "."]
assert labels == ["B-ANS", "I-ANS", "O", "O", "O", "O", "O", "O", "O", "O"]
assert bio_to_character_span(context, offsets, labels) == (0, answer)

# check 2: multi-token answer
context = "Rumour has it that Natural language processing is the only course where the homework talks back."
answer = "Natural language processing"
tokens, offsets, labels = character_span_to_bio(context, context.index(answer), answer)
print("check 2:  multi-token answer")
print("context: ", context)
print("answer:  ", answer)
print("tokens:  ", tokens)
print("offsets: ", offsets)
print("labels:  ", labels)
print(116 * "-")
assert tokens[5:9] == ["▁Natural", "▁language", "▁process", "ing"]
assert labels[5:9] == ["B-ANS", "I-ANS", "I-ANS", "I-ANS"]
assert labels[:5] == ["O"] * 5 and labels[9:] == ["O"] * 12
assert bio_to_character_span(context, offsets, labels) == (context.index(answer), answer)

# check 3: punctuation adjacent to the answer
context = "The tokenizer was last seen in Copenhagen, crying over Telegu tokens."
answer = "Copenhagen"
tokens, offsets, labels = character_span_to_bio(context, context.index(answer), answer)
print("check 3:  punctuation adjacent to the answer")
print("context: ", context)
print("answer:  ", answer)
print("tokens:  ", tokens)
print("offsets: ", offsets)
print("labels:  ", labels)
print(116 * "-")
assert tokens[8:10] == ["▁Copenhagen", ","]
assert labels[8:10] == ["B-ANS", "O"]
assert labels.count("B-ANS") == 1 and labels.count("I-ANS") == 0
assert bio_to_character_span(context, offsets, labels) == (context.index(answer), answer)

# check 4: unanswerable example
tokens, offsets, labels = character_span_to_bio(context)
print("check 4:  unanswerable example")
print("context: ", context)
print("answer:  ", answer)
print("tokens:  ", tokens)
print("offsets: ", offsets)
print("labels:  ", labels)
assert labels == ["O"] * len(tokens)
assert bio_to_character_span(context, offsets, labels) == (None, "")
print(116 * "-")

--------------------------------------------------------------------------------------------------------------------
check 1:  answer at character 0
context:  NLP is the best course at DIKU.
answer:   NLP
tokens:   ['▁N', 'LP', '▁is', '▁the', '▁best', '▁course', '▁at', '▁D', 'IKU', '.']
offsets:  [(0, 1), (1, 3), (4, 6), (7, 10), (11, 15), (16, 22), (23, 25), (26, 27), (27, 30), (30, 31)]
labels:   ['B-ANS', 'I-ANS', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']
--------------------------------------------------------------------------------------------------------------------
check 2:  multi-token answer
context:  Rumour has it that Natural language processing is the only course where the homework talks back.
answer:   Natural language processing
tokens:   ['▁Rum', 'our', '▁has', '▁it', '▁that', '▁Natural', '▁language', '▁process', 'ing', '▁is', '▁the', '▁only', '▁course', '▁where', '▁the', '▁home', 'work', '▁talk', 's', '▁back', '.']
offsets:  [(0, 3), (3, 6), (7, 10), (11, 13), (14, 18), (19, 26), (27, 35), (36, 43), (43, 46), (47, 49), (50, 53), (54, 58), (59, 65), (66, 71), (72, 75), (76, 80), (80, 84), (85, 89), (89, 90), (91, 95), (95, 96)]
labels:   ['O', 'O', 'O', 'O', 'O', 'B-ANS', 'I-ANS', 'I-ANS', 'I-ANS', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']
--------------------------------------------------------------------------------------------------------------------
check 3:  punctuation adjacent to the answer
context:  The tokenizer was last seen in Copenhagen, crying over Telegu tokens.
answer:   Copenhagen
tokens:   ['▁The', '▁to', 'ken', 'izer', '▁was', '▁last', '▁seen', '▁in', '▁Copenhagen', ',', '▁cry', 'ing', '▁over', '▁Tele', 'gu', '▁to', 'kens', '.']
offsets:  [(0, 3), (4, 6), (6, 9), (9, 13), (14, 17), (18, 22), (23, 27), (28, 30), (31, 41), (41, 42), (43, 46), (46, 49), (50, 54), (55, 59), (59, 61), (62, 64), (64, 68), (68, 69)]
labels:   ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-ANS', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']
--------------------------------------------------------------------------------------------------------------------
check 4:  unanswerable example
context:  The tokenizer was last seen in Copenhagen, crying over Telegu tokens.
answer:   Copenhagen
tokens:   ['▁The', '▁to', 'ken', 'izer', '▁was', '▁last', '▁seen', '▁in', '▁Copenhagen', ',', '▁cry', 'ing', '▁over', '▁Tele', 'gu', '▁to', 'kens', '.']
offsets:  [(0, 3), (4, 6), (6, 9), (9, 13), (14, 17), (18, 22), (23, 27), (28, 30), (31, 41), (41, 42), (43, 46), (46, 49), (50, 54), (55, 59), (59, 61), (62, 64), (64, 68), (68, 69)]
labels:   ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O']
--------------------------------------------------------------------------------------------------------------------

### 3. Implement one question-conditioned sequence labeller for the group
The representation of the question must influence the predicted label for every context token.

In [43]:
# lab_2.ipynb
BIO_TAGS = ["O", "B-ANS", "I-ANS"]
TAG_TO_ID = {tag: index for index, tag in enumerate(BIO_TAGS)}

In [ ]:
# turns the question into a set of its XLM-R pieces so that each context token can be checked if it also occurs in the question
def question_pieces_of(question):
    pieces = tokenizer.tokenize(question)
    res = set(pieces) | {piece.lower() for piece in pieces}
    print(res)
    return res

In [ ]:
# ar question word first in a sentence (reading direction: right-to-left)
# summarises the question type as its first and last piece so that the question word can be paired with each context token shape
def question_words_of(question):
    pieces = [piece for piece in tokenizer.tokenize(question) if piece not in {"?", "؟"}]
    return pieces[0] + " | " + pieces[-1]

In [ ]:
# lab_2.ipynb
def token_features(tokens, index, question_pieces, question_words):
    word = tokens[index]
    features = {
        "bias": 1.0,
        "word.lower": word.lower(),
        "word.prefix2": word[:2].lower(),
        "word.suffix2": word[-2:].lower(),
        "word.suffix3": word[-3:].lower(),
        "word.istitle": word.istitle(),
        "word.isupper": word.isupper(),
        "word.isdigit": word.isdigit(),
        "contains_hyphen": "-" in word,
        "word.in_question": word in question_pieces,  # added feature
        "word.lower_in_question": word.lower() in question_pieces,  # added feature
        "question_words|word.isdigit": f"{question_words}|{word.isdigit()}",  # added feature
        "question_words|word.istitle": f"{question_words}|{word.istitle()}",  # added feature
    }

    if index == 0:
        features["BOS"] = True
    else:
        previous = tokens[index - 1]
        features.update({
            "previous.lower": previous.lower(),
            "previous.istitle": previous.istitle(),
            "previous.isupper": previous.isupper(),
            "previous.in_question": previous in question_pieces,
        })

    if index == len(tokens) - 1:
        features["EOS"] = True
    else:
        following = tokens[index + 1]
        features.update({
            "next.lower": following.lower(),
            "next.istitle": following.istitle(),
            "next.isupper": following.isupper(),
            "next.in_question": following in question_pieces,
        })

    return features

In [ ]:
# lab_2.ipynb
def featurize(df):
    features, labels, lengths = [], [], []
    for tokens, row_labels, question in zip(df["tokens"], df["labels"], df["question"]):
        question_pieces = question_pieces_of(question)
        question_words = question_words_of(question)
        lengths.append(len(tokens))
        features.extend(token_features(tokens, index, question_pieces, question_words) for index in range(len(tokens)))
        labels.extend(TAG_TO_ID[label] for label in row_labels)
    return features, np.asarray(labels), lengths

In [68]:
# lab_2.ipynb
def split_by_lengths(values, lengths):
    sequences = []
    offset = 0
    for length in lengths:
        sequences.append(list(values[offset:offset + length]))
        offset += length
    assert offset == len(values)
    return sequences

In [69]:
# train
train_features, train_labels, train_lengths = featurize(df_train)

{'년', '인가', '의', '▁승', '▁전쟁', '자는', '▁30', '?', '▁누구'}
{'▁발견', '은', '하였', '선', '?', '엑스', '는', '▁', '▁누가', '가'}
{'이', '의', '올림픽', '?', '▁아', '나요', '▁가장', '에서', '네', '▁', '테', '▁최근', '▁올', '▁언제', '렸'}
{'▁가장', '에서', '된', '▁방송', '▁오래', '사는', '▁무엇인가', '?', '▁세상'}
{'▁수도', '인', '스타', '?', '는', '▁팔', '가요', '레', '▁어', '딘'}
{'▁많은', '▁중', '자리', '▁이루어', '리는', '?', '▁가장', '▁', '자', '▁무엇인가', '▁별', '별로', '진'}
{'▁에너지', '▁큰', '?', '▁세상', '▁가장', '는', '에서', '소', '▁발전', '▁무엇인가', '▁풍', '력'}
{'이', '은', '의', '▁15', '?', '▁루', '▁본', '명', '세', '▁무엇인가'}
{'전', '이', '텔', '된', '은', '인가', '?', '▁기업', '비', '▁처음', '▁출시', '▁', '레', '▁컬러', '▁어디'}
{'국', '▁초대', '아', '인가', '의', '제', '우리', '?', '▁누구', '는', '▁황', '▁제', '▁마'}
{'틀', '▁무슨', '▁관계', '였', '?', '는', '▁', '▁힘', '와', '히', '가', '러'}
{'율', '▁어떤', '▁실', '▁구성', '들', '▁있는', '콘', '가', '주기', '은', '에', '되어', '표', '?', '로', '▁', '▁원', '소', '리'}
{'▁일', '제', '?', '는', '점', '▁끝', '▁언제', '기는', '가', '강', '났'}
{'차', '이', '▁많은', '즈', '?', '랜', '▁외', '▁세상', '▁가장', '는', '에서', '▁프', '식', '▁무엇인가'}
{'▁취', '▁총', '의', '임', '했', '▁메', '리는', '?', '나요', '로', '▁독일', '켈', '리', '▁언제', '르'}
{'는', '▁수도', '인가', '의', '?', '▁어디', '▁영국'}
{'를', '▁먼저', '한', '인가', '▁국가', '?', '▁가장', '동', '는', '▁원', '자', '소', '▁발전', '▁가', '▁어디', '력'}
{'광', '발', '은', '하는', '가', '?', '▁달', '▁자체'}
{'은', '인가', '의', '▁배', '?', '▁달', '▁몇', '▁지구'}
{'행', '한', '의', '▁중', '▁가장', '는', '▁영화', '▁대중', '▁2019', '히', '치', '년', '적으로', '까지', '▁알', '콕', '?', '드', '▁', '흥', '프레', '▁무엇인가'}
{'년', '방', '▁일본', '▁많은', '은', '했', '비를', '▁세계', '?', '▁번째', '▁2018', '로', '▁몇', '는', '에서', '▁국', '가', '▁투자'}
{'▁종', '▁대하여', '▁출', '에', '의', '판', '인', '사는', '?', '▁기', '가요', '▁어디', '원'}
{'인', '의', '▁적', '?', '동', '는', '가요', '단체', '대', '민', '▁인', '▁어디', '군', '원'}
{'▁마지막', '▁책', '은', '의', '▁성경', '▁무엇인가', '?'}
{'된', '피', '에', '▁위', '디아', '?', '▁등록', '▁처음', '는', '▁무엇인가', '▁페이지', '키'}
{'도가', '▁인구', '▁높은', '인가', '?', '밀', '▁가장', '는', '에서', '▁어디', '▁도시', '▁호주'}
{'된', '은', '▁게임', '?', '▁세상', '▁가장', '에서', '▁온라인', '▁오래', '▁무엇인가'}
{'▁주', '인가', '▁삼', '거', '는', '▁기준', '명', '▁포', '클', '▁2019', '년', '▁인구', '를', '랜드', '은', '?', '▁몇', '지로', ',', '▁5', '월'}
{'▁높은', '률', '한', '▁역사', '을', '▁가장', '▁시청', '▁2019', '상', '방송', '년', '까지', '은', '?', '▁abc', '▁프로그램', '▁', '▁미국', '▁ABC', '▁기록', '▁무엇인가'}
{'에', '영', '?', '닥', '터', '▁몇', '▁처음', '는', '▁', '▁후', '되었', '년도', '▁방', '가'}
{'스트', '▁오', '까지', '▁얼마나', '?', '나요', '는', '▁거리', '에서', '▁되', '리아', '▁이탈리아'}
{'도가', '▁인구', '▁높은', '은', '인가', '▁중국', '▁지역', '?', '밀', '▁가장', '에서', '▁어디'}
{'스', '텔', '▁스', '한', '인가', '▁보', '▁국가', '?', '▁처음', '는', '유', '▁어디', '기를'}
{'▁가장', '▁책', '은', '의', '▁성경', '▁무엇인가', '?', '▁첫번째'}
{'곡', '스트', '▁많은', '한', '인가', '니', '?', '▁역사', '을', '▁누구', '▁가장', '는', '▁', '피아', '상', '▁작'}
{'도가', '체', '▁빠른', '▁전', '▁중', '?', '▁기', '액', '▁가장', '는', '▁', '▁열', '▁상태', ',', '▁고', '▁무엇인가'}
{'에', '했', '니', '▁전쟁', '?', '나요', '▁로', '에서', '마', '▁포', '▁승리', '가'}
{'▁오', '요', '호', '▁큰', '?', '주', '는', '마', '에서', '라', '클', '▁제일', '▁무엇인가', '▁도시'}
{'웨', '▁인구', '스트', '주의', '인가', '?', '는', '▁', '버', '지', '▁얼마', '니아'}
{'나', '라는', '▁현재', '인가', '의', '?', '▁어디', '▁청'}
{'국', '은', '▁중', '?', '을', '▁외', '있', '▁왜', '는', '화', '몽', '점', '골', '었', '하고', '▁강', '민', '가'}
{'▁자동차', '에', '?', '나요', '는', '졌', '▁한국', '▁최초', '▁언제', '▁만들어'}
{'▁첫', '?', '닥', '터', '나요', '는', '▁', '▁후', '▁되었', '▁언제', '방송'}
{'▁서', '▁창', '했', '일본', '?', '나요', '철', '▁여', '객', '도는', '▁언제', '립'}
{'멕', '은', '▁독립', '의', '코', '?', '나요', '시', '▁', '▁승인', '되었', '▁언제'}
{'은', '인', '?', '▁누구', '가요', '대', '▁대통령', '▁미국', '▁제', '▁5'}
{'이', '했', '?', '▁루', '나요', '는', '▁16', '▁국', '으로', '세', '왕', '▁언제', '위', '▁즉'}
{'에서', '▁얼마나', '▁있는', '은', '가', '?', '▁멀리', '▁달', '▁지구'}
{'폐', '인가', '의', '▁인도', '▁화', '시아', '?', '는', '네', '▁얼마'}
{'요', '란', '?', '해', '스코', '시', '▁', '▁주는', '샌', '▁속', '있는', '▁무엇인가', '프', '가'}
{'은', '▁지역', '?', '을', '▁현재', '▁뜻', '▁간', '토', '하는', '▁지방', '가', '▁어느'}
{'국', '인', '인가', '교', '?', '▁기', '독', '▁몇', '는', '개', '▁국', '▁나라', '가'}
{'년', '▁독일', '인가', '의', '자는', '?', '▁2019', '▁지도', '▁누구'}
{'▁현대', '▁누군가', '요', '은', '▁대통령', '▁중국', '?'}
{'▁일본', '의', '▁프로', '부터', '?', '▁역사', '는', '되었', '▁시작', '▁언제', '가', '야구'}
{'▁프랑스', '는', '에서', '폐', '▁사용', '▁화', '되는', '▁무엇인가', '?'}
{'▁생', '의', '장은', '▁세계', '?', '▁극', '나요', '▁처음', '에서', '▁최초', '▁나라', '겨', '▁어느', '났'}
{'는', '▁', '의', '이란', '▁무엇인가', '?', '국어'}
{'약', '▁가입', '에', '?', '▁조', '▁', '솅', '겐', '▁이', '함으로써', '▁무엇인가', '점은'}
{'는', '▁독일', '▁최대', '가요', '인', '의', '?', '▁어디', '▁도시'}
{'▁연', '바이오', '▁하는', '▁많이', '인', '?', '을', '▁생산', '는', '▁', '가요', '▁나라', '료', '▁제일', '▁어디'}
{'연합', '드는', '폴', '에', '▁가입', '했', '란', '?', '나요', '▁', '▁유럽', '▁언제'}
{'트', '집', '라는', '에', '의', '했', '?', '나요', '▁몇', '▁클', '▁이', '레', '세', '오', '파', '▁별'}
{'▁간', '는', '인가', '의', '▁명', '?', '디', '▁자녀', '▁몇'}
{'국', '를', '인가', '▁중국', '?', '▁사용하는', '로', '▁몇', '는', '▁', '▁나라', '어', '국어', '▁개'}
{'▁위', '?', '과', '나요', '▁설립', '는', '백', '▁되었', '▁언제', '키'}
{'▁가장', '는', '에서', '인가', '▁큰', '?', '▁어디', '▁영국', '▁도시'}
{'년', '▁주', '은', '의', '인가', '▁중국', '?', '▁2018', '▁누구', '석'}
{'는', '▁발견', '▁맥', '되었', '▁처음으로', '?', '▁언제', '주', '가'}
{'를', '한', '인가', '?', '파이', '▁누구', '▁처음', '▁와이', '▁사람은', '▁개발'}
{'▁무', '라는', '?', '나', '너', '졌', '는', '▁명', '▁언제', '가'}
{'에', '몬', '교', '?', '▁몇', '는', '▁', '되었', '▁몰', '년도', '▁시작', '가'}
{'년', '가요', '은', '인', '▁대통령', '▁2002', '▁중국', '?', '▁누구'}
{'▁가장', '성', '은', '▁행', '▁중', '▁무엇인가', '?', '▁강한', '력이'}
{'▁총', '은', '인가', '▁NBA', '농구', '구', '?', '▁활동', '▁몇', '단', '▁nba', '개', '▁', '에서', '하는'}
{'트', '집', '국', '▁독립', '했', '▁입', '?', '나요', '주', '헌', '는', '으로', '▁이', '▁군', '▁언제'}
{'▁높은', '인', '?', '▁2018', 'gdp', '는', '▁아시아', '에서', '▁', '가요', '▁나라', 'GDP', '▁제일', '▁어디', '가'}
{'개의', '▁주', '부', '▁남', '?', '▁몇', '에는', '▁미국', '▁있나요', '가'}
{'년', '인가', '의', '자는', '경영', '?', '▁누구', '▁최고', '▁2019', '▁애플'}
{'▁가장', '▁러시아', '는', '에서', '인가', '▁큰', '?', '▁어디', '▁도시'}
{'▁가장', '▁독일', '에서', '▁주는', '▁큰', '▁무엇인가', '?'}
{'루', '인가', '의', '▁전', '?', '설', '적', '▁호', '▁문화', '스는', '▁나라', '▁어느'}
{'은', '▁큰', '▁규모', '?', '▁기업', '▁가장', '에서', '▁한국', '▁무엇인가', '가'}
{'도가', '▁10', '천', '은', '배', '인', '▁배', '▁수', '?', '▁거', '에서', '가요', '성', '▁광', '▁사이'}
{'은', '인가', '싱', '?', '▁조', '턴', '▁된', '▁누구', '▁', '워', '으로', '▁대통령이', '▁인물', '지', '▁다음'}
{'에', '인', '?', '▁몇', '는', '개', '▁원', '가요', '자', '▁한국', '소', '▁발전', '력'}
{'▁첫번째', '시계', '▁발', '▁어디서', '?', '는', '▁', '명', '되었', '가'}
{'▁수도', '폴', '란', '?', '는', '드', '▁', '가요', '▁어', '딘'}
{'년', '요', '▁판매', '된', '▁자동차', '▁많이', '?', '▁도', '▁한', '해', '▁2018', '▁가장', '는', '에서', '타', '▁무엇인가', '동안'}
{'한', '인가', '을', '▁가장', '는', '▁선수', '년', '▁2017', '▁많은', '홈런', '?', '▁한', '해', '▁누구', '▁', '메이', '저', '▁기록', '동안', '리그'}
{'틀', '▁수도', '랜드', '?', '스코', '는', '▁', '가요', '▁어', '딘'}
{'필', '▁종교', '▁스', '요', '의', '?', '틴', '는', '버', '븐', '▁영화', '그', '▁무엇인가', '▁감독'}
{'를', '한', '인가', '?', '로', '▁누구', '▁노', '▁최초', '▁공연', '▁사람은'}
{'년', '개의', '이', '월', '?', '▁몇', '▁독일', '에는', '▁기준', '▁', '▁있는', ',', '▁대학', '▁5', '▁2019', '가'}
{'켓', '▁발', '했', '?', '을', '로', '▁로', '는', '명', '▁우주', '▁최초', '▁누가', '가'}
{'된', '인가', '▁브랜드', '▁현', '▁중', '?', '존', '▁가장', '는', '▁기타', '▁오래', '하는', '▁어디'}
{'년', '▁기간', '은', '인가', '칠', '?', '무', '▁복', '▁기준', '▁', '대', '▁대한민국', '며', ',', '▁5', '▁군', '▁2019', '월'}
{'▁교', '황', '은', '▁어디서', '▁생활', '하는', '?', '가'}
{'년', '피', '인', '은', '▁재산', '인가', '▁필', '핀', '▁2011', '?', '해', '액', '▁태', '풍', '으로', '리', '▁얼마'}
{'▁냉', '전', '는', '은', '▁되었', '▁시작', '?', '▁언제', '가'}
{'에', '?', '망', '르', '는', '▁노', '▁있는', '▁나라', '디', '가', '▁어느'}
{'는', '국', '▁태', '▁수도', '가요', '의', '▁어', '딘', '?'}
{'에', '니', '?', '해', '▁', '▁속', '▁대', '있는', '▁어느', '튀', '가', '지는', '륙'}
{'년', '전을', '기', '악', '란', '?', '▁정확', '▁몇', '▁백', '▁후기', '▁얘기', '하는', '가'}
{'▁개봉', '일', '?', '나요', '▁처음', '는', '언', '▁영화', '▁되었', '리', '▁에', '▁언제'}
{'기간', '한', '은', '인가', '▁중국', '?', '▁역사', '▁통', '▁누구', '▁가장', '에서', '▁왕', '상', '▁오랜', '치'}
{'국', '은', '되어', '유럽', '?', '▁구성', '▁몇', '으로', '▁동', '있는', '▁개', '가'}
{'년', '의', '▁계', '?', '▁현재', '▁영국', '급', '▁무엇인가', '도는', '▁2019'}
{'차', '▁일본', '인', '의', '?', '▁생산', '▁최대', '가요', '▁녹', '▁어디', '지는'}
{'▁둘', '▁물', '▁악', '▁수', '▁땅', '▁다', '?', '▁살', '과', '는', '에서', '어', '▁있을까'}
{'폴', '은', '싱', '?', '▁이름', '▁', '원의', '▁공', '▁무엇인가', '가', '▁새'}
{'▁어떤', '겼', '▁울', '▁전', '투', '▁결과', '?', '평', '해', '나요', '로', '▁나라', '▁이', '-', '가', '진'}
{'▁인구', '▁얼마나', '의', '?', '▁남아', '▁될', '는', '메', '리', '까', '카'}
{'슬', '전', '이', '▁일', '?', '▁유', '고', '▁내', '▁이유는', '어', '라', '비아', '▁무엇인가', '난'}
{'자', '성', '란', '▁중', '▁무엇인가', '?'}
{'이', '를', '할', '▁수', '?', '▁치료', '팡', '곰', '▁', '▁상처', '가', '▁있을까'}
{'이', '▁있', '▁어떤', '한', '을', '나요', '▁완전', '게', '▁되었', '▁사건', '▁인정', '받', '은', '▁독립', '▁계', '?', '기로', '▁후', '언', '▁선', '▁미국의'}
{'▁소', '▁초대', '련', '인가', '의', '자는', '?', '▁지도', '▁누구'}
{'▁종', '이', '은', '의', '올림픽', '?', '▁있었', '▁몇', '나', '▁', '목', '▁최초'}
{'주는', '스', '▁창', '인', '의', '?', '▁누구', '퍼', '드', '▁', '옥', '가요', '▁대학', '립'}
{'인가', '의', '?', 'gdp', '베', '는', '▁', '키스', '▁우주', 'GDP', '▁얼마', '탄'}
{'▁큰', '▁규모', '▁전', '투', '?', '▁역사', '▁가장', '는', '▁무엇인가', '상', '가'}
{'▁높은', '찰', '은', '▁위치한', '?', '▁곳에', '▁가장', '에서', '▁한국', '▁사', '▁무엇인가'}
{'에서', '요', '은', '▁큰', '▁강', '▁무엇인가', '▁제일', '?', '▁영국'}
{'▁생', '학', '인가', '자는', '?', '벨', '상을', '로', '▁누구', '▁노', '▁', '▁최초', '▁받은', '물'}
{'된', '?', '▁가장', '에서', '▁', '▁한국', '옹', '▁오래', '▁무엇인가', '기는'}
{'▁말', '▁무', '지에', '의', '했', '란', '구', '▁처음으로', '?', '는', '▁호', '소', '▁문', '▁누가', '가'}
{'교', '?', '는', '에서', '되었', '▁나라', '도는', '▁시작', '▁청', '가', '▁어느'}
{'를', '주의', '한', '▁전', '?', '로', '▁최초', '▁공', '리', '▁무엇인가', '파', '▁사람은'}
{'▁종', '이', '은', '의', '올림픽', '?', '▁있었', '▁몇', '나', '▁', '목', '▁최초'}
{'폴', '▁큰', '란', '?', '▁가장', '는', '드', '▁', '에서', '▁무엇인가', '▁도시'}
{'은', '민주', '▁창', '했', '?', '나요', '을', '▁독일', '당', '▁국민', '▁언제'}
{'장은', '?', '▁몇', '▁한국의', '공', '▁있는', '▁양', '조', '▁개', '가'}
{'라는', '하였', '?', '망', '나', '는', '▁', '멸', '▁언제', '▁청', '가'}
{'▁사망', '슨', '은', '의', '일', '인', '?', '닉', '▁', '가요', '▁언제'}
{'▁연', '▁스포츠', '▁출', '▁첫', '에', '한', '현', '올림픽', '인', '?', '로', '▁', '가요', '도는', '▁언제', '가', '야구'}
{'년', '▁조선', '이', '명의', '?', '▁몇', '에는', '▁', '▁있는', '▁대한민국', '족', '▁2019', '가', '▁살고'}
{'올림픽', '징', '했', '▁국가', '?', '는', '▁', '▁우승', '▁베이', '가', '야구', '▁어느'}
{'체', '은', '▁큰', '통', '?', '▁가장', '에서', '▁한국', '▁무엇인가', '▁우'}
{'국', '인가', '▁합', '초', '?', '▁몇', '는', '마', '법인', '▁나라', '▁대', '▁개', '가'}
{'▁가장', '▁성', '에서', '▁많은', '▁미국', '▁무엇인가', '?', '씨는'}
{'관', '은', '▁주', '에', '악', '?', '해', '▁백', '▁위치', '있는', '가', '▁어느'}
{'를', '▁먼저', '▁에너지', '한', '인가', '▁태양', '?', '▁누구', '▁가장', '열', '▁사람은', '▁개발'}
{'▁내용', '요', '▁이스라엘', '의', '되어', '서는', '?', '▁역사', '적인', '▁있는', '▁민', '족', '▁기록', '▁무엇인가', '들이'}
{'은', '의', '부터', '?', '권', '나요', '▁김정', '▁북한', '되었', '▁정', '▁시작', '▁언제'}
{'이', '▁많은', '인가', '?', '▁세상', '▁가장', '▁누구', '에서', '▁문', '▁사람은', '신'}
{'의', '임', '금', '▁제도', '?', '나요', '는', '▁최', '에서', '되었', '▁최초', '▁나라', '저', '▁시작', '▁어느'}
{'트', '집', '물이', '한', '인', '?', '▁시기', '▁발달', '직', '는', '에서', '가요', '▁이', '▁마', '▁언제'}
{'국', '▁수도', '▁알', '?', '는', '화', '가요', '바', '▁공', '▁어', '딘', '니아'}
{'▁오랜', '황', '기간', '은', '에', '의', '인가', '?', '▁역사', '▁누구', '▁가장', '▁천', '▁인물', '▁있던', '상', '▁자리'}
{'가요', '은', '인', '의', '▁대통령', '▁인도', '?', '▁첫번째', '▁누구'}
{'년', '▁많이', '▁소셜', '?', '▁가장', '는', '▁기준', '되고', '▁미디어', ',', '▁사용', '있는', '▁5', '▁무엇인가', '▁2019', '월'}
{'연합', '▁가입', '에', '한', '인', '?', '▁가장', '는', '가요', '▁나라', '▁최근', '▁유럽', '▁어디'}
{'된', '인가', '영', '?', '닥', '터', '▁어디', '▁처음', '는', '▁', '▁후', '년도', '▁방', '가'}
{'스', '의', '과', '에서', '▁최고', '▁말', '를', '요', '은', '다', '▁프로', '?', '나', '▁', '하나', '볼', '▁수준', '메이', '▁미국', '▁캐', '저', '▁베이', '야구', '리그'}
{'▁러시아', '요', '은', '▁대통령', '낙', '?', '▁현재', '▁누구'}
{'▁가장', '▁해', '에서', '변', '은', '▁긴', '▁중국', '?'}
{'▁출', '슨', '은', '의', '일', '인', '?', '닉', '생', '▁', '가요', '▁언제'}
{'국', '▁하는', '인가', '?', '을', '▁몇', '쌀', '는', '▁', '▁주식', '으로', '▁나라', '▁개'}
{'법을', '▁발견', '틱', '인', '?', '▁누구', '리스', '가요', '▁휴', '▁만든', '▁사람은'}
{'년', '된', '▁현', '?', '▁2018', '직', '▁세상', '▁가장', '항공', '에서', '▁', '▁오래', '▁무엇인가', '기는'}
{'▁높은', '률', '드는', '의', '터', '을', '▁시리즈', '▁가장', '▁에', '▁시청', '했던', '▁중에서', '피', '?', '닥', '▁', '▁후', '소', '▁기록', '▁무엇인가'}
{'▁측정', '▁발', '하였', '?', '▁장치', '는', '명', '▁관', '성', '▁누가', '가'}
{'인가', '범죄', '기', '징', '▁역사', '을', '▁최', '고', '상', '역', '받', '▁무', '은', '자는', '?', '▁누구', '연', '▁', '소', '▁미국', '▁선'}
{'▁가장', '에서', '은', '▁큰', '▁중국', '▁강', '▁무엇인가', '?'}
{'푸', '은', '인가', '의', '향', '?', '틴', '▁', '▁고', '▁어디'}
{'이', '황', '▁곳', '은', '인가', '?', '▁어디', '▁교', '▁지', '내는'}
{'이', '예', '인가', '의', '?', '질', '▁거', '는', '수', '▁', '대', '브라', '▁만들어', '년도', '▁언제', '상', '진'}
{'▁가장', '▁성', '에서', '당', '은', '▁큰', '▁무엇인가', '?', '▁이탈리아'}
{'졌', '은', '▁만들어', '?', '▁언제', '나요', '▁기술', '▁블록', '체인'}
{'▁서', '▁러시아', '은', '인가', '지역', '?', '늑', '대의', '식', '어', '▁어디', '디', '숲'}
{'▁인구', '많', '한', '의', '▁세계', '번째', '?', '나요', '로', '▁몇', '는', '▁', '에서', '▁나라', '불교', '가', '▁발생'}
{'▁가장', '는', '에서', '▁나라', '▁큰', '▁무엇인가', '?', '▁세상'}
{'▁산업혁명', '차', '▁일', '은', '?', '는', '▁1', '어', '▁언제', '가', '났'}
{'▁인구', '에', '인가', '▁수', '?', '는', '▁있는', '메', '▁얼마', '르'}
{'주는', '텔', '가요', '▁창', '인', '?', '▁인', '립', '▁누구'}
{'▁가장', '는', '된', '▁종교', '▁오래', '▁무엇인가', '?', '▁역사', '상'}
{'인', '?', '을', '▁블록', '▁누구', '가요', '▁만든', '▁사람은', '▁기술', '체인'}
{'년', '전', '형', '은', '악', '▁입', '?', '▁2018', '과', '시', '▁서울', '▁국', '대', '▁무엇인가'}
{'인가', '운', '?', '▁가장', '는', '에서', '▁어디', '▁더', '▁도시', '▁호주'}
{'은', '민주', '▁창', '했', '?', '나요', '▁독일', '▁사회', '당', '▁언제'}
{'년', '인가', '자는', '?', '▁2019', '▁지도', '▁미국의', '▁누구'}
{'은', '인가', '의', '향', '?', '▁', '델', '븐', '▁에', '스티', '▁고', '▁어디', '스턴'}
{'룡', '은', '에', '▁큰', '▁화', '?', '▁세상', '▁가장', '▁복', '에서', '▁있는', '본', '▁공', '▁어디', '가', '석', '원'}
{'이', '▁많은', '인가', '혼', '결', '?', '▁가장', '는', '성', '▁동', '▁나라', '▁어디'}
{'는', '▁', '▁포', '유', '▁알', '?', '류', '낳', '을'}
{'요', '갑', '사', '교', '?', '▁기', '과', '단', '는', '도', '▁무엇인가', '▁병'}
{'▁어떤', '▁주', '에', '란', '?', '해', '스코', '는', '시', '▁', '샌', '▁속', '▁있나요', '프'}
{'년', '한', '은', '인가', '제', '?', '▁시간', '▁몇', '▁기준', '▁한국의', ',', '▁5', '▁2019', '월', '▁노동'}
{'?', '▁처음', '는', '▁출시', '▁', '닌', '텐', '▁되었', '도는', '▁언제', '가'}
{'트', '집', '인', '의', '?', '는', '▁최대', '가요', '▁이', '▁어디', '▁도시'}
{'▁소', '체', '련', '은', '하였', '?', '는', '▁해', '▁언제', '가'}
{'를', '▁먼저', '한', '인가', '?', '▁가장', '는', '▁', '▁나라', '▁시작', '▁어디', '야구'}
{'▁발', '락', '했', '?', '을', '는', '▁', '명', '▁누가', '가', '음악'}
{'▁전시', '이', '스의', '트리', '은', '인가', '되어', '▁화', '?', '케', '▁', '있는', '라', '톱', '▁어디', '석', '박물관'}
{'▁산', '▁높은', '스트', '▁오', '은', '?', '▁가장', '에서', '리아', '▁무엇인가'}
{'은', '?', '▁아', '랍', '나요', '로', '브라', '▁쓰', '어', '함', '▁어떻게'}
{'도가', '▁인구', '▁높은', '인가', '▁중국', '?', '밀', '▁가장', '에서', '▁주는', '▁어디'}
{'주는', '인가', '의', '소프트', '?', '▁마이크로', '▁창업', '▁누구'}
{'전', '작', '은', '▁인천', '?', '▁펼쳐', '나', '졌', '▁상', '▁언제', '륙'}
{'▁가입', '에', 'ec', '▁o', '했', 'd', '?', 'D', 'EC', '나요', '▁프랑스', '는', '▁O', '▁언제'}
{'재', '인', '의', '사', '▁중국', '?', '가요', '소', '▁상', '하이', '▁어디', '▁청', '지는'}
{'▁불', '에', '헝', '리는', '?', '나요', '▁', '대', '▁뭐', '리', '었', '▁고', '가', '라고'}
{'▁판매', '▁많은', '한', '▁게임', '인가', '사는', '?', '을', '▁가장', '▁어디'}
{'▁수도', '은', '의', '?', '는', '▁서울', '▁대한민국', '▁되었', '▁언제', '가'}
{'국', '▁오', '만', '스', '은', '인', '의', '?', '▁누구', '가요', '대', '▁1', '▁제', '▁왕'}
{'▁많은', '한', '제', '?', '▁역사', '▁치료', '을', '▁가장', '는', '▁생명', '▁구', '▁무엇인가', '상'}
{'▁높은', '률', '한', '▁중', '터', '을', '▁시리즈', '▁가장', '▁에', '▁시청', '피', '?', '닥', '드', '▁', '▁후', '소', '▁기록', '▁무엇인가'}
{'▁가장', '▁산', '▁높은', '에서', '은', '▁무엇인가', '?', '▁스페인'}
{'▁초대', '은', '인가', '▁대통령', '?', '▁미국의', '▁누구'}
{'관', '은', '인가', '▁큰', '?', '미술', '▁세상', '▁가장', '에서', '▁', '▁어디'}
{'▁사망', '▁당시', '자는', '▁전', '투', '?', '▁몇', '망', '는', '▁노', '명', '이었', '디', '가', '르'}
{'년', '된', '▁일본', '▁판매', '수는', '▁많이', '?', '▁2018', '▁음', '▁가장', '에서', '료', '▁무엇인가'}
{'년', '인가', '의', '▁필', '핀', '자는', '?', '▁누구', '리', '▁2019', '▁지도'}
{'라이', '은', '했', '?', '터', '나요', '을', '▁음', '▁브', '엘', '언', '▁발표', '▁피', '▁가', '반', '브리', '▁언제', '▁첫번째'}
{'를', '은', '▁중국', '▁보', '?', '채', '▁현재', '▁국', '▁있는', '▁미국', '유', '하고', '▁얼마', '가'}
{'년', '은', '백화점', '▁큰', '?', '▁세상', '▁가장', '에서', '▁', '▁무엇인가', '▁2019'}
{'건설', '▁어디서', '▁세계', '?', '나요', '▁철', '에서', '▁', '되었', '도는', '▁첫번째'}
{'년', '자가', '까지', '▁많은', '에', '의', '인가', '?', '▁역사', '▁된', '▁누구', '▁가장', '▁나라', '▁나이', '▁2019', '상', '▁사람은', '▁지도'}
{'곡', '보드', '한', '인가', '위를', '?', '▁빌', '▁누구', '▁가장', '▁1', '▁오래', '가는', '▁작'}
{'인', '?', '질', '나', '▁주의', '는', '▁', '▁최대', '가요', '▁파', '브라', '라', '▁어디', '▁도시'}
{'년', '이', '까지', '황', '인가', '?', '▁역사', '로', '▁된', '▁누구', '▁', '▁최', '연', '▁교', '소', '▁2019', '상', '▁사람은'}
{'년', '▁미', '인가', '의', '자는', '?', '▁누구', '얀', '마', '▁2019', '▁지도'}
{'▁오', '은', '에', '궤', '?', '▁역사', '로', '▁', '공', '성', '▁최초', '도', '▁무엇인가', '▁인', '상', '위', '른'}
{'▁헤', '이', '스', '한', '인', '?', '럴', '는', '드', '▁', '▁라', '가요', '웰', '대학교', '▁어디', '▁졸업'}
{'▁냉', '전', '는', '은', '▁끝', '?', '▁언제', '가', '났'}
{'▁호', '개의', '에는', '▁', '▁있나요', '수가', '?', '▁영국', '▁몇'}
{'된', '?', '▁가장', '는', '에서', '▁', '▁한국', '▁오래', '연구소', '▁무엇인가'}
{'된', '▁일본', '팀', '은', '인가', '?', '▁가장', '에서', '▁', '▁오래', '▁어디', '야구'}
{'요', '은', '에', '?', '▁기', '▁어디', '생', '에서', '급', '하나', '▁사회', '▁한국', '▁속', '상', '계'}
{'된', '?', '▁가장', '는', '에서', '▁', '▁한국', '▁오래', '연구소', '▁무엇인가'}
{'국', '요', '의', '▁국가', '?', '▁프랑스', '는', '화', '공', '▁1', '▁제', '▁무엇인가'}
{'친', '차', '를', '했', '▁동안', '?', '나요', '▁통', '이나', '▁프랑스', '는', '▁식', '지', '▁코', '▁얼마', '민', '치'}
{'▁산', '▁높은', '스', '▁스', '은', '?', '▁가장', '에서', '▁무엇인가', '위'}
{'큰', '은', '했', '부터', '?', '롤', '나요', '로', '▁로', '▁장', '▁미국의', '▁발전', '▁대중', '▁언제', '음악', '르'}
{'라는', '▁당', '하였', '?', '망', '나', '는', '▁', '멸', '▁언제', '가'}
{'년', '▁말', '▁많은', '은', '점이', '▁분', '시아', '?', '레이', '▁기업', '▁가장', '▁기준', '에서', ',', '▁무엇인가', '▁2019'}
{'라는', '▁당', '했', '?', '망', '나', '는', '▁', '멸', '▁언제', '가'}
{'▁가장', '▁아시아', '에서', '▁국제', '공항', '은', '▁큰', '▁무엇인가', '?'}
{'▁러시아', '인가', '▁큰', '▁국가', '▁세계', '?', '▁번째', '로', '▁몇', '는', '에서'}
{'는', '▁', '의', '니', '지', '▁무엇인가', '?', '국어', '튀'}
{'▁연', '방', '은', '에', '▁건물', '?', '▁미국', '▁있나요', '▁대', '▁어디', '법원'}
{'▁인류', '아', '은', '?', '올', '▁처음', '쏘', '▁', '공', '성', '▁무엇인가', '▁인', '위', '가', '린'}
{'▁러시아', '인가', '운', '?', '▁가장', '는', '에서', '▁추', '▁어디', '▁도시'}
{'는', '마', '니아', '인가', '의', '▁크기', '▁얼마', '?', '▁루'}
{'요', '의', '핀', '란', '?', '용', '는', '드', '▁', '어', '▁공', '▁무엇인가'}
{'▁총', '▁난', '인가', '일', '?', '▁페이지', '기는', '▁몇', '중'}
{'은', '에', '인', '▁돈', '기', '으', '인가', '▁imf', '?', '▁몇', '▁금', '시', '▁모', '모', '당', '▁IMF', '▁운동'}
{'웨', '마크', '요', '인', '의', '니', '?', '▁루', '는', '번호', '▁', '▁등', '▁무엇인가'}
{'▁사망', '이', '은', '일', '▁중국', '?', '젠', '▁', '가요', '자', '▁철학', '언', '▁정'}
{'▁미', '에', '?', '해', '는', '얀', '마', '▁속', '▁대', '있는', '▁어느', '가', '륙'}
{'호', '폴', '▁15', '였', '▁승', '?', '▁아', '무', '나요', '로', '▁몇', '명이', '원은'}
{'은', '즈', '텍', '?', '▁아', '는', '명', '되었', '▁시작', '▁문', '▁언제', '가'}
{'는', '▁초대', '웠', '▁교회', '▁세', '?', '▁누가', '나요'}
{'듀', '▁프로', '인', '번째', '서는', '?', '▁기', '▁누구', '▁', '가요', '탑', '▁세', '어'}
{'인', '의', '▁북', '유럽', '딕', '▁국가', '?', '▁몇', '는', '개', '▁노', '가요', '르'}
{'년', '를', '▁많은', '한', '인가', '?', '▁2018', '▁가장', '는', '▁반도체', '▁나라', '▁어디', '▁수입'}
{'▁기간', '▁얼마나', '▁8', '은', '의', '?', '나요', '▁재', '헨', '▁', '▁되', '리', '세', '위'}
{'실', '▁사망', '하였', '?', '로', '는', '▁브루', '▁언제', '프', '가'}
{'▁먼저', '한', '▁게임', '은', '블', '?', '▁가장', '드', '▁출시', '▁', '에서', '자', '▁사', '리', '▁무엇인가'}
{'▁노트북', '이', '요', '▁처음으로', '?', '을', '▁회사는', '낙', '▁만든', '▁어디'}
{'은', '인가', '?', '▁법적', '▁시간', '▁몇', '시간', '▁최대', '▁한국의', '▁근무'}
{'▁회사', '▁첫', '의', '은', '인', '금', '?', '▁자본', '▁설립', '▁', '가요', '닌', '텐', '도', '▁얼마'}
{'▁프랑스', '▁끝나', '혁명', '은', '▁대', '?', '▁언제', '나요'}
{'틀', '러', '?', '는', '▁죽', '▁', '에서', '▁나라', '었', '히', '가', '▁어느'}
{'▁가장', '에서', '▁한국', '성', '은', '▁석', '▁큰', '▁무엇인가', '?'}
{'년', '슬', '곡', '스', '까지', '했', '리는', '?', '비', '을', '▁몇', '엘', '는', '▁', '프레', '▁2019', '가', '▁작'}
{'▁사망', '하였', '?', '는', '스는', '▁마', '크', '▁언제', '가', '르'}
{'이', '은', '에', '의', '범', '되는', '?', '론', '빅', '주', '▁', '▁우주', '뱅', '가', '▁포함'}
{'폰', '를', '▁스', '밥', '한', '인가', '?', '터', '케', '▁누구', '▁', '릭', '▁디자인', '지', '▁사람은'}
{'교', '?', '▁기', '독', '는', '에서', '되었', '▁나라', '▁시작', '가', '▁어느'}
{'트', '에', '코', '?', '▁몇', '인은', '는', '▁', '되었', '년도', '▁비', '▁시작', '가'}
{'국', '▁초대', '은', '인가', '의', '?', '▁누구', '▁프', '랑', '▁왕', '크', '왕'}

In [70]:
# val
validation_features, validation_labels, validation_lengths = featurize(df_val)

{'రె', 'న్', '▁?', 'ం', 'గా', '▁రాష్ట్రంలో', 'పె', '▁నగర', '▁అతి', 'ద్ద', '▁ఏది', '▁ఒ', 'ని'}
{'రా', '▁క', 'ను', '▁మొదట', '▁దేశంలో', 'గ', '▁?', 'న్నారు', 'ొ', 'గా', '▁వ్యాధి', '▁కల', '▁ఏ', 'ని'}
{'రా', '▁క', 'ను', '▁మొదట', '▁దేశంలో', 'గ', '▁?', 'న్నారు', 'ొ', 'గా', '▁వ్యాధి', '▁కల', '▁ఏ', 'ని'}
{'యింది', '▁మొద', 'ల', '▁ఎప్పుడు', '▁ప్రపంచ', '▁యుద్ధం', '▁?', '▁మొదటి'}
{'యింది', '▁మొద', 'ల', '▁ఎప్పుడు', '▁ప్రపంచ', '▁యుద్ధం', '▁?', '▁మొదటి'}
{'▁చట్టం', '▁ఆ', '?', 'మో', '▁సమాచార', 'ించింది', '▁ను', '▁ఏ', 'ద', '▁ప్రభుత్వం', '-2005'}
{'లో', 'దేశం', 'చీ', 'న', 'క', '▁ఉండే', '?', 'వి', '▁ఎన్ని', '▁ప్రా', '▁', 'వాడు', '▁భారత', '▁భాష', 'లు'}
{'గ', '▁స', '▁మనిషి', 'న', '?', 'ం', 'టు', '▁ఉండ', 'ాల్సిన', '▁ఎంత', '▁రక్త', 'ని'}
{'▁?', '▁మానవ', 'తం', 'స', '▁రాష్ట్రంలో', 'టెక్', '▁', 'మి', 'పె', '▁నిర్', '▁అతి', 'ద్ద', '▁ఏది', 'ని', 'స్'}
{'▁క', 'స్సు', 'లో', '▁హక్కు', 'డానికి', '▁పొంద', 'దేశం', '▁వ', '?', 'స', 'నీ', 'టు', '▁భారత', '▁ఉండ', '▁ఎంత', 'వలసిన', '▁ఓ', 'య'}
{'▁క', 'ను', 'లో', 'గ', 'న్నారు', '?', 'ొ', 'వి', 'లి', '▁ను', '▁సంవత్సరం', '▁ఏ', 'జన్', '▁టె'}
{'లో', 'దేశం', 'ండే', '?', '▁ఎక్కువగా', 'వరి', '▁', '▁ప', '▁భారత', '▁రాష్ట్రం', '▁ఏది'}
{'▁మాట్లాడ', 'లో', 'గ', 'దేశం', '▁స', '?', 'గా', 'టు', '▁ఎన్ని', '▁భారత', 'తారు', '▁భాష', 'లు'}
{'▁సి', 'న్', 'ంచ', '▁చర్చ', 'క', '▁వాటి', '?', 'గా', 'టి', '▁పేరు', 'ిన', '▁లో', '్', '▁ఏది'}
{'▁ఈ', 'డ్', '▁డ', 'జి', '?', '▁దేశ', 'పు', 'ొ', 'టు', 'మైన', '▁కో', '▁ఏంటి', '్', '▁ఇంటర్నెట్', 'ప్'}
{'ీర్', 'లో', 'ఫో', '▁రాష్ట్రంలో', 'ర్', 'లి', '▁వి', 'ణం', '▁పెద్ద', '▁ఏది', 'స్త', '?', '▁కా', '▁పర', 'ం', 'యా', '▁నగర', '▁అతి', 'ంగా', 'ని'}
{'నాటి', 'లో', 'కి', 'దేశం', '▁ప్రాంత', '▁ఉండే', '?', 'ం', '▁క్', 'వులు', '▁', 'రై', '▁భారత', '▁ఏది', '▁ఎక్కువ', 'స్త', '▁2010'}
{'ండా', '▁ఉ', 'డంలో', '▁ఉంది', '▁ఏ', '?', '▁ఖ', 'గా', 'ం'}
{'రా', 'లో', '▁అర', 'న్', '?', '▁ఖ', 'బ్బ', 'ీ', 'ారు', '▁ఎవరు', '▁ఏ', 'ు', '▁భాష', '▁రాస'}
{'▁ని', '▁అంటారు', '▁ఆంగ్ల', '▁ఏమ', '?', '▁జల', 'ం', 'ని', 'ంలో'}
{'లో', 'దేశం', '▁?', 'ష', 'న', 'రీ', 'రై', '▁భారత', 'బడింది', 'వ', 'పించ', 'స్త', '▁మొదట', 'గా', 'స్థా', '▁క్', '▁', '▁మి', '▁ఎక్కడ'}
{'వు', 'ుడి', '▁అవ', '▁ప్రకారం', 'వ', 'తార', '▁ఎ', 'న్న', '▁కృష్ణ', 'రా', 'ది', 'ాల', 'ాలలో', 'విష్ణు', '?', 'ణ', 'ం', '▁', '▁పు'}
{'▁ఉ', 'గ', 'ష్', '▁స', 'గ్ర', '▁మనిషి', '▁ఒక', 'కో', 'ట్టు', '▁త', 'డు', '?', 'ణ', 'గా', 'టు', 'ో', 'త', 'గల', '▁ఎంత', 'ని'}
{'▁క', 'ను', '▁క్యాన్సర్', 'గ', '▁ఎవరు', '?', 'న్నది', 'ొ', '▁ని'}
{'▁కాలం', 'చీ', 'కు', 'న', 'ింది', '?', '▁నుండి', 'రీ', '▁', '▁ప్రా', 'గ్', '▁నడి', 'చ', '▁ఏ', '▁వరకు'}
{'లో', '▁మొదట', 'దేశం', '▁మె', '?', 'మైంది', 'గా', '▁రాష్ట్రంలో', 'రై', '▁భారత', '▁ఏ', '▁ప్రారంభ', 'లు', 'ట్రో'}
{'వం', '▁మనిషి', '▁అవ', 'క', '?', '▁చనిపో', '▁పని', 'స్తుంది', '▁సమయం', 'యా', 'చే', '▁ఏ', 'య', '▁ఎక్కువ'}
{'▁క', 'క్', '▁చిత్ర', '▁ఆ', '?', 'ధా', 'ుడు', 'సి', '▁ఎవరు', 'జన్', 'నాయక'}
{'▁క', 'క్', '▁చిత్ర', '▁ఆ', '?', 'ధా', 'ుడు', 'సి', '▁ఎవరు', 'జన్', 'నాయక'}
{'లలో', '▁బై', '?', '▁అను', '▁2018', 'ించారు', '▁ఎన్ని', '▁ను', 'వ', 'ద', 'బి', '▁భాష', 'లు', '▁వరకు'}
{'ంటారు', 'తిని', '▁ఆంగ్ల', '▁ఏమ', '?', '▁నీ', 'ంలో'}
{'దు', 'స్తున్నాయి', '?', '▁ఎన్ని', '▁న', 'వ', '▁ప్ర', '▁అమెరికాలో', 'లు', 'హి'}
{'▁ప్రా', 'దేశ', '▁భారత', 'చీ', 'న', '?', '▁ఏది', '▁రాజధాని', 'ానికి'}
{'▁ఎన్ని', 'కి', '▁సాధారణ', '▁?', 'ుని', '▁నిద్ర', '▁మానవ', '▁అవసరం', '▁గంటల'}
{'▁ఎన్ని', 'కి', '▁సాధారణ', '▁?', 'ుని', '▁నిద్ర', '▁మానవ', '▁అవసరం', '▁గంటల'}
{'▁ప్రధాన', 'నాటి', '▁మంత్రి', 'కి', '▁రష్యా', '▁2011', '?', '▁దేశ', '▁', '▁ఎవరు'}
{'మంది', 'యు', 'గ', '▁ప్రపంచ', '▁స', '?', '▁చనిపో', 'గా', 'టు', '▁రెండవ', 'ారు', '▁ఎంత', 'ద్ధ', 'య', 'ంలో'}
{'▁పే', '▁చంప', 'జీ', '?', 'టి', 'మి', '▁వ్యక్తి', 'ిన', '▁గాంధీ', 'రే', 'ని'}
{'▁పే', '▁చంప', 'జీ', '?', 'టి', 'మి', '▁వ్యక్తి', 'ిన', '▁గాంధీ', 'రే', 'ని'}
{'మంది', 'లో', '▁పాలన', 'గ', 'ష్', 'ులు', '▁స', 'ి', '▁బ్ర', 'న', '?', 'టు', 'టి', 'ారు', '▁మరణించ', '▁ఎంత', '▁భారతీయ'}
{'లో', '▁పూ', 'దేశం', '▁మొత్తం', 'కు', '?', '▁రకాల', '▁ఎన్ని', '▁', '▁భారత', 'రు', 'తాయి', 'దొ', 'లు'}
{'యు', '్యా', 'వు', '▁?', 'రణ', '▁ఉండే', '▁పర', '▁ఎక్కువగా', '▁వా', 'వ', '▁ఏది', 'ంలో'}
{'▁ఉంది', '▁అత్యంత', '▁ద', '?', '▁దేశ', 'వి', '▁శక్తి', 'కా', '▁ఏ', 'వంతమైన', '▁రక్షణ', '▁నా', 'ళం', 'ానికి'}
{'▁ఉంది', '▁అత్యంత', '▁ద', '?', '▁దేశ', 'వి', '▁శక్తి', 'కా', '▁ఏ', 'వంతమైన', '▁రక్షణ', '▁నా', 'ళం', 'ానికి'}
{'▁మొదట', '▁ప్రపంచ', '▁మొదలు', '?', '▁అయ్యింది', 'గా', '▁దేశాల', '▁యుద్ధం', 'ఏ', '▁ఏ', '▁మొదటి', '▁మధ్య'}
{'▁మొదట', '▁ప్రపంచ', '▁మొదలు', '?', '▁అయ్యింది', 'గా', '▁దేశాల', '▁యుద్ధం', 'ఏ', '▁ఏ', '▁మొదటి', '▁మధ్య'}
{'ను', 'లలో', '▁బై', '?', '▁అను', 'ించారు', 'బు', '▁ఎన్ని', 'వ', 'ద', '▁2019', '▁భాష', 'లు', '▁వరకు'}
{'ాం', '▁గణ', 'గ', '▁?', 'భా', '▁2011', 'న', '▁ప్రకారం', 'ణ', '▁గుంటూరు', '▁జన', 'నా', '▁భారత', '▁ఎంత', 'కాల', '▁పట్టణ', '▁జ'}
{'▁ఉ', 'డానికి', 'ష్', '▁ఆ', 'గ్ర', '?', '▁కావాలి', 'ణ', 'గా', 'వి', 'ో', 'త', 'రి', '▁ఎంత', '▁మార', '▁నీరు'}
{'▁క', 'ను', 'గ', 'న్నారు', '?', 'ొ', 'వి', 'లి', '▁ను', '▁ఎవరు', 'జన్', '▁టె'}
{'ను', '▁ప్రచురించ', '?', '▁పీ', 'వార్', '▁', 'ారు', '▁ఎప్పుడు', '▁అండ్', '▁నవల', 'స్'}
{'ను', '▁ప్రచురించ', '?', '▁పీ', 'వార్', '▁', 'ారు', '▁ఎప్పుడు', '▁అండ్', '▁నవల', 'స్'}
{'న', '?', '▁ఏది', '▁దేశ', 'డా', '▁రాజధాని', '▁కె'}
{'▁మొదట', '▁దేశంలో', '▁ప్రవేశపెట్ట', '?', '▁విద్యుత్', '▁ను', 'ారు', 'ర', '▁ఏ', '▁సౌ', 'శక్తి'}
{'▁మొదట', '▁దేశంలో', '▁ప్రవేశపెట్ట', '?', '▁విద్యుత్', '▁ను', 'ారు', 'ర', '▁ఏ', '▁సౌ', 'శక్తి'}
{'ట్టు', '▁ఉ', 'ష్', '▁త', '▁?', 'గ్ర', 'డు', '▁మానవ', 'కో', 'ణ', '▁తక్కువ', 'ుడు', 'ో', 'త', 'గల', '▁ఎంత', 'ని'}
{'▁స్', '▁ఏంటి', '▁లే', 'కా', '▁దేశ', '?', 'ండ్', 'ట్', '▁రాజధాని'}
{'▁అధికార', 'త్', '?', '▁దేశ', '▁కొ', 'ిక', '▁ఏది', '▁సౌ', '▁భాష', 'రియా'}
{'క్', '▁సముద్ర', 'క', '?', '▁ము', 'పోయింది', '▁న', '▁', 'ౌ', 'టా', '▁టై', '▁ఏ', 'ని', 'ంలో', 'గి'}
{'▁క', 'ను', '▁బా', 'గ', 'ంబ', 'న్నారు', '?', 'ణ', 'ొ', '▁ఎవరు', 'ుని', '▁అ', 'ు'}
{'▁చంద్ర', '▁పై', '?', 'గా', 'ుడు', '▁చేసిన', '▁పేరు', '▁పరిశోధన', '▁ఏంటి', '▁సంస్థ', '▁మొదటి'}
{'▁చంద్ర', '▁పై', '?', 'గా', 'ుడు', '▁చేసిన', '▁పేరు', '▁పరిశోధన', '▁ఏంటి', '▁సంస్థ', '▁మొదటి'}
{'క్', '▁పొంద', '▁ఆర్', '▁పట్ట', 'స్ట్', 'ా', '▁మొదటి', '?', '▁కె', 'గా', 'రీ', 'ుడు', 'మి', '▁ఎవరు', 'ిన', '▁లో', '▁భారతీయ', 'ని'}
{'▁పరిచయం', 'న్', '?', 'నీ', '▁చేసిన', '▁డిస్', 'టూ', '▁ఏది', '▁మొదటి', '▁కార్'}
{'▁మ', '▁భాష', '▁ఏంటి', '▁అధికార', '▁లో', 'ిక', '?', 'నీ', 'లా'}
{'ము', '▁?', 'ంబ', 'కు', 'టు', 'న్న', '▁', 'ర', '▁అతి', 'గ్రహ', 'చి', '▁సౌ', '▁ఏది', 'ంలో'}
{'ము', '▁?', 'ంబ', 'కు', 'టు', 'న్న', '▁', 'ర', '▁అతి', 'గ్రహ', 'చి', '▁సౌ', '▁ఏది', 'ంలో'}
{'▁ఈ', '▁ఇండియా', 'దేశం', 'స్ట్', '?', '▁ఎప్పుడు', 'లోకి', '▁భారత', '▁కంపెనీ', '▁వచ్చింది'}
{'▁ఎన్ని', 'లో', '▁ఒక్క', '▁సంవత్సరం', '▁ఉంటాయి', '▁రోజులు', '?', 'ఫ్', '▁లీ'}
{'లో', '▁2017', 'వ్', 'దేశం', '▁ఆ', '?', '▁ఉన్న', 'లి', '▁', 'థ', '▁లో', '▁నూనె', '▁స్థానంలో', '▁ప్ర', '▁ఏది', '▁ఉత్పత్తి', 'మ'}
{'లో', '▁2017', 'వ్', 'దేశం', '▁ఆ', '?', '▁ఉన్న', 'లి', '▁', 'థ', '▁లో', '▁నూనె', '▁స్థానంలో', '▁ప్ర', '▁ఏది', '▁ఉత్పత్తి', 'మ'}
{'▁పోరాటం', '▁జరుగుతుంది', '?', '▁కా', '▁విషయంలో', 'ర్', '▁దేశాల', 'శ్', '▁ఏ', '▁మధ్య', 'మీ'}
{'రా', 'లో', '▁వాడ', 'ే', '▁నిత్య', '▁మానవ', '?', 'స', '▁నీటి', 'ుడు', '▁ప్రపంచంలో', 'వ', '▁ఎంత', '▁శాతం', '▁70%', 'లకు'}
{'లో', 'యు', '▁రాష్ట్రాల', '▁ఉన్నాయి', '▁సం', '?', '▁దేశ', '▁ఎన్ని', 'క్త', '▁అమెరికా', 'ాలు'}
{'ీర్', 'ము', 'దేశం', '▁?', '▁పర', 'ణ', '▁ప్రపంచంలో', '▁', '▁వి', 'పె', '▁అతి', 'ంగా', 'ద్ద', '▁ఏది', 'స్త'}
{'▁క', 'స్సు', 'లో', 'దేశం', '▁వ', '?', 'స', 'నీ', '▁చేయడానికి', 'గా', '▁పోటీ', '▁కావ', '▁భారత', 'ాల్సిన', '▁ఎంత', 'పతి', 'య', '▁రాష్ట్ర'}
{'లో', '▁2017', '▁చేస్తున్న', 'దేశం', '?', 'త్తి', '▁ఎక్కువగా', '▁ప', '▁భారత', '▁లో', '▁రాష్ట్రం', '▁ఏది', '▁ఉత్పత్తి', 'ని'}
{'డంలో', 'ంగ్', 'దేశం', '▁ఉంది', '▁ఇ', '?', '▁ఖ', 'ం', 'లాండ్', '▁', '▁ఏ'}
{'▁మొదట', '▁దేశంలో', '▁బో', 'ింది', 'తం', '?', '▁మ', 'మి', '▁ఏ', 'యన్', 'హే', '▁పుట్ట'}
{'రా', 'తన', 'దేశం', '▁ఉంది', '▁అత్యంత', '?', 'ం', '▁ఉన్న', '▁', '▁నే', '▁దేవాలయ', '▁ఎక్కడ', '▁పు', '▁హిందూ', 'పాల్'}
{'▁ఉంది', 'రాష్ట్ర', '▁సముద్ర', 'ానికి', '?', 'గా', '▁మహా', '▁రాష్ట్రం', '▁ఏ', '▁దగ్గర'}
{'▁ఉ', 'ష్', '▁ఆ', 'గ్ర', '?', 'ణ', 'గా', 'ుతుంది', 'వి', '▁వద్ద', 'ో', 'త', 'రి', '▁ఎంత', '▁మార', '▁నీరు'}
{'▁క', 'ను', 'ంత', 'లో', 'న్నాడు', 'గ', '▁సిద్ధ', 'ా', '?', 'ొ', 'ాన్ని', 'టన్', '▁న్యూ', '▁సంవత్సరం', '▁ఏ', '▁మొదటి'}
{'▁క', 'ను', 'ంత', 'లో', 'న్నాడు', 'గ', '▁సిద్ధ', 'ా', '?', 'ొ', 'ాన్ని', 'టన్', '▁న్యూ', '▁సంవత్సరం', '▁ఏ', '▁మొదటి'}
{'▁ఈ', 'దేశం', '▁?', 'ండి', 'ించింది', '▁ప్రవేశ', 'యా', '▁ఎప్పుడు', 'లోకి', 'స్టి', '▁భారత', '▁కంపెనీ'}
{'లో', '▁సి', '▁ఆంధ్రప్రదేశ్', 'ాన్ని', 'వి', '▁వి', '▁కళాశాల', 'ల్', '▁మొదట', 'భాగ', '?', 'రింగ్', 'నీ', 'గా', 'జ', 'ారు', '▁ఇం', '▁లో', '▁ఏ', '▁ప్రారంభించ'}
{'▁చర్చ', '▁దేశంలో', '▁ఉంది', 'ి', '?', 'నీ', 'జర్', '▁', 'పె', '▁ఎక్కడ', '▁అతి', 'ద్ద', 'మ'}
{'▁చర్చ', '▁దేశంలో', '▁ఉంది', 'ి', '?', 'నీ', 'జర్', '▁', 'పె', '▁ఎక్కడ', '▁అతి', 'ద్ద', 'మ'}
{'యు', '్యా', 'వు', '▁?', '▁ఉండే', '▁పర', 'వర', '▁ఎక్కువగా', '▁వా', 'ణం', '▁లో', '▁ఏది'}
{'ది', '▁?', 'చీ', '▁మె', 'పొ', 'స', 'న', 'టే', 'ొ', 'మి', '▁ప్రా', 'యా', 'మైన', '▁ఎంత'}
{'యు', 'దేశం', '▁ఆ', '▁?', 'ధ', 'ం', '▁ఉన్న', '▁వద్ద', '▁భారత', '▁అతి', 'వంతమైన', '▁ఏది', 'శక్తి'}
{'▁మా', '▁ఎప్పుడు', '▁మరణించ', 'ంగ్', 'ాడు', '▁జె', '?', 'డా', 'వో'}
{'▁ఈ', 'లో', '▁?', 'ండి', 'యా', '▁సంవత్సరం', 'దేశ', 'స్టి', '▁భారత', '▁కంపెనీ', '▁ఏ', '▁వచ్చింది', 'ానికి'}
{'లో', 'ష్', '▁ప్రకారం', '▁సంవత్సరం', 'వ', '▁పంచ', '▁ప్రారంభ', '▁తెలుగు', 'మ', 'ాంగ', 'ంగ్', '▁నెల', 'లీ', '▁ఇ', '?', 'ం', 'ుతుంది', '▁ఏ', '▁నూతన'}
{'నాటి', '▁2017', 'కి', 'లో', 'దో', 'యిన', '?', 'మ', 'ం', '▁చనిపో', '▁వల్ల', '▁జన', '▁', '▁సంవత్సరం', '▁ఏది', '▁ఎక్కువ'}
{'లో', 'దేశం', '▁?', 'తం', 'ించింది', '▁ప్రవేశ', '▁క్', '▁మ', 'రై', '▁సంవత్సరం', 'లోకి', '▁భారత', 'వ', '▁ఏ', 'స్త'}
{'ను', '▁మొదట', '▁బ', '▁దేశంలో', '▁ప్రవేశపెట్ట', '?', 'కో', 'మో', 'ల', 'ారు', 'ాయి', '▁లో', 'రు', '▁ఏ', 'టివ్'}
{'▁పన్ను', '▁చట్టం', '▁ఆ', '?', 'దా', '▁నుండి', 'లోకి', '▁ఎ', 'య', '▁భారతీయ', '▁వచ్చింది', '▁అమలు', 'ప్పటి'}
{'▁క', 'ీర్', 'కి', 'న్', '?', 'ణ', '▁దేశ', 'స్థా', 'జ', '▁వి', 'త', '▁ఎంత', 'స్త'}
{'కి', 'న్', '▁విడి', '?', 'స్తా', 'పోయింది', '▁నుండి', '▁భారత్', '▁ఎప్పుడు', '▁పా'}
{'కి', 'న్', '▁విడి', '?', 'స్తా', 'పోయింది', '▁నుండి', '▁భారత్', '▁ఎప్పుడు', '▁పా'}
{'లో', 'దేశం', '▁భ', 'తిక', 'శాస్త్ర', 'త్త', '▁భారత', '▁మొదటి', '▁భారతీయ', '▁పొంద', 'బెల్', '?', '▁శాస్త్రం', '▁నుండి', '▁', 'ౌ', '▁నో', '▁ఎవరు', 'ిన', 'మతి', '▁బహు', 'వే'}
{'లో', '▁తూర్పు', 'దేశం', '▁యూ', '?', '▁', 'పె', 'ర', '▁అతి', 'ద్ద', '▁ఏది', 'ప్'}
{'లో', 'దేశం', 'కు', 'న', '▁చి', '?', '▁నిర్మించ', 'డం', '▁కట్ట', 'హ్', '▁భారత', 'ిన', '▁ప్రేమ', 'ంగా', '▁ఏది'}
{'లో', 'దేశం', 'కు', '▁గుర్తు', '?', '▁ఉన్న', 'డం', 'గా', '▁కట్ట', '▁భారత', '▁ప్రేమ', '▁ఏది'}
{'▁ఉ', '▁సి', 'ష్', 'గ్ర', 'ద్ర', 'వర్', '▁వద్ద', 'రూపం', 'వ', '▁మార', 'ల్', '?', 'ణ', 'ుతుంది', '▁', 'ో', 'త', 'లోకి', '▁ఏ'}
{'దు', 'లో', 'ించే', 'ము', 'దేశం', '?', 'హ', '▁అయి', '▁న', '▁భారత', 'వ', '▁ప్ర', '▁ఏది', '▁రాష్ట్ర', 'లు'}
{'దు', 'లో', 'ించే', 'ము', 'దేశం', '?', 'హ', '▁అయి', '▁న', '▁భారత', 'వ', '▁ప్ర', '▁ఏది', '▁రాష్ట్ర', 'లు'}
{'▁పనిచేస', 'లో', 'ారు', '▁అమెరికా', '▁ఎవరు', '▁2011', '?', 'ుడిగా', '▁అధ్యక్ష'}
{'▁పనిచేస', 'లో', 'ారు', '▁అమెరికా', '▁ఎవరు', '▁2011', '?', 'ుడిగా', '▁అధ్యక్ష'}
{'ను', '▁బ', 'తో', '?', '▁రైలు', 'ొ', 'ారు', 'గ్గు', 'చే', '▁ఎప్పుడు', '▁నడి', '▁ప్రారంభించ'}
{'ను', '▁బ', 'తో', '?', '▁రైలు', 'ొ', 'ారు', 'గ్గు', 'చే', '▁ఎప్పుడు', '▁నడి', '▁ప్రారంభించ'}
{'సీ', '▁మొదట', '▁ప్రవేశపెట్ట', 'జీవ', '?', '▁రాష్ట్రంలో', 'ధన', '▁ను', '▁', 'ారు', '▁ఇం', '▁ఏ', '▁పాల', '▁జాతీయ'}
{'మత', '▁బ', 'ప', '?', 'ించింది', 'స్థా', 'ాన్ని', '▁', 'ౌ', '▁ఎవరు', 'ద్ధ'}
{'మత', '▁బ', 'ప', '?', 'ించింది', 'స్థా', 'ాన్ని', '▁', 'ౌ', '▁ఎవరు', 'ద్ధ'}
{'▁చట్టం', '▁హక్కు', '▁ప్రవేశపెట్ట', 'దేశం', '▁మానవ', '?', 'ల', 'ారు', '▁ఎప్పుడు', '▁భారత', '▁లో'}
{'నాటి', 'లో', 'కి', 'దేశం', '▁1950', 'క', '?', '▁ఎన్ని', '▁', 'వాడు', '▁భారత', 'గల', '▁భాష', 'లు'}
{'లో', 'యు', 'దేశం', '▁?', 'వర', 'ర్', 'ాన్ని', '▁భారత', 'ుకున్నారు', 'లు', '▁మొదట', 'ే', 'గా', 'స్థా', 'పరచ', '▁', '▁ఎక్కడ', '▁ఆంగ్ల', '▁ఏ'}
{'▁క', 'లో', 'దేశం', '?', 'స', '▁వివాహ', 'నీ', '▁', 'పురుష', '▁వయసు', '▁భారత', 'ుని', '▁ఎంత'}
{'▁క', 'లో', 'దేశం', '?', 'స', '▁వివాహ', 'నీ', '▁', 'పురుష', '▁వయసు', '▁భారత', 'ుని', '▁ఎంత'}
{'▁తొలి', '▁సృష్టించ', '▁జీ', '▁మనుషుల', '▁?', 'ిన', '▁ఏది', 'ు', 'వి'}
{'▁తొలి', '▁సృష్టించ', '▁జీ', '▁మనుషుల', '▁?', 'ిన', '▁ఏది', 'ు', 'వి'}
{'గ', '▁?', '▁స', 'కు', '▁ఒక', '▁గుండె', 'సార్లు', 'గా', 'టు', '▁ఎన్ని', '▁', '▁కొట్ట', '▁వ్యక్తి', '▁గంట', 'ుకుంటుంది'}
{'లో', 'క్', '▁కాలం', 'ష', '▁ఉండేది', 'జి', 'జార్', 'ర్', '▁న్యూ', '▁రాజధాని', 'ింగ్', '?', '▁దేశ', 'గా', 'టన్', '▁వా', '▁', 'యా', '▁ఏ', 'ానికి'}
{'ము', 'త్ర', 'క్ష', '▁ఉన్నాయి', '?', '▁సుమారు', 'గా', '▁ఎన్ని', '▁విశ్వ', '▁న', '▁లో', 'ాలు', '▁మన'}
{'న', '?', '▁ఏది', 'డా', '▁రాజధాని', '▁కె'}
{'▁మొదట', '▁దేశంలో', '▁క్రీ', 'డ', '▁అనే', '?', 'ట్', 'గా', '▁బాల్', '▁మొద', 'ల', '▁ఏ', 'ు', '▁ఫ', 'ైంది'}
{'్యా', '▁ఏమిటి', 'న', '?', '▁దేశ', '▁రాజధాని', '▁కె'}
{'▁క', '్రి', 'ను', 'గ', 'న్నారు', '▁గుండె', '?', 'ొ', 'కృత', '▁ప్రపంచంలో', '▁', '▁ఎవరు', '▁మొదటి', 'మ', 'ని'}
{'▁క', '్రి', 'ను', 'గ', 'న్నారు', '▁గుండె', '?', 'ొ', 'కృత', '▁ప్రపంచంలో', '▁', '▁ఎవరు', '▁మొదటి', 'మ', 'ని'}
{'టీ', 'ష్', 'దేశం', 'ి', '▁బ్ర', '?', 'ించారు', '▁ప్రవేశ', '▁ఎప్పుడు', 'లోకి', '▁భారత', '▁వారు'}
{'లో', 'క్', 'దేశం', 'జీ', '▁ట', 'ట్', 'ల', 'నా', '▁ఆఫ్', '▁భారత', 'స్టి', '▁ఇండియన్', '▁మొదటి', '▁ఉంది', '?', '▁2018', '▁', '▁ఇన్', '▁ఏ', '▁స్థానంలో', 'యూ'}
{'లో', 'క్', 'దేశం', 'జీ', '▁ట', 'ట్', 'ల', 'నా', '▁ఆఫ్', '▁భారత', 'స్టి', '▁ఇండియన్', '▁మొదటి', '▁ఉంది', '?', '▁2018', '▁', '▁ఇన్', '▁ఏ', '▁స్థానంలో', 'యూ'}
{'▁క', 'ను', 'గ', '▁?', 'ళ్ల', 'ొ', '▁రా', '▁ఎవరు', '▁జరిగే', 'న్నది', 'ని'}
{'▁డె', '▁ల', '?', 'ల', 'భ్య', '▁సంఖ్య', 'త', '▁ఎంత', 'యన్', 'బి', '▁భాష'}
{'రా', 'లో', 'తన', 'దేశం', '?', 'మైన', '▁భారత', '▁పు', '▁అతి', '▁ఏది', '▁భాష'}
{'రా', 'లో', 'తన', 'దేశం', '?', 'మైన', '▁భారత', '▁పు', '▁అతి', '▁ఏది', '▁భాష'}
{'▁ఉన్నాయి', '▁యూ', '?', '▁దేశ', 'ట్', 'వి', '▁ఎన్ని', '▁సో', '▁లో', 'యన్', 'ాలు', 'య', 'ని'}
{'▁కనిపిస్త', '▁దేశంలో', 'ళ్లు', '▁కో', 'ాయి', '▁ఏ', '?', '▁ఎక్కువగా'}
{'లో', 'దేశం', 'కు', '▁గుర్తు', '?', '▁ఉన్న', 'డం', 'గా', '▁కట్ట', '▁భారత', '▁ప్రేమ', '▁ఏది'}
{'క్', '▁అధికార', '▁మె', '?', 'కో', '▁దేశ', 'సి', 'ిక', '▁ఏది', '▁భాష'}
{'న్', 'డంలో', 'డ', '▁ఉంది', '▁ఏ', '?', '▁ఖ', '▁స్వీ', 'ం'}
{'న్', 'డంలో', 'డ', '▁ఉంది', '▁ఏ', '?', '▁ఖ', '▁స్వీ', 'ం'}
{'లో', 'గ', 'భా', 'టి', 'మి', 'రి', '▁ఆఫ్', 'నా', 'వ', 'టికీ', '▁అత్యధిక', 'కా', '▁నా', '▁జ', 'ల్', '▁పే', '?', 'ం', '▁', 'గల', '▁2015', '▁నగర', 'రే'}
{'▁ఉంది', '▁ఏ', '?', '▁పట్టణ', 'ం', '▁రాష్ట్రంలో', 'స్', '▁పారి'}
{'▁క', 'ను', '▁సాధన', 'దర్', 'గ', '▁ప్రయాణ', '▁బ్ర', '?', 'ం', 'ట్', 'ొ', '▁', 'రై', '▁ఏమిటి', 'స్', 'న్న'}
{'ను', '▁మొదట', 'ారు', '▁ఆట', '▁ఎప్పుడు', '▁ఆడ', '?', '▁క్రికెట్', 'గా'}
{'ను', '▁మొదట', 'ారు', '▁ఆట', '▁ఎప్పుడు', '▁ఆడ', '?', '▁క్రికెట్', 'గా'}
{'▁చివర', 'సు', '?', '▁దేశ', 'గా', 'ాన్ని', 'రీ', '▁', 'ించిన', '▁రాజు', 'గ్', '▁ఎవరు', '▁పాల'}
{'లో', 'ించే', 'ము', 'దేశం', '▁?', '▁ఎక్కువగా', 'ండ', '▁ప', '▁మి', '▁నల్ల', '▁భారత', 'లను', '▁ఏది', '▁రాష్ట్ర', 'రియా'}
{'▁పడ', 'డానికి', '?', 'ం', 'ుతుంది', '▁శ', '▁ఎన్ని', '▁', '▁సూర్య', 'ుని', '▁రావ', '▁తిరిగి', 'గ్రహ', '▁రోజులు', 'ని', '▁చుట్టూ'}
{'ల్', 'లో', 'దేశం', '▁ఆ', '▁ఉంది', 'పి', '?', 'ండ్', 'గు', 'ల', '▁', '▁ప', 'మతి', '▁ఏ', '▁స్థానంలో', '▁ఎ', '▁మొదటి'}
{'ల్', 'లో', 'దేశం', '▁ఆ', '▁ఉంది', 'పి', '?', 'ండ్', 'గు', 'ల', '▁', '▁ప', 'మతి', '▁ఏ', '▁స్థానంలో', '▁ఎ', '▁మొదటి'}
{'▁చిత్ర', '▁ఎవరు', '?', '▁పి', 'ంక్', '▁దర్శకుడు'}
{'▁విడుదల', '▁మొదట', '▁ఉ', '▁ఎప్పుడు', '▁?', '▁అయింది', 'గా', 'ంటు', 'బు'}
{'రా', '▁పై', 'ి', '▁వై', '?', '▁మొదటి', 'ఫో', 'శాస్త్ర', 'టై', 'త్త', 'మ్మ', '▁', '▁చేసిన', '▁కొ', '▁పరిశోధన', '▁ఎవరు', '▁భారతీయ', 'వే'}
{'లో', 'దేశం', '▁ఉత్తర', '?', '▁', 'పె', 'రి', '▁ఆఫ్', '▁అతి', 'ద్ద', '▁ఏది', 'కా'}
{'లో', 'దేశం', '▁ఉత్తర', '?', '▁', 'పె', 'రి', '▁ఆఫ్', '▁అతి', 'ద్ద', '▁ఏది', 'కా'}
{'లో', '▁హక్కు', '▁ప్రవేశపెట్ట', 'దేశం', '▁?', '▁చట్ట', '▁సమాచార', 'ాన్ని', 'ల', 'ారు', '▁ఎప్పుడు', '▁భారత'}
{'నాటి', 'లో', 'కి', 'దేశం', 'భా', '▁కలిగిన', '?', '▁1990', '▁', 'పె', 'రి', '▁ఆఫ్', 'నా', '▁అతి', 'ద్ద', '▁ఏది', 'కా', '▁జ'}
{'కి', 'ుకోవాలి', '▁గుడ్', '▁?', '▁రోజు', '▁తీస', '▁మానవ', '▁ఎన్ని', 'ుడు', '▁సాధారణ', 'లు'}
{'స్తు', 'యు', 'గ', 'ులు', '▁దు', '▁వేస', '▁మానవ', '?', '▁రా', '▁', 'తి', 'ుకున్న', '▁ఏమిటి', 'లు', 'ంలో'}
{'▁మాట్లాడ', '▁ప్రధాన', '▁ఈ', 'ే', 'జి', '?', 'ట్', '▁లో', '▁ఏది', '▁భాష', 'ప్'}
{'కి', 'న్', '▁స్వ', 'తం', '?', 'స్తా', 'త్రం', '▁ఎప్పుడు', '▁కు', '▁పా', '▁వచ్చింది'}
{'కి', 'న్', '▁స్వ', 'తం', '?', 'స్తా', 'త్రం', '▁ఎప్పుడు', '▁కు', '▁పా', '▁వచ్చింది'}
{'▁జీ', '▁పెరుగు', '▁జరుగుతుంది', '▁ఏ', '▁విటమిన్', '▁వలన', '?', 'దల', 'వి'}
{'▁జీ', '▁పెరుగు', '▁జరుగుతుంది', '▁ఏ', '▁విటమిన్', '▁వలన', '?', 'దల', 'వి'}
{'లో', 'ము', 'ేంద్ర', '▁ఉన్నాయి', 'ి', '▁మానవ', '?', '▁శరీర', '▁ఎన్ని', 'జ్ఞాన', '▁', 'యా', 'లు'}
{'▁గతంలో', 'లోని', '▁ఒక', '?', '▁పి', 'జింగ్', '▁ను', '▁చైనా', 'మైన', 'బడింది', '▁నగర', 'వ', '▁ఏ', '▁బీ', 'ంగా', 'లు'}
{'లో', 'ల్', '▁డె', '▁ల', 'దేశం', '్యా', 'ింది', '?', '▁ను', '▁సంవత్సరం', '▁భారత', '▁కంపెనీ', '▁ఏ', '▁మొదటి', '▁ప్రారంభించ', '▁టాప్', 'ప్'}
{'▁క', 'ను', 'గ్రా', '?', 'ింగ్', 'ారు', '▁ఎవరు', '▁ప్రో', 'మ', '▁భాష', 'ని', 'పెట్ట'}
{'ను', '▁ప్రజలు', 'ుతారు', '▁వాడ', 'లలో', '?', '▁ఎక్కువగా', '▁వంట', '▁కేరళ', '▁ఏ', '▁నూనె', '▁రాష్ట్ర'}
{'లో', 'ించే', 'ము', 'దేశం', '▁పంట', '?', '▁ఎక్కువగా', 'వరి', 'ండ', '▁', '▁ప', '▁భారత', '▁ఏది', '▁రాష్ట్ర'}
{'▁ఎవరు', 'న', '▁దేశ', '?', '▁మొదటి', 'డా', '▁కె', '▁ముఖ్యమంత్రి'}
{'తో', '▁ఒక్క', 'గ', 'వు', '▁స', '▁బరువు', 'క', '?', 'గా', 'టు', 'శు', '▁ఉంటుంది', '▁శి', '▁ఎంత', 'ు', '▁పుట్ట'}
{'తో', '▁ఒక్క', 'గ', 'వు', '▁స', '▁బరువు', 'క', '?', 'గా', 'టు', 'శు', '▁ఉంటుంది', '▁శి', '▁ఎంత', 'ు', '▁పుట్ట'}
{'▁పనిచేస', '▁2017', 'ారు', '▁అమెరికా', '▁ఎవరు', 'ుడి', '▁గా', '?', '▁అధ్యక్ష'}
{'ను', '▁మొదట', 'బా', 'దేశం', 'యోగ', '?', 'ణ', 'ం', 'ించారు', 'గా', 'బు', '▁', '▁ఏ', '▁ప్ర', '▁అ', 'ు', 'పై'}
{'ను', '▁మొదట', 'బా', 'దేశం', 'యోగ', '?', 'ణ', 'ం', 'ించారు', 'గా', 'బు', '▁', '▁ఏ', '▁ప్ర', '▁అ', 'ు', 'పై'}
{'▁క', 'ను', '▁విమాన', 'గ', '▁ఎవరు', 'న్నారు', '?', 'ొ', 'ాన్ని'}
{'▁అధికార', '?', '▁', 'యా', 'ళ', '▁ఏ', 'ిక', '▁రాష్ట్ర', '▁భాష', 'మల', 'ానికి'}
{'▁ర', 'భారత', 'ట్ట', '?', 'ించారు', 'గా', 'టి', 'ాన్ని', 'మొ', '▁మహా', '▁ఎవరు', 'చ', '▁మొ', 'ద'}
{'ను', '▁మొదట', 'పాద', '▁ప్రతి', '?', 'గా', '▁', 'వుల', '▁జీ', 'ించిన', '▁ఎవరు', 'వర్గ', '▁వ్యక్తి', 'ీకరణ'}
{'ను', '▁మొదట', 'పాద', '▁ప్రతి', '?', 'గా', '▁', 'వుల', '▁జీ', 'ించిన', '▁ఎవరు', 'వర్గ', '▁వ్యక్తి', 'ీకరణ'}
{'▁అధికార', '?', '▁దేశ', 'లాండ్', '▁', 'థ', 'ాయి', 'ిక', '▁ఏది', '▁భాష'}
{'స్సు', '▁?', '▁స', 'నీ', 'టి', '▁ప్రపంచంలో', 'పె', 'ర', '▁అతి', 'ద్ద', '▁ఏది', '▁మంచి'}
{'లో', '▁ఎక్కువ', 'ము', 'దేశం', 'వు', '?', '▁నే', '▁భారత', 'రాల', '▁కలిగి', '▁శాతం', '▁ఏది', '▁రాష్ట్ర', 'న్న'}
{'లో', '▁ఎక్కువ', 'ము', 'దేశం', 'వు', '?', '▁నే', '▁భారత', 'రాల', '▁కలిగి', '▁శాతం', '▁ఏది', '▁రాష్ట్ర', 'న్న'}
{'▁చట్టం', 'క', '?', 'గా', '▁విడుదల', 'మి', '▁చేసిన', '▁ప్రభుత్వం', '▁కేంద్ర', '▁ఏది', '▁మొదటి', '▁కార్'}
{'రా', 'లో', 'తన', 'దేశం', '?', 'ం', 'పు', 'మైన', '▁పేరు', '▁భారత', '▁దేవాలయ', '▁అతి', '▁ఏమిటి', '▁హిందూ'}
{'▁క', '▁?', 'ింది', 'మో', 'ట్', '▁ని', 'ర్', '▁', 'టా', '▁ఎవరు', 'థ', 'ని', 'స్', 'పెట్ట'}
{'▁క', '▁?', 'ింది', 'మో', 'ట్', '▁ని', 'ర్', '▁', 'టా', '▁ఎవరు', 'థ', 'ని', 'స్', 'పెట్ట'}
{'ో', 'రి', '?', '▁ఏది', 'డా', '▁రాజధాని', '▁ఫ్ల'}
{'క్', '▁ఎన్ని', 'నా', 'సై', 'బ', '▁మొ', 'ు', 'జన్', 'న్', 'డ్', '▁ఆ', '▁ఉన్నాయి', '?', 'ణ', 'వులు', 'సి', '▁లో', '▁అ', '▁కార్'}
{'కాలం', 'లో', '▁జీవిత', '?', '▁చైనా', 'ించిన', '▁ఎవరు', '▁వ్యక్తి', '▁ఎక్కువ', '▁సాగ'}
{'▁రంగంలో', 'దేశం', '▁ఉంది', '?', '▁చైనా', '▁', '▁ఎన్నో', '▁స్థానంలో', 'టికీ', '▁నా', '▁2010', '▁వ్యవసాయ'}
{'ుడు', '▁చిత్ర', '▁ఎవరు', 'నాయక', '▁రో', '?', 'బో', '▁కథా'}
{'▁ఉ', 'ష్', '▁ఆ', 'గ్ర', '?', 'ణ', 'ుతుంది', 'వి', '▁వద్ద', 'ో', 'త', 'రి', '▁ఎంత', '▁మార', '▁గా', '▁నీరు'}
{'లో', '▁హక్కు', 'దేశం', '?', 'ల', '▁మహిళ', '▁ఎవరు', '▁భారత', 'ిన', '▁పోరాడ', '▁బాలిక', '▁మొదటి', '▁కోసం'}
{'క్', '?', '▁కా', 'వి', '▁చిత్రం', 'లి', 'మి', 'మైన', 'ర', '▁లో', '▁ఏమిటి', '▁ప్ర', '▁మొదటి', 'సా', 'జన్', '▁టె'}
{'▁నాలుగ', '?', 'ం', '▁భూమి', '▁', 'ో', '▁పేరు', '▁ఏంటి', '▁తరువాత', 'గ్రహ'}
{'డా', '▁ఏంటి', 'న', '?', '▁దేశ', '▁రాజధాని', '▁కె'}
{'▁శా', 'లో', 'దేశం', '▁కలిగిన', 'న', '?', 'స', '▁భారత', 'భ', '▁సభ్యులు', '▁రాష్ట్రం', '▁ఏది', '▁అధిక'}
{'▁?', 'ూ', 'ధ్వ', 'న్య', '▁శ', '▁', '▁ఎంత', '▁వే', 'గం', 'ని', 'ంలో'}

In [54]:
# lab_2.ipynb
vectorizer = DictVectorizer(sparse=True)
X_train = vectorizer.fit_transform(train_features)
X_validation = vectorizer.transform(validation_features)

for X in (X_train, X_validation):
    X.indices = X.indices.astype(np.int32)
    X.indptr = X.indptr.astype(np.int32)

token_classifier = SGDClassifier(
    loss="log_loss",
    alpha=1e-5,
    class_weight="balanced",
    max_iter=30,
    random_state=42,
)
token_classifier.fit(X_train, train_labels)

SGDClassifier(alpha=1e-05, class_weight='balanced', loss='log_loss',
              max_iter=30, random_state=42)

In [ ]:
# lab_2.ipynb
def valid_bio_transition(previous_id, current_id):
    current = BIO_TAGS[int(current_id)]
    if not current.startswith("I-"):
        return True
    if previous_id is None:
        return False
    entity_type = current[2:]
    return BIO_TAGS[int(previous_id)] in {f"B-{entity_type}", f"I-{entity_type}"}

In [56]:
# lab_2.ipynb
def constrained_beam_decode(token_log_probs, class_ids, beam_size=4):
    beam = [([], 0.0)]

    for scores in token_log_probs:
        candidates = []
        for sequence, sequence_score in beam:
            previous = sequence[-1] if sequence else None
            for column, label_id in enumerate(class_ids):
                if valid_bio_transition(previous, label_id):
                    candidates.append((
                        sequence + [int(label_id)],
                        sequence_score + float(scores[column]),
                    ))
        candidates.sort(key=lambda item: item[1], reverse=True)
        beam = candidates[:beam_size]

    return beam[0][0]

In [ ]:
# keeps only the first predicted span and sets all other labels to O
def first_span(labels):
    kept = ["O"] * len(labels)
    if "B-ANS" not in labels:
        return kept
    index = labels.index("B-ANS")
    kept[index] = "B-ANS"
    index += 1
    while index < len(labels) and labels[index] == "I-ANS":
        kept[index] = "I-ANS"
        index += 1
    return kept

In [ ]:
# val
# predict
validation_log_probs = token_classifier.predict_log_proba(X_validation)
log_prob_sequences = split_by_lengths(validation_log_probs, validation_lengths)

beam_predictions = [
    constrained_beam_decode(scores, token_classifier.classes_, beam_size=4)
    for scores in log_prob_sequences
]

df_val["pred_labels"] = [first_span([BIO_TAGS[label] for label in sequence]) for sequence in beam_predictions]
df_val["pred_answer"] = [bio_to_character_span(context, offsets, labels)[1] for context, offsets, labels in zip(df_val["context"], df_val["offsets"], df_val["pred_labels"])]

print("predicted empty:", round((df_val["pred_answer"] == "").mean(), 3))
display(df_val[df_val["answerable"]][["lang", "question", "answer", "pred_answer"]].head(15))

predicted empty: 0.137

,lang,question,answer,pred_answer
0,te,ఒరెగాన్ రాష్ట్రంలోని అతిపెద్ద నగరం ఏది ?,Portland,
1,te,కలరా వ్యాధిని మొదటగా ఏ దేశంలో కనుగొన్నారు ?,Indian subcontinent,1817
2,te,కలరా వ్యాధిని మొదటగా ఏ దేశంలో కనుగొన్నారు ?,England,1847
3,te,మొదటి ప్రపంచ యుద్ధం ఎప్పుడు మొదలయింది ?,1914,1914
4,te,మొదటి ప్రపంచ యుద్ధం ఎప్పుడు మొదలయింది ?,28 July 1914,28
5,te,సమాచార చట్టం-2005 ను ఏ ప్రభుత్వం ఆమోదించింది?,India,11
6,te,ప్రాచీన భారతదేశంలో ఎన్ని భాషలు వాడుకలో ఉండేవి?,122,122
7,te,మనిషిని సగటున ఉండాల్సిన రక్తం ఎంత?,approximately 5 liters,A
8,te,టెక్సస్ రాష్ట్రంలోని అతిపెద్ద మానవ నిర్మితం ఏది ?,JPMorgan Chase Tower,1960
9,te,భారతదేశంలో ఓటు హక్కు పొందడానికి ఉండవలసిన కనీస ...,18,Six
10,te,టెలివిజన్ ను ఏ సంవత్సరంలో కనుగొన్నారు?,1926,John Logi
11,te,భారతదేశంలో వరి ఎక్కువగా పండే రాష్ట్రం ఏది?,West Bengal,India
12,te,భారతదేశంలో సగటుగా ఎన్ని భాషలు మాట్లాడతారు?,"122 which were spoken by more than 10,000 people",122
13,te,వాటికన్ సిటి లో పేరుగాంచిన చర్చ్ ఏది?,St. Peter's Basilica,Vatican
14,te,ఈజిప్టు దేశపు ఇంటర్నెట్ డొమైన్ కోడ్ ఏంటి?,.eg,.